### ISSUE TITLE
Full anatomical names of 72 tracts

### ISSUE THREAD

**Issue by francopestilli** [MIC-DKFZ/TractSeg#10]
Dear @wasserth and Klaus,

Great work. We have an implementation running quite swiftly on brainlife.io: https://doi.org/10.25663/bl.app.95 

Many thanks to Jakob for the help with this given to @soichih 

We are looking for a complete list of full anatomical names for the 72 tracts. I see in your paper and on the README file a list of acronyms. Would you please be kind and share with us full names for the tracts? I post here because this might be of help to the users.

Best regards,
Franco

**Comment by wasserth** [comment]
Hi Franco, great work from you guys at brainlife.io.
The full bundle names can be found in den Readme.md: https://github.com/MIC-DKFZ/TractSeg#bundle-names

**Comment by francopestilli** [comment]
@wasserth thank you!
