### ISSUE TITLE
Reading in Peaks Files Preprocessed Elsewhere

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#100]
Hello,

I am new to TractSeg. I have used the [TractoFlow](https://tractoflow-documentation.readthedocs.io/en/latest/pipeline/steps.html) pipeline to preprocess my DWI data. The output from this pipeline includes a CSD peaks .nii file (using Dipy code) that has dimensions [X,Y,Z,15]. TractSeg seems to expect an [X,Y,Z,9] nifti file for peaks. Is there anyway to use the Dipy-generated peaks file? I also have a .trk whole-brain streamlines file; could that be of use at all? My goal is to ultimately segment the brain into relevant fiber bundles and produce the [AFQ-like tract profiles](https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/Tractometry_documentation.md). Happy to provide any more information as needed.

Thanks,
Steven

**Comment by wasserth** [comment]
Hello Steven,

I am not sure what the content of the DIPY CSD Peaks file is. Therefore I can say if you can use it for TractSeg. TractSeg expects 3 peaks (=9 channels). Maybe the dipy file has 5 peaks (=15 channels) and you could simply use the 3 biggest peaks. But not sure if this is the case.

The whole brain tractogram is not needed by TractSeg at any step.

To get AFQ like tract profiles just follow the Tractometry tutorial. This should be straight forward and the runtime should also not be too bad. So the only thing you are missing are the input peaks. I am always using Mrtrix to generate those. I find that fairly easy. If you have installed mrtrix you can call TractSeg with the option `--raw_diffusion_input` and it will automatically call the right mrtrix commands for you.

I hope that answered your questions.

**Comment by smeisler** [comment]
That makes sense, thanks for the quick reply! I have used the --raw_diffusion_input argument to generate the peaks and it has worked thus far; just would have been nice to cut down on redundancies if possible. I'll see if it's possible to only generate the 3 peaks from Dipy/Tractoflow.
