### ISSUE TITLE
aslant

### ISSUE THREAD

**Issue by aver123** [MIC-DKFZ/TractSeg#101]
Dear TractSeg experts, 
I was wondering if there is any plan to include the frontal aslant tract in the TractSeg segmentation in the near feature. 
Thanks, Amy

**Comment by wasserth** [comment]
Hi Amy,
there are no plans to include it so far.

**Comment by aver123** [comment]
I see. Thanks a lot for getting back! 
Amy

**Comment by aver123** [comment]
Somewhat related... I saw that tractseg can use the dmri.bedpostx folder to use xtract segmentation using: TractSeg -i peaks.nii.gz --tract_definition xtract
I get: TractSeg: error: argument --tract_definition: invalid choice: 'xtract' (choose from 'TractQuerier+', 'AutoPTX')

I am using TractSeg 2.1.1. I assume I should use https://github.com/MIC-DKFZ/TractSeg/blob/master/bin/TractSeg.  

-- question: how do I point TractSeg to my bedpostX folder?  

Thanks!

**Comment by wasserth** [comment]
You have to use the latest Master of TractSeg to be able to choose `xtract`:
```
pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
```
It is not part of 2.1.1 (I guess I should release a newer version).

Using fsl bedpostx folder as input (instead of mrtrix peaks) is independent from the `--tract_definition` option. You can do it like the following: 
```
TractSeg -i my_bedpostx_folder/dyads1.nii.gz
```
