### ISSUE TITLE
Export Centroids of streamlines during tractometry

### ISSUE THREAD

**Issue by Davi05d** [MIC-DKFZ/TractSeg#102]
Hi Jacob,
thank you very much for a wonderful tool. It is very useful. 
I would like to ask, is it possible to somehow export (save) Centroids and (and their segments) of individual bundles that are calculated during tractometry? Either as .nii Image or as coordinates.

I have tried to dig little bit in your code but I am afraid my python skills are not suffitient for such task. Is there some easy way to do that?

thank you very much

kind regards
David

**Comment by wasserth** [comment]
Hi David,
this is unfortunately not possible without touching the code. But to give you some hints were you would have to modify:
The centroids are created here: https://github.com/MIC-DKFZ/TractSeg/blob/72f2e73d261ccef68df608f8a5287a16311586b6/tractseg/libs/tractometry.py#L93

And `segment_idxs` contains the assignments of bundle segments to cluster segments: https://github.com/MIC-DKFZ/TractSeg/blob/72f2e73d261ccef68df608f8a5287a16311586b6/tractseg/libs/tractometry.py#L96

To save streamlines (e.g. the centroid streamlines) you can use code similar to this one:
```
from tractseg.libs import fiber_utils
fiber_utils.save_streamlines_as_trk_legacy("centroids.trk", centroids, affine,  scalar_img.shape)
```

**Comment by Davi05d** [comment]
Hi Jacob, 
I appreciate your helpful and fast response. I have saved centroids.trk and segment_idxs matrixes as you suggested, however, I wasn't able to save centroid.trk into same space as original image (it is shifted). I assume that the trick would be in right setting of affine and scalar_img.shape parameters. Would you be so kind and give me an advice in this matter?  

I also struggle with understanding to segment_idxs matrixes. How and also what information is stored inside?

**Comment by Davi05d** [comment]
So I somehow solved the alignment issue. I am just puzzled why MITK display raw_Diffusion data (used as TractSeg input) aligned with TOM and TOM_tracking but not aligned with centroides, however TrackVis show it just the opposite way (missaligned TractSeg outputs and aligned centroides). 

But I still haven't figgured out how are information stored in segment_idxs matrix. I would be greatful for any hint.

**Comment by wasserth** [comment]
Unfortunately MITK and TrackVis interpret the streamline files differently. This results if streamlines being displayed different (not aligned) in both Softwares. In TractSeg you can set the parameter `--tracking_format`. `trk_legacy` should work well with MITK. `trk` should work well with TrackVis.

`segments_idxs` contains for each segment of each streamlines (100 segments for each of the 2000 streamlines) the index of the centroid segment that it is assigned to (the closest centroid segment).

**Comment by Davi05d** [comment]
Great, it makes sense! 
Thank you very much
