### ISSUE TITLE
Some questions about 'train your own model'

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#103]
Hi, I have some questions when I training my own model.
1. Is the first FCNN and the second FCNN are trained separately?  If so, what do I need to adjust after training the first FCNN?
2. Are the networks trained separately along coronal, sagittal and axial directions? Or are they trained simultaneously in three directions to get the weights?

**Comment by wasserth** [comment]
1: The model which is available online does not use a second FCNN  but simply averages the results from the first FCNN. This is a lot faster and the performance decrease is only very minor.

2: One network is trained simultaneously on all three directions (randomly receiving slices from different directions). It learns to work with all of them at the same time.

**Comment by luqily** [comment]
> 1: The model which is available online does not use a second FCNN but simply averages the results from the first FCNN. This is a lot faster and the performance decrease is only very minor.
> 
> 2: One network is trained simultaneously on all three directions (randomly receiving slices from different directions). It learns to work with all of them at the same time.

Thank you very much for your reply!
