### ISSUE TITLE
Tractometry algorithm choice & visualizing segments on a tract

### ISSUE THREAD

**Issue by meconomou** [MIC-DKFZ/TractSeg#104]
Hi Jakob,

I have been using TractSeg for a while now - it's a great tool and thanks for the continuous efforts!

My first question is about the tractometry sampling algorithm choice. Right now the following options are available: `algorithm = "distance_map"  # equal_dist | distance_map | cutting_plane | afq`. 
I just wanted to confirm whether the `afq` algorithm refers to the approach implemented in AFQ (Yeatman et al. 2012), where a weighted average is used to summarize DTI-based metrics at each point along the tract. I'd like to see whether/how the tract profiles differ when using the two different approaches (distance_map vs afq) - since there is no command-line option for this, I guess I have to manually adjust the code in that script?
My second question is about visualizing the re-sampled points along the tract. I'm aware of the current 3D plotting functions to plot metrics (e.g. FA) or p-values generated by TractSeg along the tract , but I was wondering if there is a way to find out exactly where specific points (e.g. 25-35) are in a certain individual (and thus be able to link the location to anatomical features). Where is this information on the sampled points stored and do you have a suggestion on how to extract/plot it?

Many thanks!
Maria

**Comment by wasserth** [comment]
I am happy to hear that TractSeg is helpful for you.
`afq` is pretty much the same as from Yeatman et al. 2012. However, the original paper is implemented in matlab and I use a python version. So not sure if it is 100% identical but the python code is intended to do the same.
If you want to use a different `algorithm` you have to adapt it in the code. There is no command line argument.
Just clone the repo and edit the code. Then do `pip install -e my/path/to/tractseg_dir`. The `-e` option will always update the installation automatically whenever you edit the code.

Adapting the 3D plotting of streamlines is a bit more complicated unfortunately. The code for this is not so straight forward. The function you have to look at is here:
https://github.com/MIC-DKFZ/TractSeg/blob/master/tractseg/libs/plot_utils.py#L343

The variable `segment_idxs` saves the assignment of streamline segments to cluster segments.
`segment_idxs[streamline_id][streamline_point] = id_of_cluster_segment_this_point_is_assigned_to`.
You might want to adapt the loop where `colors_all` is filled. This set the color for each segment of each streamline. If you give the same color to all points which have the same segment_idx then you can see which points are group together in Tractometry.

**Comment by meconomou** [comment]
Thanks a lot for the input!
