### ISSUE TITLE
Prestaging pretrained_weights_peak_regression_partX_v1.npz

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#11]
Is there a way to prestage those `pretrained_weights_peak_regression_partX_v1.npz` files that gets loaded when I run with `--output_type endings_segmentation`? I am running TractSeg via singularity and singularity doesn't let me write to the container image (without going through some hoops) at runtime. It would make it easier if I could prestage those files just like other files that I am prestaging on Dockerfile.

```
RUN curl -SL -o /.tractseg/pretrained_weights_tract_segmentation_v2.npz https://zenodo.org/record/1410884/files/best_weights_ep274.npz?download=1 \
    && curl -SL -o /.tractseg/pretrained_weights_tract_segmentation_dropout_v2.npz https://zenodo.org/record/1414130/files/best_weights_ep407.npz?download=1 \
    && curl -SL -o /.tractseg/pretrained_weights_endings_segmentation_v3.npz https://zenodo.org/record/1409670/files/EndingsSeg_best_weights_ep234.npz?download=1 \
    && curl -SL -o /.tractseg/pretrained_weights_peak_regression_v2.npz https://zenodo.org/record/1419198/files/best_weights_ep125.npz?download=1 \
    && curl -SL -o /.tractseg/pretrained_weights_dm_regression_v1.npz https://zenodo.org/record/1409676/files/DmReg_best_weights_ep427.npz?download=1

```

I am hoping I could just add pretrained_weights_peak_regression files in the list above? Is that possible?

**Comment by wasserth** [comment]
You can do it the following way:
```
RUN mkdir -p ~/.tractseg \
    && curl -SL -o ~/.tractseg/pretrained_weights_tract_segmentation_v2.npz https://zenodo.org/record/1410884/files/best_weights_ep274.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_tract_segmentation_dropout_v2.npz https://zenodo.org/record/1414130/files/best_weights_ep407.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_endings_segmentation_v3.npz https://zenodo.org/record/1409670/files/EndingsSeg_best_weights_ep234.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_peak_regression_part1_v1.npz https://zenodo.org/record/1434206/files/best_weights_ep226.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_peak_regression_part2_v1.npz https://zenodo.org/record/1434208/files/best_weights_ep210.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_peak_regression_part3_v1.npz https://zenodo.org/record/1434210/files/best_weights_ep185.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_peak_regression_part4_v1.npz https://zenodo.org/record/1434212/files/best_weights_ep174.npz?download=1 \
    && curl -SL -o ~/.tractseg/pretrained_weights_dm_regression_v1.npz https://zenodo.org/record/1409676/files/DmReg_best_weights_ep427.npz?download=1 \
```
Does that solve the problem?

**Comment by soichih** [comment]
Thanks. That will work. How about `pretrained_weights_tract_segmentation_v1.npz`? Don't I need to download it also?

Byt the way, I think it will be nice if TractSeg itself provides a command to download all these models - without actually running anything - so that I can run that command inside Dockerfile to pre-stage these models.

**Comment by wasserth** [comment]
`pretrained_weights_tract_segmentation_v1.npz` was replaced by `pretrained_weights_tract_segmentation_v2.npz`.
Adding such a command is  a good idea.

**Comment by soichih** [comment]
OK! I will ignore _v1 for now (I am already pre-staging _v2)

**Comment by wasserth** [comment]
You can specify your own path for the weights now and I added a script for downloading all weights. See https://github.com/MIC-DKFZ/TractSeg#can-i-save-the-pretrained-weights-at-a-different-location

**Comment by soichih** [comment]
@wasserth 

> You can change this directory by adding weights_dir=/absolute/path_to_where/you_want_it to ~/.tractseg/config.txt

The issue with this approach is that, ~ will point to different locations when I build the container (as root) and when the container is executed by singularity (it could be any user). Is it possible to just let the path be overridden by command line argument?

**Comment by wasserth** [comment]
As there are already a lot of command line arguments I do not want to add a lot more. Otherwise it is getting more and more complicated for new users to understand it. 
Would it also work for you if you could set the path via a environment variable e.g. `TRACTSEG_CONFIG_PATH`?

**Comment by soichih** [comment]
Yes, that could work, but why not just let user set TRACTSEG_WEIGHTS_DIR via ENV?

For now, I've workaround this by doing this.

```Dockerfile
RUN HOME=/ download_all_pretrained_weights
```
.. which seems to work fine. but it's a bit hacky.

**Comment by wasserth** [comment]
Good idea. I updated the code. Now the user can also define where the weights are stored using the environment variable `TRACTSEG_WEIGHTS_DIR`.
