### ISSUE TITLE
A question about gpu when I train my own model.

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#111]
Hi, sorry to bother you. I have a problem when I train my own model.
Recent days when I use `ExpRunner --config=My_custom_experiment --lw` to load weights to initialize my model,  the program reports the error.
![image](https://user-images.githubusercontent.com/43931240/84596836-8949e100-ae92-11ea-876e-8043ccc77f88.png)
But when I use `ExpRunner --config=My_custom_experiment` and don't load weight to initialize my model, the program doesn't report the error.

The gpu is TITAN Xp. The batch size is 47. And when I decrease batch size I can solve this problem.

But since I didn't have a problem when I used `ExpRunner --config=My_custom_experiment --lw` the other day. I am very puzzled and didn't find the cause of the sudden problem. Can you give me some advice? Looking forward to your reply.

**Comment by wasserth** [comment]
If `ExpRunner --config=My_custom_experiment --lw` worked for you the other day and now does not work anymore, I would check if your environment changed: Did you update any python packages like pytorch? Did you change to a different python version? You can also lower your batch size a bit. Something like 45 should still be fine.

**Comment by luqily** [comment]
> If `ExpRunner --config=My_custom_experiment --lw` worked for you the other day and now does not work anymore, I would check if your environment changed: Did you update any python packages like pytorch? Did you change to a different python version? You can also lower your batch size a bit. Something like 45 should still be fine.

Thanks for your reply!
I have checked my environment and it didn't be changed. I guess I accidentally changed the code, but I didn't find out where it was changed.  
So I want to sort out the codes carefully. If I want to copy different versions of TractSeg for different methods, may I use `pip install -e Tractseg_vxxx` to install each version then rename the `ExpRunner` to `ExpRunner_vxxx`, use the `ExpRunner_vxxx --config=My_custom_experiment` to perform different methods?

**Comment by luqily** [comment]
> If `ExpRunner --config=My_custom_experiment --lw` worked for you the other day and now does not work anymore, I would check if your environment changed: Did you update any python packages like pytorch? Did you change to a different python version? You can also lower your batch size a bit. Something like 45 should still be fine.

Thanks for your reply!
