### ISSUE TITLE
Training the TOM network on new data

### ISSUE THREAD

**Issue by aritche** [MIC-DKFZ/TractSeg#112]
Hi,

I am trying to generate TOMs from the .trk files provided on Zenodo ([link](https://zenodo.org/record/1477956)). Having a look at the "Train your own model" instructions in the repo's readme file,  it doesn't appear to  generate TOMs anywhere throughout the steps.

Is there a file similar to TractSeg/resources/utility_scripts/trk_2_binary.py but for generating TOMs? (e.g. trk_2_TOM.py)

**Comment by wasserth** [comment]
This is a bit more tricky unfortunately. But the following two issues can tell you how it works in general:
https://github.com/MIC-DKFZ/TractSeg/issues/82
https://github.com/MIC-DKFZ/TractSeg/issues/92

I will add the links to those issues to the "Train your own model" sections.

**Comment by aritche** [comment]
Thank you very much.

When I generate TOMs via the MitkFiberDirectionExtraction script, they are not as '_smooth_' as the TOMs generated by the pre-trained TractSeg network. Is this to be expected? or am I using inappropriate parameters?

The command I am using is: ` sh MitkFiberDirectionExtraction.sh -i ./CST_left.trk -o ./result_TOM --mask ./CST_left_mask.nii.gz --athresh 10 --peakthresh 0.1 --numdirs 1 --normalization 3 --file_ending .nii.gz`

**Result from the script (CST_left):**

![v1](https://user-images.githubusercontent.com/11988281/85491957-c000c380-b617-11ea-8b2a-6c7294119388.png)



**Result from the pre-trained TractSeg network (CST_left):**

![v2](https://user-images.githubusercontent.com/11988281/85491969-c55e0e00-b617-11ea-8e6b-d64948e18c50.png)

**Comment by wasserth** [comment]
That is expected. The TractSeg TOMs are smoother and better than the peak maps from MitkFiberDirectionExtraction.sh
