### ISSUE TITLE
Aligning image to MNI space and flip peaks axis

### ISSUE THREAD

**Issue by OeslleLucena** [MIC-DKFZ/TractSeg#113]
### I am trying to segment tracts for non HCP data. I conducted the following experiments:

**1) Rigidly registration from non HCP data to HCP data.** 

` TractSeg -i dMRI_data.nii.gz --bvals dMRI_data.bval --bvecs dMRI_data.bvec --brain_mask mask.nii.gz --raw_diffusion_input --preprocess --keep_intermediate_files --csd_type csd_msmt -o multi_shell
`

_The outputs do not seem proper tracts at all._

**2) Rigidly registration from non HCP data to HCP data,  flipping peals_MNI_space.nii.gz x-axis, and run TractSeg pipeline on flipped peaks.**

`TractSeg -i dMRI_data.nii.gz --bvals dMRI_data.bval --bvecs dMRI_data.bvec --brain_mask mask.nii.gz --raw_diffusion_input --preprocess --keep_intermediate_files --csd_type csd_msmt -o multi_shell`

Then, 

`TractSeg -i multi_shell/peaks_flip_x.nii.gz -o multi_shell_MNI_peaks_flip_x`

_The outputs seem good. I realized that HCP is LAS stored while my data is RAS stored, which means a flip at the x-axis for peals_MNI_space.nii.gz so I thought about converting my data to LAS and running TractSeg pipeline on raw data which leads to next experiment._

**3) Convert non HCP data to LAS stored using MRtrix and run TractSeg pipeline on raw data.**

`mrconvert   dMRI_data.nii.gz -fslgrad dMRI_data.bvec dMRI_data.bval -stride  -1, 2, 3, 4  output_image -export_grad_fsl dMRI_data_LAS.bvec dMRI_data_LAS.bval`

`TractSeg -i dMRI_data_LAS.nii.gz --bvals dMRI_data_LAS.bval --bvecs dMRI_data_LAS.bvec --brain_mask maskfigg.nii.gz --raw_diffusion_input --preprocess --keep_intermediate_files --csd_type csd_msmt -o multi_shell_LAS`

_The outputs do not seem proper tracts at all as in experiment 1. I checked my data using `mrinfo` and it is LAS stored_

Could you please let me know if there is anything wrong with the TractSeg call in Experiment 3?

**Comment by wasserth** [comment]
I seems that in experiment 3 the peaks are still not flipped correctly even though you did the conversion from RAS to LAS space. There might be some others issues with your data which makes it differently oriented than the HCP data. I would recommend doing it the way like in experiment 2: flip the peaks manually. That's also how I do it for datasets where the orientation is not correct.

**Comment by OeslleLucena** [comment]
Thank you!
I managed to correctly convert from RAS to LAS space and I ran again experiment 3 successfully.
