### ISSUE TITLE
Wrong number of samples in tractometry outputs

### ISSUE THREAD

**Issue by vukovicnikola** [MIC-DKFZ/TractSeg#114]
When I run this:

`Tractometry -i tractseg_output/TOM_trackings/ -o tractseg_output/tractometry_output/tractometry_fa.csv --tracking_format tck -e tractseg_output/endings_segmentations/ -s tractseg_output/FA_MNI.nii.gz --nr_points 100`

I get a csv file with 98 points. If I specify 50 for --nr_points, I get 48. Is the new version clipping the output for some reason? Or bug?

**Comment by wasserth** [comment]
The first and last point will always get clipped because those tend to be quite noisy. If you want exactly 100 points I would recommend to just duplicate the first and last point of the 98 points.

**Comment by vukovicnikola** [comment]
Thank you for the clarification! I'll just specify that I want 102 points so as to get 100 unique values. This might be something to note in the manual.
