### ISSUE TITLE
Fiber in isolation looks good, but not correct in anatomical space.

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#115]
Hi Tractseg Team,

I am trying to create Tractseg segmentation starting with a preprocessed diffusion image. I run the following steps to produce all of the tractseg outputs, and it runs without error:
`TractSeg -i dwi.nii.gz -o tractseg_output --raw_diffusion_input --output_type tract_segmentation`
`TractSeg -i tractseg_output/peaks.nii.gz -o tractseg_output --output_type endings_segmentation`
`TractSeg -i tractseg_output/peaks.nii.gz -o tractseg_output --output_type TOM`
`Tracking -i tractseg_output/peaks.nii.gz -o tractseg_output --nr_fibers 5000`

However, when I open the results in TrackVis, I see something like this, where the tracked fiber looks fine in isolation, but not correctly placed. The background image is the b0 image from the same diffusion file input to TractSeg. This below images are from the Left AF.

![image](https://user-images.githubusercontent.com/27028726/86259471-0ca14d00-bb8a-11ea-8610-005a15d42d58.png)
![image](https://user-images.githubusercontent.com/27028726/86259513-188d0f00-bb8a-11ea-837d-87c396c3cbf5.png)

Is this normal, or do you know what I may do to address this? Please let me know if you would need any more information.

Thanks,
Steven

**Comment by wasserth** [comment]
You could try to use the option `tracking_format trk` when calling the `Tracking` command. The default is `trk_legacy` which works fine with MITK Diffusion. But TrackVis is using a sightly different trk version, so you have to use `trk`. Does this work?

**Comment by smeisler** [comment]
![image](https://user-images.githubusercontent.com/27028726/86367473-fd81d400-bc49-11ea-9ece-76d3d1167c10.png)
Much better, thank you!
