### ISSUE TITLE
Index out of bound during Tractometry

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#117]
I am getting an error when running tractometry that reads:
` UserWarning: The `dipy.stats` module is still under heavy development and functionality, as well as the API is likely to change in future versions of the software`
  `warnings.warn(w_string)`
  `0%|                                                    | 0/50 [00:00<?, ?it/s]`
`Traceback (most recent call last):`
 ` File "/usr/local/bin/Tractometry", line 138, in <module>
    main()`
 ` File "/usr/local/bin/Tractometry", line 109, in main`
  `  predicted_peaks=predicted_peaks, affine=scalar_image.affine)`
  `File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/tractometry.py", line 64, in evaluate_along_streamlines`
    `streamlines = _orient_to_same_start_region(streamlines, beginnings)`
  `File "/usr/local/lib/python3.5/dist-packages/tractseg/libs/tractometry.py", line 42, in _orient_to_same_start_region`
    `if beginnings[int(startpoint[0]), int(startpoint[1]), int(startpoint[2])] == 0:`
`IndexError: index 178 is out of bounds for axis 1 with size 174
`

**Steps taken to replicate on TractSeg 2.1.1:**
0) Preprocessed dwi (Diffusion.nii.gz, single shell acquisition, has undergone denoising, eddy, and N4 bias correction), along with the b0 mask (nodif_brain_mask.nii.gz) and FA map (FA.nii.gz) are copied to the working directory.

1) Create peaks from preprocessed data (not rigidly aligned to MNI, but in the same orientation)
`TractSeg -i Diffusion.nii.gz -o tractseg_output --raw_diffusion_input --brain_mask nodif_brain_mask.nii.gz  --output_type tract_segmentation`

2) Remove the recently created bundle segmentations because I have to flip the peaks over X axis (discovered this primarily through trial-and-error). **Is there a wrapper function in TractSeg just to produce the MrTrix peaks so I can avoid creating the bundles twice?**
`rm -r tractseg_output/bundle_segmentations`

3) Flip peaks and recreate bundle segmentations
`flip_peaks -i tractseg_output/peaks.nii.gz -o tractseg_output/peaks_flip_x.nii.gz -a x`
`TractSeg -i tractseg_output/peaks_flip_x.nii.gz -o tractseg_output --output_type tract_segmentation`
The peaks and bundle segmentations look correct after this step (can provide images if needed)

4) Create Ending Segmentation, TOM, and TOM trackings
`TractSeg -i tractseg_output/peaks_flip_x.nii.gz -o tractseg_output --output_type endings_segmentation`
`TractSeg -i tractseg_output/peaks_flip_x.nii.gz -o tractseg_output --output_type TOM`
`Tracking -i tractseg_output/peaks_flip_x.nii.gz -o tractseg_output --tracking_format trk` **(should I specify --nr_fibers here?)**

There are no errors up until this point, and the .trk fibers look great!

5) Attempt tractometry
`Tractometry -i TOM_trackings/ -o FA.csv -e endings_segmentations/ -s FA.nii.gz`

This is where the error occurs. If it's of any help, I am using the [Brainlife singularity container ](https://hub.docker.com/r/brainlife/tractseg). Please let me know if anymore information would be helpful.

Thanks,
Steven

**Comment by wasserth** [comment]
Could you post the affine matrix of the following files:  
  
tractseg_output/peaks_flip_x.nii.gz  
tractseg_output/bundle_segmentations/CST_right.nii.gz  
tractseg_output/endings_segmentation/CST_right_b.nii.gz  
tractseg_output/TOM/CST_right.nii.gz  
FA.nii.gz

**Comment by smeisler** [comment]
Sorry I am a bit confused by this request, since I did not do any transformation. Are you asking me to align these images (using FLIRT for example) to the MNI FA map provided with TractSeg and then to post the output matrix (-omat)?

**Comment by wasserth** [comment]
Sorry for the confusion. Since you did not do any transformations the affine matrix should always look the same. But to make sure that this is actually the case it would be important to have a look at them. I am talking about the affine matrix which is in the image header of any nifti image (not the affine matrix of a transformation with FLIRT). In any nifti viewer it should be possible to have a look at this matrix. (the matrix should contain the offset in the last column and the spacing on the diagonal)

**Comment by smeisler** [comment]
The following outputs from the fslhd command show the sform and qform affine matrices.
# FA.nii.gz
![image](https://user-images.githubusercontent.com/27028726/86935273-a462e600-c10a-11ea-9434-b5642d2b13da.png)
# peaks_flip_x.nii.gz
![image](https://user-images.githubusercontent.com/27028726/86935491-e55afa80-c10a-11ea-8405-c06b618fc08f.png)
# bundle_segmentations/CST_right.nii.gz
![image](https://user-images.githubusercontent.com/27028726/86936970-af1e7a80-c10c-11ea-94b4-96ce99f53afc.png)
# endings_segmentations/CST_right_b.nii.gz
![image](https://user-images.githubusercontent.com/27028726/86937111-db39fb80-c10c-11ea-882c-d445c69a6d79.png)
# TOM/CST_right.nii.gz
![image](https://user-images.githubusercontent.com/27028726/86937219-fb69ba80-c10c-11ea-8747-da9a13f7518f.png)

**Comment by smeisler** [comment]
Looking through the documentation of Tractometry, I did not know that there was a --tracking_format argument for that as well. I changed it to trk to match the format of Tracking, and now it seems to work.
