### ISSUE TITLE
--plot3D not a valid argument for plot_tractometry_results

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#118]
Hello,

When I run as instructed in the documentation, I get an error `unrecognized arguments: --plot3D metric
`.  This is especially confusing because I looked at the code for plot_tractometry_results, and I can see the code for --plot3D towards the bottom where arguments are parsed. The rest of the function (e.g. making the group comparison plots) seems to be working fine. Do you know what the problem might be? This is running on TractSeg 2.1.1, checked out earlier today.

Thanks,
Steven

**Comment by wasserth** [comment]
Does it work if you use the master branch?
```
pip install --upgrade https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
```

**Comment by smeisler** [comment]
Now it begins running, but I get the following error when I try to run. I am just testing on 4 subjects (2 per group) and four tracts, and trying to make a 3d plot for the first subject. The corresponding nodif_brain_mask is in the directory outside of the tractseg outputs.

`Correcting for comparison of multiple tracts: False`
`Using 4 manually specified bundles.`
`Doing group analysis.`
`Number of subjects:`
  `group 0: 2`
  `group 1: 2`
`  0%|                                                                                                    | 0/4 [00:00<?, ?it/s]`
`Traceback (most recent call last):`
 ` File "/om2/user/smeisler/anaconda3/bin/plot_tractometry_results", line 379, in <module>
    main()`
  `File "/om2/user/smeisler/anaconda3/bin/plot_tractometry_results", line 375, in main
    show_color_bar=show_color_bar, save_csv=args.save_csv, y_range=args.range)`
  `File "/om2/user/smeisler/anaconda3/bin/plot_tractometry_results", line 274, in plot_tractometry_with_pvalue
    output_path_3D, tracking_format, show_color_bar)`
 ` File "/om2/user/smeisler/anaconda3/lib/python3.7/site-packages/tractseg/libs/plot_utils.py", line 401, in plot_bundles_with_metric`
   ` if beginnings[int(startpoint[0]), int(startpoint[1]), int(startpoint[2])] == 0:`
`IndexError: index 147 is out of bounds for axis 2 with size 141`
 ` 0%|                                                                                                    | 0/4 [00:23<?, ?it/s]`

**Comment by smeisler** [comment]
Sorry to reopen so soon, but the 3d images appear to be empty (below is the left AF, which I know is not empty for this particular subject) The codes does run without error though, and the 2D group comparison plots are still looking fine. ![image](https://user-images.githubusercontent.com/27028726/87448979-8eea3200-c5ca-11ea-9da7-40f54bb8431a.png)

The code I used to run looks like the following (I used trk trackings):
`plot_tractometry_results --plot3D metric -i /PATH/TO/subjects.txt -o test.png --tracking_format trk`

My output folder is called TractSeg as opposed to tractseg_output), and in these folders I have tractometry csv files for fa, md, rd, and ad. The header to my subjects txt file looks like the following:
`# tractometry_path=/PATH/TO/SUBJECT/FOLDERS/SUBJECT_ID/TractSeg/fa.csv`
`# bundles=AF_left UF_left CST_left IFO_left`
`# plot_3D=/PATH/TO/FIRST/SUBJECT/TractSeg/`

**Comment by wasserth** [comment]
Is your subject in MNI space? The camera of the 3D rendering is adjusted to have the right view angle for MNI space. So if your subject is not in MNI space it might face the wrong direction.
For the 3D rendering it is a bit painful to get the orientation right for very format. I always work with `trk_legacy`. Does it work for you if you use `trk_legacy`? Then the format would be the issue.

**Comment by smeisler** [comment]
![image](https://user-images.githubusercontent.com/27028726/87627500-e092d980-c6fc-11ea-83e5-01040547d257.png)
That worked, thanks! I'll see if it works with trk_legacy while in subject space. To this end, my workflow has been:
1) Get FA_2_MNI transform matrix
2) Register all diffusion files and scalar maps to MNI (starting from raw diffusion)
3) Generate CSD peaks on MNI diffusion file with MrTrix and flip them across X-axis
3) Run TractSeg (bundle, endings, TOM) on MNI
4) Register all of these outputs back to subject space, including peaks (which I do not binarize like the bundles and endings)
5) Run Tracking individually on both MNI and subject space

Before running Tracking in subject space, should I generate peaks in subject space with MrTrix or simply register them from MNI (or does it make a difference)? Alternatively, is there a way to cut out the intermediary steps and just register the .trk files themself to subject space?

Also, ignore the comment I made earlier about matplotlib; my conda environment was just disorganized beyond repair, so after a new install and very deliberate package installing, everything is working better. I do get a warning when it enters the rendering stage that may be worth addressing.

`path/to/conda/environment/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
`

**Comment by smeisler** [comment]
Also, I compared the Left AF picture with the Right AF picture, and it looks like that 1) the same orientation is used to render both pictures, and that 2) left and right may be switched, based on how close the right and left fibers appear when looking at the left side of the brain as in the pictures.

# AF Right
![image](https://user-images.githubusercontent.com/27028726/87684469-49577180-c750-11ea-89f2-8257a43dd57a.png)
# AF Left
![Uploading image.png…]()

**Comment by wasserth** [comment]
Thanks for the colorbar hint. There was a bug. If you pull the newest master the colorbar should work now.

TractSeg only works properly if your images are roughly aligned with MNI space. Using `trk_legacy` does not change that.
After you ran all Tracking you can transform your results back to subject space if you want to. However TractSeg does not provide any commands for that. Transforming the trk files should be possible but I do not know which is the best tool to do this (flirt does not work with streamline files).
plot_tractometry_results only works properly in MNI space.

AF_left and right should be fine I guess. In `tractseg/libs/plot_utils.py` you can uncomment line 499 then you should get an interactive 3D view where you can rotate the brain.

**Comment by smeisler** [comment]
Color bar works now. However, I am still suspicious that somehow left and right are getting switched. Below are the Left CST as rendered by plot_tractometry_results (MNI) and by TrackVis (warped back to subject space), both _presumably_ from an anterior perspective.

# plot_tractometry_results
![image](https://user-images.githubusercontent.com/27028726/87857316-dedf3680-c8f3-11ea-98eb-9bc36974da78.png)

# TrackVis
![image](https://user-images.githubusercontent.com/27028726/87857350-14841f80-c8f4-11ea-9f89-ae9be7446dc2.png)

**Comment by wasserth** [comment]
I will do a more in depth investigation into the left/right issue. Might take a little while.

**Comment by wasserth** [comment]
I updated the code. Now the left/right issue in the 3D plot should be fixed. (When showing a bundle, the correct bundle was shown, but in 3D it was plotted flipped to the other side. Now the flipping should be correct).

**Comment by smeisler** [comment]
Thanks!
