### ISSUE TITLE
tck files not aligned to subject space (All other files are aligned)

### ISSUE THREAD

**Issue by thiagoparanhos** [MIC-DKFZ/TractSeg#120]
Hi. I ran the following 4 steps without the --preprocess option: 
TractSeg -i peaks.nii.gz --output_type tract_segmentation
TractSeg -i peaks.nii.gz --output_type endings_segmentation
TractSeg -i peaks.nii.gz --output_type TOM 
Tracking -i peaks.nii.gz

The .nii files generated in the folders bundle_segmentation, endings segmentation and TOM are aligned to the subject dwi. However, .trk or .tck files are not aligned to the subject space.

<img width="237" alt="Screen Shot 2020-08-25 at 18 46 11" src="https://user-images.githubusercontent.com/70239114/91231227-45c9e980-e703-11ea-9a1d-9c3873ca2f7e.png">

Can someone tell me why did that happened?

**Comment by wasserth** [comment]
What program are you using to visualize the streamline files? If you choose the format `trk_legacy` (default) then visualization should work correctly in MITK Diffusion. If you choose `trk` then visualization should work correctly in TrackVis. If you choose `tck` then visualization should work correctly in Mrtrix mrview.

**Comment by thiagoparanhos** [comment]
I was using Mrtrix to visualize .tck files. The problem was solved by registering the dwi to the MNI space.Now I am struggling with 2 main issues in tractometry: (1) I was only able to perform tractometry with .trk files. Whenever I try to use .tck files, the command does not run properly; (2) Whenever I run tractometry with trk files, the results plotted in the spreadsheet do not seem to make sense, or at least I'm not able to understand the units.

<img width="133" alt="Screen Shot 2020-08-28 at 15 46 38" src="https://user-images.githubusercontent.com/70239114/91604983-12c36800-e946-11ea-8b8e-f73cf9da108b.png">

 I only performed tractometry with 3 pair of tracks.

**Comment by soichih** [comment]
I am also noticing the tck / dwi alignment issue with the latest master branch tractseg code.

https://user-images.githubusercontent.com/923896/133103227-7c7588f3-6d23-4b1c-be91-eab5ba95212d.mp4

I am just viewing the tck output with the input dwi image that I passed to tractseg using mrview. It looks like the tck file is shifted slightly to the left side?

I am also seeing this mis-alignment with brainlife/wmc visualizer (tractview).

https://user-images.githubusercontent.com/923896/133103881-750e19b2-a253-4d19-a588-dc9e9ca9eb4a.mp4

Here is the affine of our dwi image.

```
[[  -3.08333349    0.            0.           86.33333778]
 [   0.            3.08333325    0.         -110.99999714]
 [   0.            0.            3.10000014 -127.10000587]
 [   0.            0.            0.            1.        ]]
```

I believe this is an issue introduced in the latest master branch and maybe related to the fix made for https://github.com/MIC-DKFZ/TractSeg/issues/147

**Comment by m-petersen** [comment]
Hi,

just want to report that I am facing the same issue of the .tck-bundles derived via TOM tracking being misaligned to the subject using the latest tractseg container from dockerhub (https://hub.docker.com/layers/wasserth/tractseg_container/master/images/sha256-702dabaca03b7765c58d0567b0260b9ab376f63b8e33197639c8458e88b49c32?context=explore).

**Comment by lbinding** [comment]
Just wanted to report this is still the case for .tck TOM bundles. I've found that running locally (2.3) leads to much worse estimations compared to docker – is there a difference between versions?

**Comment by pinghongyeh** [comment]
Hi, 
I have the same issue. All TractSeg outputs are aligned except tck files. Any suggestions for having this fixed? 

Ping

**Comment by wasserth** [comment]
Would it be possible to share the data so I can try to reproduce the issue?

**Comment by pinghongyeh** [comment]
NCNC3164_averageblipup_289_WM_FODs.mif.gz
<https://drive.google.com/file/d/1a9a4AktsZMyHsdwO-8JOEBfFECJOJDaK/view?usp=drive_web>
Hi Jakob,

Thank you for the prompt response.
See attached.
HEre is the commands I ran,
sh2peaks ${dwipath}/${averageresponse}_WM_FODs.mif
 ${dwipath}/peaks_${averageresponse}_WM_FODs.nii.gz
TractSeg -i ${dwipath}/peaks_${averageresponse}_WM_FODs.nii.gz -o
${dwipath}/${averageresponse}_tractseg_output --output_type
tract_segmentation
TractSeg -i ${dwipath}/peaks_${averageresponse}_WM_FODs.nii.gz -o
${dwipath}/${averageresponse}_tractseg_output --output_type
endings_segmentation
TractSeg -i ${dwipath}/peaks_${averageresponse}_WM_FODs.nii.gz -o
${dwipath}/${averageresponse}_tractseg_output --output_type TOM
Tracking -i ${dwipath}/peaks_${averageresponse}_WM_FODs.nii.gz -o
${dwipath}/${averageresponse}_tractseg_output --nr_fibers 100000
--tracking_format tck

Thanks.

Ping

**Comment by pinghongyeh** [comment]
The file is too large and exceeds the size limit.
Do you have links where I can upload the file?

Thanks.
p

**Comment by pinghongyeh** [comment]
/* Init
        ----------- */
        * {
            margin: 0;
            padding: 0;
            font-family: 'Inter', Tahoma, sans-serif;
            font-size: 100%;
        }

        /* Resets
        ----------- */
        body {
            width: 100% !important;
            height: 100% !important;
            -webkit-font-smoothing:antialiased;
            -webkit-text-size-adjust:none;
            margin: 0;
            padding: 0;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
            background-color: #f6f9fc;
        }

        /* Fonts
        ----------- */
        @font-face {
            font-family: 'Inter';
            font-style: normal;
            font-weight: 400;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/inter/v3/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }
        @font-face {
            font-family: 'Inter';
            font-style: normal;
            font-weight: 700;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/inter/v3/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }

        /* Remove spacing around Outlook 07, 10 tables
        ----------- */
        table {
            border-collapse: collapse !important;
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }
        img {
            -ms-interpolation-mode: bicubic;
        }
        a {
            text-decoration: none;
            border: 0;
            outline: none;
        }
        a img {
            border: none;
        }

        /* Essentially, this acts as the body of the email. I chose to call it "page."
        ----------- */
        .page, #transfernowBackgroundTable {
            width: 100% !important;
            margin: 0;
            padding: 0;
            line-height: 100% !important;
        }

        #transfernowBackgroundTable {
            margin: 0;
            padding: 0;
            width: 100% !important;
            line-height: 100% !important;
        }

        /* Links
        ----------- */
        img {
            display: block;
            outline: none;
            text-decoration: none;
            -ms-interpolation-mode: bicubic;
        }
        .button {
            display: inline-block;
            font-family: 'Inter', Tahoma, sans-serif;
            background-color: #3f51b5;
            text-decoration: none;
            border-radius: 6px;
            -webkit-border-radius: 6px;
            -moz-border-radius: 6px;
            color: #ffffff;
            font-size: 16px;
            font-weight: 700;
            line-height: 50px;
            width: 260px;
            min-height: 50px;
            -webkit-text-size-adjust: none;
            mso-hide: all;
        }
        .button span {
            display: inline-block;
            font-family: 'Inter', Tahoma, sans-serif;
            background-color: #3f51b5;
            text-decoration: none;
            border-radius: 6px;
            -webkit-border-radius: 6px;
            -moz-border-radius: 6px;
            color: #ffffff;
            font-size: 16px;
            font-weight: 700;
            min-height: 50px;
            width: 260px;
            line-height: 50px;
            -webkit-text-size-adjust: none;
        }

        table[class="container-table-margin"] {
            margin-top: 50px;
            margin-bottom: 50px;
        }

        .border-radius {
            border-radius: 4px 4px 0 0 !important;
            -moz-border-radius: 4px 4px 0 0 !important;
            -webkit-border-radius: 4px 4px 0 0 !important;
        }

        /* Responsive
        ----------- */
        @media screen and (max-width:670px) {
            table[class="container-table"] {
                width: 100% !important;
            }
            table[class="container-table-margin"] {
                width: 100% !important;
                margin-top: 0 !important;
                margin-bottom: 15px !important;
            }
            .border-radius {
                border-radius: 0 !important;
                -moz-border-radius: 0 !important;
                -webkit-border-radius: 0 !important;
            }
            .button,
            .button span {
                width: 100% !important;
            }
            .title {
                font-size: 20px !important;
                line-height: 30px !important;
            }
        }

        /* MS viewport
        ----------- */
        @-ms-viewport {
            width: device-width;
        }

        /* Fix Orange
        -----------*/
        .email a,
        .email a span,
        .email a span span {
            color: #3f51b5 !important;
            text-decoration: none !important;
            font-weight: 700 !important;
        }
        .noreply a,
        .noreply a span,
        .noreply a span span {
            color: #000000 !important;
            text-decoration: none !important;
            border-bottom: 1px dotted #000000 !important;
        }
        * td .button,
        * td .button span {
            line-height: 50px !important;
        }
        .btn-orange,
        .btn-orange span {
            width: 260px !important;
        }
    




    
        
            
                    
                        
                            

                                
                                    
                                        
                                            

                                            
                                                
                                                    
                                                        
                                                            
                                                        
                                                    
                                                
                                            
                                            

    
        
            
                
            
        
        
            
                
                    
                        
                            
                                Ping-Hong Yeh 
                            
                        
                    
                    
                        
                            sent you files (Re: [MIC-DKFZ/TractSeg] tck files not aligned to subject space (All other files are aligned) ()
                        
                    
                    
    
        2 files, 283 MB total ● Files available until : 01/26/2022 at 6:21 PM (GMT)
    

                
            
        
    

    
    
        
    Two files. Please reply once you receive them.
Thank you for your time
ping

    
    

    

    
    
        
            
                

                
                    Download
                
            
        
    
    
        
            Download link
        
    
    
        
            
                https://www.transfernow.net/dl/20220119LDxftOv9/3wjPJ3rB
            
        
    



    
    
        
            2 files (283 MB)
        
    
    
        
            
                
                
                
                
                    
                        1 NCNC3164_FWdti_FA.nii.gz
                    
                
                
                
                
                
                
                
                    
                        2 NCNC3164_averageblipup_289_WM_FODs.mif.gz
                    
                
                
                
                
            

        
    



                                        
                                    
                                    
                                        

                                            
                                                
                                                    
                                                        To be sure to receive our emails, please add the address ***@***.*** to your contacts.
                                                    
                                                
                                            

                                            
                                            
                                                
                                                    
                                                        About TransferNow -
                                                        Get help -
                                                        Service status -
                                                        Terms of use
                                                    
                                                
                                            

                                            
                                                
                                                    
                                                        Want to change how you receive these emails?
                                                        Unsubscribe

**Comment by wasserth** [comment]
Thanks for sending the data. That really helped in identifying the problem. I just pushed a bugfix. So if you update your TractSeg installation to the lastest master branch it should work now.
```
pip install --upgrade https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
```

**Comment by pinghongyeh** [comment]
Awesome!
Thank you so much for your prompt response.
p
