### ISSUE TITLE
(only) .trk files flipped in tractvis, but solved by outputting to .tck and then converting to .trk with nipype

### ISSUE THREAD

**Issue by nblauch** [MIC-DKFZ/TractSeg#121]
hi, thanks for the awesome software.

just wanted to note a small issue i am having with the .trk outputs, related to some others but persistent in the current stable release. 

i started with files in isotropic, MNI-oriented native space and ran the pipeline without `--preprocessing`. The ROIs come out in the correct orientation, perfectly aligned with my structural data. Since I use TrackVis I originally used the `--tracking_format trk`. However this causes the tracks to be flipped about both the x and y axes. I the tried using `--tracking_format tck` and then used the `nipype` [function](https://nipype.readthedocs.io/en/0.12.0/interfaces/generated/nipype.interfaces.mrtrix.convert.html).`MRTrix2TrackVis` to convert to .trk, using my b0 image file as a reference. This works perfectly. 

Maybe this will help the software development or others who run into this issue.

**Comment by wasserth** [comment]
Thanks for pointing this out. Getting the orientations for the `trk` files right is a bit of a pain, especially since there are different versions of the `trk` file specification.

**Comment by luqily** [comment]
> hi, thanks for the awesome software.
> 
> just wanted to note a small issue i am having with the .trk outputs, related to some others but persistent in the current stable release.
> 
> i started with files in isotropic, MNI-oriented native space and ran the pipeline without `--preprocessing`. The ROIs come out in the correct orientation, perfectly aligned with my structural data. Since I use TrackVis I originally used the `--tracking_format trk`. However this causes the tracks to be flipped about both the x and y axes. I the tried using `--tracking_format tck` and then used the `nipype` [function](https://nipype.readthedocs.io/en/0.12.0/interfaces/generated/nipype.interfaces.mrtrix.convert.html).`MRTrix2TrackVis` to convert to .trk, using my b0 image file as a reference. This works perfectly.
> 
> Maybe this will help the software development or others who run into this issue.

hi, thanks for your help. I also met this problem, and I tried to solve it with the method you mentioned. But it says `ImportError: cannot import name 'move_streamlines' from 'dipy.tracking.utils' ` I think it may be because of the version of my DIPY.
So what is the version of your DIPY?

**Comment by wasserth** [comment]
You have to update to the newest version of TractSeg (`pip install --upgrade TractSeg`) and to dipy > v1.0. Then this error should be gone.

**Comment by luqily** [comment]
> You have to update to the newest version of TractSeg (`pip install --upgrade TractSeg`) and to dipy > v1.0. Then this error should be gone.

Thanks for your reply!
