### ISSUE TITLE
beginnings.get_data(), NR_POINTS, dilate=DILATION, 16%|███████████▊

### ISSUE THREAD

**Issue by Renatar18** [MIC-DKFZ/TractSeg#123]
Hello!

The command stops at 16%: Tractometry -i ${i}/tractseg_output/TOM_trackings/ -o results/FA/${i}_FA.csv -e ${i}/tractseg_output/endings_segmentations/ -s ${i}/FA.nii.gz --tracking_format tck

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
  beginnings.get_data(), NR_POINTS, dilate=DILATION,
 16%|███████████▊          

What is wrong? 

Thank you!

**Comment by wasserth** [comment]
Which version of nibabel are you using? Using an older version might be a quick workaround.

**Comment by Renatar18** [comment]
Hi Jakob,
Thank you very much for your reply!
I adressed your question to our IT engineer, and he replied:

'Now I've installed older nibabel version (2.5.2) in the conda environment
for tractseg on your server.  But just as a warning, dipy 1.1.1 requires
nibabel>=3.0.0.  So I'll really need an exact version to not have
compatibility issues'.

What do you say? Which version should we install?

Thank you,
Renata.

**Comment by wasserth** [comment]
Which nibabel version did you use when the error occured?

**Comment by Renatar18** [comment]
We had version 3.0.1 on it before. When downgraded it to 2.5.2 it told:
"dipy 1.1.1 has requirement nibabel>=3.0.0"

**Comment by wasserth** [comment]
I just tested TractSeg with nibabel 3.1.1 and it worked fine for me.
I guess there is another error. What is the complete error message when it stops?

**Comment by Renatar18** [comment]
The complete error message is:
Sometimes it stops on 16% like this:

    deprecated from version: 3.0
    Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
    beginnings.get_data(), NR_POINTS, dilate=DILATION,
    16%|███████████▊

Sometimes the error message is:
Traceback (most recent call last):
  File "/usr/local/tractseg/bin/Tractometry", line 138, in <module>
    main()
  File "/usr/local/tractseg/bin/Tractometry", line 71, in main
    scalar_image = nib.load(args.scalar_img)
  File "/usr/local/tractseg/lib/python3.8/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '20130314.5143/FA.nii.gz'

**Comment by Renatar18** [comment]
This is the complete message when it stops. For some reason it works well
for some subjects and doesn't work for the others from the same sample.
What could be the problem?

* deprecated from version: 3.0
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of
version: 5.0
  beginnings.get_data(), NR_POINTS, dilate=DILATION,
 16%|███████████▊
   | 8/50 [00:14<01:15,  1.79s/it]Traceback (most recent call last):
  File "/usr/local/tractseg/bin/Tractometry", line 138, in <module>
    main()
  File "/usr/local/tractseg/bin/Tractometry", line 107, in main
    mean, std =
tractometry.evaluate_along_streamlines(np.nan_to_num(scalar_image.get_data()),
streamlines,
  File
"/usr/local/tractseg/lib/python3.8/site-packages/tractseg/libs/tractometry.py",
line 64, in evaluate_along_streamlines
    streamlines = _orient_to_same_start_region(streamlines, beginnings)
  File
"/usr/local/tractseg/lib/python3.8/site-packages/tractseg/libs/tractometry.py",
line 42, in _orient_to_same_start_region
    if beginnings[int(startpoint[0]), int(startpoint[1]),
int(startpoint[2])] == 0:
IndexError: index 64 is out of bounds for axis 2 with size 64
 16%|███████████▊

**Comment by wasserth** [comment]
Probably your FA image has different dimensions than your endpoint_segmentation images.
Could you post the dimensions / affine of those?
Did you use the `--preprocess` option?

**Comment by Renatar18** [comment]
On the preprocessing I ran eddy_correct and rotated the vectors before
starting tractSeg.

**Comment by wasserth** [comment]
The affine matrices in the header of the images (your diffusion image, peak image, segmentation and FA image) have to be the same. Probably this is causing the error.

**Comment by Renatar18** [comment]
They all seem to be the same. Are you willing to see the data? Should I
upload one of the "wrong" subjects?
