### ISSUE TITLE
Order of Tractometry sampling?

### ISSUE THREAD

**Issue by vukovicnikola** [MIC-DKFZ/TractSeg#124]
In what order does Tractometry sample the tracts? For example, for AF or ILF, is point 0 the most anterior segment, or the other way around? And how about for CST - is it sampling its way up, or down? The documentation is not clear on this issue.
Thank you!

**Comment by vukovicnikola** [comment]
@wasserth @soichih @jakobmm18 Any insights on this? 🙏

**Comment by wasserth** [comment]
Sorry for the late reply. I have been on vacation.
There should be a folder in the tractseg output which is called something like "endings_segmentation". Inside you can find a segmentation mask for the start and end region of each bundle. The Tractometry will start in the start-region.

**Comment by vukovicnikola** [comment]
Got it. Thank you, Jakob!

**Comment by soichih** [comment]
Not directly related, but not all fibers produced by tractseg(mrtrix) are going from start to end mask. Some fibers goes from end to start.

**Comment by vukovicnikola** [comment]
> Not directly related, but not all fibers produced by tractseg(mrtrix) are going from start to end mask. Some fibers goes from end to start.

How does that work with Tractometry averaging? If, like you say, one fiber's point 0 is in ending ROI, and another fiber's point 0 is in start ROI, does that mean that the average point 0 includes both?

**Comment by soichih** [comment]
@vukovicnikola Normally, you will have to reorient each fibers by creating a centroid streamline from a segment (assuming *most* fibers are oriented in the right way to begin with), then use something like https://dipy.org/documentation/1.0.0./reference/dipy.tracking/#orient-by-streamline to force all streamline in the same orientation, then you can do tractometry analysis. I believe tractseg does something similar.

**Comment by wasserth** [comment]
When doing tractometry, TractSeg will automatically reorient all streamlines to make sure they are starting in the same region. Then the averaging is applied. So as a user you do not have to worry about it.
