### ISSUE TITLE
Tractometry error - ValueError: could not convert string to float

### ISSUE THREAD

**Issue by thiagoparanhos** [MIC-DKFZ/TractSeg#125]
Hello!

I tried to run the last command on the tractometry pipeline (plot_tractometry_results -i tractseg/examples/subjects.txt -o tractometry_result.png --mc) but I came across the following error:

ValueError: could not convert string to float: '0,0,0.267,0.306,0.328,0,0,0,0,0,0,0,0,0,0,0.411,0.365,0,0,0,0,0.26,0.276,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.319,0.313,0,0'

Apparently TractSeg is not being able to use the infos from the excel sheet below:

<img width="1275" alt="Screen Shot 2020-10-04 at 20 23 34" src="https://user-images.githubusercontent.com/70239114/95029631-df2fd800-067f-11eb-97eb-07d83d949932.png">

The output from the command Tractometry -i TOM_trackings/ -o Tractometry_subject1.csv -e endings_segmentations/ -s ../FA.nii.gz generated excel sheets with comma as the decimal separator, but I was able to solve this problem and included dots as decimal separators.

Any clues on how this problem can be solved?

**Comment by wasserth** [comment]
Your subjects.txt file should be separated by spaces not by commas (see the example file here: https://github.com/MIC-DKFZ/TractSeg/blob/master/examples/subjects.txt).  Then it should work.

**Comment by thiagoparanhos** [comment]
The subjects.txt is already separated by spaces, that doesn't seem to be the issue.

<img width="784" alt="Screen Shot 2020-10-05 at 09 33 30" src="https://user-images.githubusercontent.com/70239114/95080144-06bd8980-06ee-11eb-81ec-cd1ee1abe708.png">

This is how the .txt file is organized 

<img width="829" alt="Screen Shot 2020-10-05 at 09 33 55" src="https://user-images.githubusercontent.com/70239114/95080178-1341e200-06ee-11eb-9ac8-5f2732fb0eb3.png">

**Comment by wasserth** [comment]
It seems that the Tractometry.csv files are saved with comma instead of semicolon separator. TractSeg Tractometry normally saves them with semicolon. Maybe you opened them with excel and saved them with excel and then maybe excel changed the separator.

**Comment by thiagoparanhos** [comment]
I opened the Tractometry.csv files with .txt and replaced all the coomas for semicolons. It worked smoothly!
Just one last question: How can I generate an image for the ATR just like the one below?

<img width="279" alt="Screen Shot 2020-10-05 at 12 57 38" src="https://user-images.githubusercontent.com/70239114/95102981-6f1a6400-070a-11eb-9b8c-91d000270f75.png">

**Comment by wasserth** [comment]
Creating an image with these rainbow colors is not possible without doing changes in the code. However, you can get a 3D fiber image with the p-value or the fa value as colormap (see the --plot3D option here https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/Tractometry_documentation.md)
