### ISSUE TITLE
Averaging the segments

### ISSUE THREAD

**Issue by Renatar18** [MIC-DKFZ/TractSeg#126]
Hi all!

When I analyze FA in all segments in the tract of interest I'm getting several small groups of significant segments. Then I'm going to average the FA of these segments and analize the clusters. How many consequtive significant segments would you suggest for  clustering?

Thank you very much in advance!

**Comment by wasserth** [comment]
This really depends on what you are doing. I am not doing this kind of clustering so I can not recommend any number of segments.
