### ISSUE TITLE
FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'

### ISSUE THREAD

**Issue by difan0224** [MIC-DKFZ/TractSeg#127]
Hello, it seems an issue many people met before but I still do not find the good solution. I have already install all packages and all the latest version. Could you please give any suggestions?

TractSeg -i Diffusion.nii.gz --raw_diffusion_input
Creating peaks (1 of 3)...
Traceback (most recent call last):
  File "/Users/difan/mrtrix3/bin/dwi2response", line 102, in <module>
    if int(image.statistic('mask.mif', 'count', '-mask mask.mif')) == 0:
ValueError: invalid literal for int() with base 10: '130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n130895 \n1
Creating peaks (2 of 3)...
dwi2fod: [ERROR] no data in matrix file "tractseg_output/response.txt"
dwi2fod: [ERROR] CSD algorithm expects second argument to be the input response function file
Creating peaks (3 of 3)...
sh2peaks: [ERROR] cannot access file "tractseg_output/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/Users/difan/opt/anaconda3/lib/python3.7/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tractseg_output/peaks.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/difan/opt/anaconda3/bin/TractSeg", line 400, in <module>
    main()
  File "/Users/difan/opt/anaconda3/bin/TractSeg", line 244, in main
    data_img = nib.load(peak_path)
  File "/Users/difan/opt/anaconda3/lib/python3.7/site-packages/nibabel/loadsave.py", line 44, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'

**Comment by wasserth** [comment]
You have to first create a brain mask using for example fsl bet.
As soon as you created a brain mask called nodif_brain_mask.nii.gz in the same directory you can call 
TractSeg -i Diffusion.nii.gz --raw_diffusion_input​.
