### ISSUE TITLE
Something wrong with using --single_output_file

### ISSUE THREAD

**Issue by Silflame** [MIC-DKFZ/TractSeg#128]
There is an error in line 387 of /<path>/anaconda/bin/TractSeg when using --single_output_file.
You may need to fix 
`preprocessing.move_to_subject_space()`  
with 
`preprocessing.move_to_subject_space_single_file()`.

**Comment by wasserth** [comment]
Unfortunately I can not reproduce this error. Could you please tell me which command did you execute? And which version of TractSeg are you using?

**Comment by Silflame** [comment]
I used the v2.1.1 and the command I used as follow:
`TractSeg -i dwi.nii.gz -o /tractseg/ --bvals bvals --bvecs bvecs --raw_diffusion_input --preprocess --single_output_file`

**Comment by wasserth** [comment]
The same command does not result in an error for me. Could you post the complete error messsage?
