### ISSUE TITLE
Questions about the input of the raw data.

### ISSUE THREAD

**Issue by Silflame** [MIC-DKFZ/TractSeg#129]
Hi, I want to ask if I'm using `--raw_diffusion_input` and `--preprocess`, is it necessary to do eddy_correct for the raw data before taking the data as input? In other words,  I am concerned about whether this pipeline will automatically perform eddy_correct with the this commd:
`TractSeg -i /dti/data.nii.gz -o /output/ --bvals /dti/bvals --bvecs /dti/bvecs --raw_diffusion_input --preprocess --single_output_file`.
And when using this command, what preprocessing operations will it contain ?
Thank you.

**Comment by wasserth** [comment]
This command will not run eddy_correct for you. You will have to do that yourself before feeding the data to the script.  
* `--preprocess` will only move the Diffusion image + bvecs to MNI space (rigid registration) and move the results of TractSeg back to subject space in the end
* `--raw_diffusion_input` will only run Mrtrix CSD and extract the peaks 

Everything else you have to do on your own.
