### ISSUE TITLE
Missing brain mask leads to a cryptic error message

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#13]
Hi. I was trying to troubleshoot this error message.

```
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 196, in <module>
    output_format=args.tracking_format)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/Mrtrix.py", line 178, in track
    " -include " + tmp_dir + "/" + bundle + "_e.nii.gz" +
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

For some reason, I had to set `--brain_mask testdata/mask.nii.gz ` when I am running it with --track on one of our HPC system but works fine without it on Ubuntu 16 machine. (We are running via singularity so it shouldn't really matter..)

Even with --brain option set, TractSeg fails with OOM on our HCP system.

```
=>> PBS: job killed: vmem 289836974080 exceeded limit 68719476736
```

Here is the content of my testdata

```
hayashis@carbonate(h2):/N/dc2/scratch/hayashis/tractseg/testdata(master*) $ ls -lrt
total 1477428
-rwxr-xr-x 1 hayashis uits         26 Oct  8 09:41 makemask.sh
-rw-r--r-- 1 hayashis uits   13256170 Oct  8 09:42 t1.nii.gz
-rw-r--r-- 1 hayashis uits    3207305 Oct  8 09:42 mask.nii.gz
-rw-r--r-- 1 hayashis uits 1496386061 Oct  8 09:42 dwi.nii.gz
-rw-r--r-- 1 hayashis uits       9507 Oct  8 09:42 dwi.bvecs
-rw-r--r-- 1 hayashis uits       1631 Oct  8 09:42 dwi.bvals
lrwxrwxrwx 1 hayashis uits          9 Oct  8 13:35 T1w_acpc_dc_restore_brain.nii.gz -> t1.nii.gz
```

and I am running TractSeg with following options

```
TractSeg -i tractseg_output/peaks.nii.gz -o . --output_type TOM --track --filter_tracking_by_endpoints
```

**Comment by soichih** [comment]
We run TracSeg via singularity so this issue doesn't make sense that it only happens on one of our HPC cluster. My current guess is that something from the host OS is getting injected into the python path (like $HOME/.local/lib stuff).

Meanwhile.. we are also seeing following error message when we run --track on another cluster.

```
+ TractSeg -i tractseg_output/peaks.nii.gz -o . --output_type TOM --track --filter_tracking_by_endpoints
INFO: font search path ['/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/ttf', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/afm', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
INFO: generated new fontManager
100%|##########| 144/144 [02:11<00:00,  1.10it/s]
100%|##########| 144/144 [02:24<00:00,  1.13s/it]
100%|##########| 144/144 [02:10<00:00,  1.05it/s]
100%|##########| 144/144 [02:18<00:00,  1.11it/s]
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 202, in <module>
    output_format=args.tracking_format)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/Mrtrix.py", line 195, in track
    reference_affine, smooth=smooth)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/FiberUtils.py", line 110, in convert_tck_to_trk
    streamlines = FiberUtils.compress_streamlines(streamlines, compress_err_thr)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/FiberUtils.py", line 57, in compress_streamlines
    pool = multiprocessing.Pool(processes=nr_processes)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

```

TractSeg just forks mrtrix command via Popen(), so I don't know why it's having a problem allocating memory.. I know mrtrix generates a tons of stdout/err stuff. Could it be that Popen is trying to hold on to the output and running out of memory because of it?

**Comment by wasserth** [comment]
Regarding the out of memory problem: `--track` needs quite a bit of memory on my machine as well. I have 32GB of RAM and it uses the majority of it. Not sure yet why it needs so much. How much RAM do you have to the cluster where it fails?

**Comment by soichih** [comment]
It seems to be failing on the cluster where the max is 30GB and another one with 31GB. It seems to work fine on machine that has 64GB of memory.

So, if I understand correctly, TractSeg is crashing when it tries to initialize multiprocessing.Pool() with following cpu count
> nr_processes = psutil.cpu_count()
I believe this won't work on shared HPC cluster where you can only use up to the requested number of CPUs and memory. Is there anyway to specify the number of cores / max-mem that I'd like TractSeg to use?

**Comment by soichih** [comment]
I just read this thread > Memory-wise, we already know that subprocess.Popen uses fork/clone under the hood, meaning that every time you call it you're requesting once more as much memory as Python is already eating up,

**Comment by wasserth** [comment]
TractSeg is only using `multiprocessing.Pool` for compressing of streamlines. If you take the most recent master branch you can go to line 195 in `tractseg/libs/Mrtrix.py` and set `compress_err_thr=None`. Then TractSeg will not compress the streamlines and therefore not use multiprocessing. You could try that to verify that `multiprocessing.Pool` is the actual problem.

**Comment by wasserth** [comment]
I tested the maximum memory consumption on my local ubuntu machine and got the following results:
`--output_type TOM --track`: 17206MB
`--output_type TOM --track` without compression: 17211MB
`--output_type TOM --track --only_track`: 280MB
`--output_type TOM --track --only_track` without compression: 257MB

I am having a GPU on the machine. If I run TractSeg on a machine with only CPU it takes 15731MB for `--output_type TOM --track`.

Are you using v1.6? It contains some memory optimisations compared to v1.5.

**Comment by wasserth** [comment]
I fixed the problem that TractSeg `--track` sometimes fails when you do not provide a brain mask. Now `--track` always works without specifying a brain mask.

**Comment by wasserth** [comment]
I am currently working on a solution to reduce the memory consumption for TOM down to around 9GB. This might solve your memory problems on the cluster. I am trying to release it tomorrow.

**Comment by soichih** [comment]
Yes, we are having this issue on 1.6. Thanks for the update on missing brain mask. Should I open another ticket for the memory issue? 

Our jobs are getting killed on most of our machines now. From the log, it looks like TractSeg was consuming about 2.7T of memory vmem. 

![screen shot 2018-10-16 at 7 23 15 pm](https://user-images.githubusercontent.com/923896/47166949-55887380-d2cb-11e8-88ea-6ebf574da9af.png)

**Comment by wasserth** [comment]
The master branch now only needs around 9GB of RAM for TOM (and anything else). 
Do you get such high memory usage only when you use `--track` or always?

**Comment by soichih** [comment]
OK. I found something interesting. I've run the --track step locally and observed that as TractSeg processes each track, there will be more and more TractSeg processes that piles up - even the one that's already finished (1 per each tract)

It eventually runs out of memory and all processes die. 

![screenshot from 2018-10-19 13-43-04](https://user-images.githubusercontent.com/923896/47234877-3cec8c00-d3a5-11e8-9c9c-d91a9940684e.png)
 
So, something is wrong with how the threads are forked or how it's terminating.

**Comment by wasserth** [comment]
I fixed the problem with the high number of processes getting generated. I missed to do `pool.close()`. I think now it should work on the cluster even if it uses all available CPUs (therefore I did not add the option `--cpus N` yet).

**Comment by soichih** [comment]
Thanks. I am testing the master branch code now, and so far so good! 

Some of our HPC clusters has a lot of cores (like 24). I request for 8 cores for each job so that scheduler can run other jobs on the same machine (or 3 of my jobs as 8x3=24). If all 3 jobs uses 24, then it will most likely CPU starve, or risk getting killed by the scheduler for using more than requested number of cores. I think it's important to be able to limit the number of CPU used via command line.

**Comment by wasserth** [comment]
Ok, I added a new command line option `--nr_cpus n`.
