### ISSUE TITLE
Fix to "cannot import name 'joblib'"

### ISSUE THREAD

**Issue by roeysc** [MIC-DKFZ/TractSeg#131]
Hi there!
In the .../tractseg/libs/img_utils.py code, there's an import call to joblib. 
It seems that with the new version of scikitlearn, we can longer import joblib with **from sklearn.externals import joblib** as before. Instead, we have to use **import joblib** (see [here](https://github.com/joblib/joblib/issues/1059)).
I hope this is useful and relevant!
Best,
Roey

**Comment by wasserth** [comment]
Hi Roey,
thanks for pointing this out. In the newest versions of TractSeg this should already be fixed. You can update by doing `pip install --upgrade TractSeg`.
