### ISSUE TITLE
Where is the data size check implementation?

### ISSUE THREAD

**Issue by zhao98** [MIC-DKFZ/TractSeg#133]
Hi, I made a small modification in the network to train my data, but met this error during my training `Exception in background worker 2: data and seg must have the same spatial dimensions.`Could you tell me which module is this data size checking definated in please? I did not find it.

**Comment by zhao98** [comment]
The output size is twice the input size in my training dataset. And I want to train my model. How to deal with this error?

**Comment by wasserth** [comment]
This error is part of the [batchgenerators](https://github.com/MIC-DKFZ/batchgenerators) library which TractSeg uses during Training. For your training data the peak images and the label images need to have exactly the same spatial dimensions. If this is not the case you have to change the data before feeding it to TractSeg.

**Comment by zhao98** [comment]
I found it. Thanks!
