### ISSUE TITLE
Distortion correction

### ISSUE THREAD

**Issue by XL258** [MIC-DKFZ/TractSeg#134]
Hello,

I'm wondering why EPI distortion correction and B0-field inhomogeneity correction are not needed for TractSeg.
Are these two preprocessing steps also not required for doing Tractometry? 

I would appreciate any help!

**Comment by wasserth** [comment]
Hi, 
these steps are needed, but you have to do them on your own before feeding the images to TractSeg. TractSeg is not doing any artifact correction.
You can use something similar to the following script for the preprocessing of your raw DWI images:
https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/utility_scripts/dwi_preprocessing.sh

**Comment by XL258** [comment]
> Hi,
> these steps are needed, but you have to do them on your own before feeding the images to TractSeg. TractSeg is not doing any artifact correction.
> You can use something similar to the following script for the preprocessing of your raw DWI images:
> https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/utility_scripts/dwi_preprocessing.sh



Thank you very much for your help!

The script, dwi_preprocessing.sh, includes eddy and motion correction, but seems not include EPI distortion correction. Also in Chandio et al. 's paper, EPI distortion correction is also not mentioned in the preprocessing section.

My problem is that I didn't collect b0 images in the opposite PE direction (or fieldmap), so I cannot correct for EPI distortion. 

I wonder whether it is a big problem or it is less detrimental in TractSeg, that the image distortion is not corrected.

Any suggestion would be highly appreciated!

**Comment by wasserth** [comment]
This depends on how strong the EPI distortion artifacts in your images are. If they are very minor and you do not have a B0 with opposite PE direction you are probably fine without.

**Comment by XL258** [comment]
> This depends on how strong the EPI distortion artifacts in your images are. If they are very minor and you do not have a B0 with opposite PE direction you are probably fine without.

I see. Thank you!
