### ISSUE TITLE
High resolution segmentation.

### ISSUE THREAD

**Issue by zhao98** [MIC-DKFZ/TractSeg#136]
Hi, I read your paper 'Combined tract segmentation and orientation mapping for bundle-specific tractography'. In the paper, you mentioned that TractSeg could provide a segmentation from LR to HR, and the LR data is generated through 'Data augmentation'. What if I don't want to perform a low resolution to high resolution segmentation? I just want to use HR data as the network input. How to change the experiment hyperparameters? Could you help me with this please?

**Comment by wasserth** [comment]
You can change the Data augmentation settings in your experiment. You can see all the options in `tractseg/experiments/base.py`. Look at the options starting with `DAUG_`.
If you do not want the images to be downsampled to lower resolution during training you have to do
`DAUG_RESAMPLE = False` and `DAUG_RESAMPLE_LEGACY = False`. You might also want to deactivate bluring as this is very similar in its effect: `DAUG_GAUSSIAN_BLUR = False`

**Comment by zhao98** [comment]
I got it. Thanks!
