### ISSUE TITLE
Documentation needed?

### ISSUE THREAD

**Issue by Leo-Ryu** [MIC-DKFZ/TractSeg#137]
Hello,

I’ve been working on a platform for editable codebase documentation and noticed this repo's documentation consists of a few md files. Would it be useful if I generated/hosted docs for this repo?

The platform:

1) has a modern markdown editor to allow people to quickly and easily create new documents/user guides
2) is similar to readthedocs/sphinx in that reads through the codebase and builds/hosts linkable pages describing classes and functions, as well as their usages in the codebase. However unlike readthedocs/sphinx, it doesn't require any configuration to get up and running
3) tracks the github repo so that every build has the latest code

Sincerely hoping I can be of use to you and your project!

**Comment by wasserth** [comment]
Thank you for the offer. However, I am fine with the documentation as it is right now.
