### ISSUE TITLE
Multiprocessing TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by vukovicnikola** [MIC-DKFZ/TractSeg#138]
Running the following command results in the below error:

`Tracking -i tractseg/peaks.nii.gz -o ./ --nr_fibers 6000 --tracking_format tck`

Error:
>   0%|                                                                                                                                               | 0/72 [00:01<?, ?it/s]
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 156, in process_seedpoint
>     streamline_part1, length_1 = process_one_way(peaks, streamline1, max_nr_steps, step_size, probabilistic,
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 51, in process_one_way
>     dir_raw = get_at_idx(peaks, (last_point[0], last_point[1], last_point[2]))
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 42, in get_at_idx
>     return img[int(idx[0]), int(idx[1]), int(idx[2])]
> TypeError: 'NoneType' object is not subscriptable
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/nikola/anaconda3/envs/tractseg2020/bin/Tracking", line 169, in <module>
>     main()
>   File "/Users/nikola/anaconda3/envs/tractseg2020/bin/Tracking", line 159, in main
>     tracking.track(bundle, input_path, Config.PREDICT_IMG_OUTPUT,
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/site-packages/tractseg/libs/tracking.py", line 219, in track
>     streamlines = tractseg_prob_tracking.track(tom_peaks, max_nr_fibers=nr_fibers, smooth=5,
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 247, in track
>     streamlines_tmp = pool.map(partial(process_seedpoint, next_step_displacement_std=next_step_displacement_std,
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/multiprocessing/pool.py", line 364, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/Users/nikola/anaconda3/envs/tractseg2020/lib/python3.8/multiprocessing/pool.py", line 768, in get
>     raise self._value
> TypeError: 'NoneType' object is not subscriptable

**Comment by wasserth** [comment]
Do all of your files (peaks.nii.gz, tract_segmentations/*, endings_segmentation/*, TOM/*) have the same dimensions (shape) and affine header?

**Comment by vukovicnikola** [comment]
They all appear to have the same dimensions. Is there a reason why TractSeg would generate images of different sizes? I guess it's another reason?

**Comment by wasserth** [comment]
TractSeg is only generating images with the same size. However, sometimes people are swapping files inbetween the TractSeg steps and then of course problems might occur. Does it work if you use a different `--tracking_format` ? Sorry, for not being able to give you a straight forward solution, but for me this command is working. So it is hard to reproduce.

**Comment by vukovicnikola** [comment]
I get the same error when using the default tracking_format, instead of tck. No swapping of files between steps i.e. all intermediary files are TractSeg generated. If you provide me an email I can send you some sample inputs to test? (305mb)

**Comment by wasserth** [comment]
You can find my email here: https://www.sciencedirect.com/science/article/pii/S1053811918306864?via%3Dihub#!

**Comment by vukovicnikola** [comment]
Thank you! You should see some example input files in your inbox 🙏

**Comment by zhenxingjian** [comment]
I found the same error here. May I ask how did you solve this error?

**Comment by jgburg** [comment]
I am also, having the same error. Please could you share a solution if this was resolved? :)

**Comment by vukovicnikola** [comment]
I ended up just reinstalling TractSeg in a new Python environment and that seemed to do it 👍

**Comment by warddef** [comment]
Had the same issue on a mac. Downgrading to python 3.7 solved the issue
