### ISSUE TITLE
Does this support if there is only DTI without the original dMRI data?

### ISSUE THREAD

**Issue by zhenxingjian** [MIC-DKFZ/TractSeg#139]
Hi,

Thanks for this wonderful tool. 
Right now, I only have the access to the DTI data (92x92x92x6) instead of the original dMRI data (92x92x92x33).
But I do have the bvals and bvecs and the mask. 
Will this tool work for this setup?

**Comment by wasserth** [comment]
Hi,
in this case you can not use TractSeg unfortunately. You will need the raw dMRI data.
