### ISSUE TITLE
Can't visualize generated .trk

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#14]
We are having a trouble opening generated .trk files with tractvis. The .trk file loads but I don't see it displayed anywhere.

![screenshot from 2018-10-08 20-34-05](https://user-images.githubusercontent.com/923896/46640373-a369e280-cb39-11e8-965d-2307f2b87d3c.png)

track_vis command shows the volume dimension to be all-0

```
$ ./track_vis CA.trk -l 20

Reading CA.trk ...done
Number of tracks: 2000
Number of tracks to render: 2000
Number of line segments to render: 33812
Mean track length: 68.81 +/- 15.16 mm

Volume dimension: 0 0 0
Voxel size: 1.250 1.250 1.250
Can not load camera info from tmp.cam
```

I am wondering if affine information is properly stored on generated .trk files.

**Comment by LucSam** [comment]
You can use freesurfer's freeview. It's able to load .trk files via File -> load Tract.

**Comment by soichih** [comment]
I am seeing a similar issue with freeview. When I load just the .trk, nothing gets displayed (all black). I have to load a volume first (which sets the default affine?) then load .trk so that I can view the tracts. I have other .trk files that I can visualize just fine with freeview, so I am sure that this issue is caused by TractSeg not outputting .trk with correct affine information.

**Comment by soichih** [comment]
I just noticed that the "volume dimension" is set to 0 for TractSeg generated .trk.

```
Volume dimension: 0 0 0
Voxel size: 1.250 1.250 1.250
```

I believe it should be set to non-0 (like 1?)

**Comment by wasserth** [comment]
I updated the code. Now the volume dimensions are also stored and the fibers can be displayed in TrackVis. However, when also displaying the FA image in TrackVis, the fibers and the FA do not properly align. So far I was not able to find out the reason for that. In FreeView, dipy and MITK Diffusion the fibers and the FA image do align as expected.

**Comment by pietroastolfi** [comment]
Hi @wasserth ,

the ground-truth tracts '.trk' that you have published are all missing the correct affine. 
TRK format differently from TCK requires the streamlines to be stored  in the native space (voxel space), and thus it requires also to save the affine to project the streamlines from voxel space to real coordinate space (RASmm). When you save a trk files you should use the new api of nibabel where the [nibabel.trackvis](http://nipy.org/nibabel/reference/nibabel.trackvis.html) has been deprecated and functions that deal with trk has been redefined under [nibabel.streamlines](http://nipy.org/nibabel/reference/nibabel.streamlines.html). 

For the specific case of your ground-truth tracts I've adjusted the header by using the following script:

```
#!/usr/bin/env python

import os
import nibabel as nib
import numpy as np

def save_tract_trk(
                streamlines,
                affine=None,
                vox_sizes=None,
                vox_order='LAS',
                shape=None,
                out_file='tract.trk'):
    """
    This function saves tracts in Trackvis '.trk' format.
    The default values for the parameters are the values for the HCP data.
    The HCP default affine is: array([[  -1.25,    0.  ,    0.  ,   90.  ],
                                      [   0.  ,    1.25,    0.  , -126.  ],
                                      [   0.  ,    0.  ,    1.25,  -72.  ],
                                      [   0.  ,    0.  ,    0.  ,    1.  ]], 
                                     dtype=float32)

    parameters:
    - streamlines: sequence of streamlines in RASmm coordinate
    - affine: 4d array with voxel to RASmm transformation
    - vox_sizes: 1d array with the voxels sizes, default [1.25, 1.25, 1.25]
    - vox_order: orientation convention, default to 'LAS'
    - shape: 1d array with dimensions of the brain volume, default [145, 174, 145]
    - out_file: string with filepath of the output file
    
    returns: void
    """
    
    if affine == None:
        affine = np.array([[  -1.25,    0.  ,    0.  ,   90.  ],
                           [   0.  ,    1.25,    0.  , -126.  ],
                           [   0.  ,    0.  ,    1.25,  -72.  ],
                           [   0.  ,    0.  ,    0.  ,    1.  ]], 
                          dtype=np.float32)

    if vox_sizes == None:
        vox_sizes = np.array([1.25, 1.25, 1.25], dtype=np.float32)
        
    if shape == None:
        shape = np.array([145, 174, 145], dtype=np.int16)

    if out_file.split('.')[-1] != 'trk':
        out_file = out_file + '.trk'

    # Create a new header with the correct affine and # of streamlines
    hdr = nib.streamlines.trk.TrkFile.create_empty_header()
    hdr['voxel_sizes'] = vox_sizes
    hdr['voxel_order'] = vox_order
    hdr['dimensions'] = shape
    hdr['voxel_to_rasmm'] = affine
    hdr['nb_streamlines'] = len(streamlines)

    nib.streamlines.save(
        nib.streamlines.Tractogram(streamlines, affine_to_rasmm=np.eye(4)),
        out_file,
        header=hdr)


if __name__ == '__main__':

    subjects = os.listdir('HCP105_Zenodo')
    subjects.sort()

    for sub in subjects:
        print("Processing subject: %s" % sub)
        
        # ignore the Readme and the License file
        if sub.split('.')[-1]  == 'txt':
            continue
            
        tracts_dir = os.path.join('HCP105_Zenodo', sub, 'tracts')
        tracts_list = os.listdir(tracts_dir)
        tracts_list.sort()
        
        # initialize tracts counter
        n_tracts = 0

        # correct tracts
        for tract_file in tracts_list:
            # file check
            if tract_file.split('.')[-1] != 'trk':
                continue
            
            n_tracts +=1
            
            print("\tCorrecting tract: %s" % tract_file)
            
            # load the trk with the old api, trackvis.read(), because the it 
            # does not apply any transformation during loading.
            tract, _ = nib.trackvis.read(os.path.join(tracts_dir, tract_file))
            
            tract_sl = [sl[0] for sl in tract]
            
            # create output directory if it doesn't exist
            out_dir = os.path.join('HCP105_Zenodo', sub, 'tracts_correct')
            if not os.path.exists(out_dir):
                os.makedirs(out_dir)
        
            # save the tract with the same filename and with the HCP default header
            save_tract_trk(tract_sl, out_file=os.path.join(out_dir, tract_file))
            
        try:
            assert(n_tracts == 72)
        except AssertionError:
            e.args += ("For sub-%s %d tracts found, while 72 are expected" 
                                % (sub, n_tracts), )
            raise
```

Let me know if this works also for you.

**Comment by barbrakr** [comment]
Hi @wasserth .

Thank you for providing this tool - I have tried the above code and unfortunately the FA images and the trk files don't align perfectly in my case.

It seems like I may have to adjust this: 
    The HCP default affine is: array([[  -1.25,    0.  ,    0.  ,   90.  ],
                                      [   0.  ,    1.25,    0.  , -126.  ],
                                      [   0.  ,    0.  ,    1.25,  -72.  ],
                                      [   0.  ,    0.  ,    0.  ,    1.  ]], 
                                     dtype=float32)

To something that will represent my voxel size and FOV, correct?
        affine = np.array([[  -1.81,    0.  ,    0.  ,   108.  ],
                            [   0.  ,    1.81,    0.  , -108.  ],
                            [   0.  ,    0.  ,    1.8,  -70.  ],
                            [   0.  ,    0.  ,    0.  ,    1.  ]], 
                          dtype=np.float32)

Hoever, the overlay in TrackVis is not perfekt. Is there a way to solve this?
Thank you,
Kind wishes,
Barbara

**Comment by wasserth** [comment]
Hi,
you do not need to have the exactly same voxel spacing und affine as the HCP default. You just have to align your image with MNI space. And your peaks image which you input to TractSeg has to be in the same space as your FA image.

Moreover, you could check if the streamlines files align properly if you are using `--tracking_format tck` or `--tracking_format trk`. Different viewers interpret the formats differently and therefore depending on your viewer you might have more success with a different format. (tck seems more stable than trk)
