### ISSUE TITLE
Beginning/Endings Segmentation Inconsistent

### ISSUE THREAD

**Issue by aritche** [MIC-DKFZ/TractSeg#142]
Hi,

I am trying to replicate TractSeg. My first goal is to generate the required dataset, i.e. the tract segmentations, start/end segmentations, and TOMs.

I have successfully generate the tract segmentations using ```resources/trk_2_binary.py```.

I am now trying to generate start/end region segmentations using ```tractseg/libs/create_endpoints_mask_with_clustering.py```. The script runs successfully, however there are inconsistencies in the start regions (and hence end regions) for the same tract between subjects.

Attached is an example comparison of the 'beginnings' regions generated by ```create_endpoints_mask_with_clustering.py``` for CST_left of subjects 987983 [first image] and 599469 [second image]. You can see that the actual segmentations are correct, however the beginning region for one subject has been interpreted as the ending region for the other subject.

![Screenshot from 2021-01-17 20-57-31](https://user-images.githubusercontent.com/11988281/104837132-bbc72b00-5906-11eb-88c5-a41bfa2f1dae.png)
![Screenshot from 2021-01-17 20-57-41](https://user-images.githubusercontent.com/11988281/104837136-c1247580-5906-11eb-9f64-618880e438a7.png)

1. Am i using the correct script to replicate the beginnings/endings segmentation dataset that was used to train the model? I am not sure why I am not getting consistent results across subjects. 
2. Am I supposed to be using ```tractseg/resources/random_forest_peak_orientation_detection.pkl```? I'm not sure where that fits in with the ```create_endpoints_mask_with_clustering.py``` file.

**Comment by wasserth** [comment]
1. The scrips `tractseg/libs/create_endpoints_mask_with_clustering.py` does not ensure that the start and end region are never flipped between subjects. You have to do that on your own. E.g. Register all subject to the same space and then take the start/end regions of one subject as reference. Then check the overlap of the regions of all other subjects and thereby determine which is the start region and which is the end region in all subjects.

2. You can ignore `tractseg/resources/random_forest_peak_orientation_detection.pkl`. This file was needed for something completely different.
