### ISSUE TITLE
Plot3D Blank When ALL Areas are Significant

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#150]
## Operating Info
Tractseg 2.3 in dedicated anaconda environment
Running on a Mac Big Sur 11.4 (on data stored on a linux cluster via SSH)

## Problem
When I run `plot_tractometry_results` with `plot3D --pval` and each node of a given tract is above the critical pFWE, the whole tract is gray instead of red, as if no nodes were significant.

**Comment by wasserth** [comment]
Thanks for reporting this bug! I just committed a fix for this bug to the master branch.
