### ISSUE TITLE
Problem with Tracking command

### ISSUE THREAD

**Issue by Mtay316** [MIC-DKFZ/TractSeg#154]
Hi TractSeg team,
I am a new user of your tool. I have followed the pipeline that you explained in your tutorial page of how to use this tool on our non-HCP dataset. My diffusion data is a 2mm isotropic multishell (0,1000,2000,3000) image. 

The first three steps for Tract segmentation, ending segmentation, and TOM finished perfectly. I just have a problem with the last step of tractography.  

This is the command I ran:

Tracking -i peaks.nii.gz -o tractseg_output --tracking_format tck --algorithm prob --nr_fibers 5000

And this is the error I got:

Traceback (most recent call last):
  File "/usr/local/bin/Tracking", line 169, in <module>
    main()
  File "/usr/local/bin/Tracking", line 159, in main
    tracking.track(bundle, input_path, Config.PREDICT_IMG_OUTPUT,
  File "/usr/local/lib/python3.9/site-packages/tractseg/libs/tracking.py", line 220, in track
    streamlines = tractseg_prob_tracking.track(tom_peaks, max_nr_fibers=nr_fibers, smooth=5,
  File "/usr/local/lib/python3.9/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 249, in track
    seed_generator(mask_coords, seeds_per_batch))
  File "/usr/local/lib/python3.9/site-packages/tractseg/libs/tractseg_prob_tracking.py", line 190, in seed_generator
    random_indices = np.random.choice(nr_voxels, nr_seeds, replace=True)
  File "mtrand.pyx", line 903, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

Could you please help me with how to fix this problem?

Regards,
Maryam

**Comment by wasserth** [comment]
Hi Maryam,
does it work if you first move your raw input (the dwi data) to MNI space and then rerun all the TractSeg commands?

**Comment by wasserth** [comment]
I will be on vacation for the next week, so will take a bit longer till I reply.

**Comment by Mtay316** [comment]
I have tried after registration on MNI space as well.  I got the same error. 
Is there any other clue that can help?

**Comment by Mtay316** [comment]
I sent you my diffusion images by email.

**Comment by jakepalmer** [comment]
@Mtay316 @wasserth I'm running into this same error. Do you mind sharing what the solution was?
