### ISSUE TITLE
3d plots - Tract appearing outside of glass brain

### ISSUE THREAD

**Issue by jgburg** [MIC-DKFZ/TractSeg#158]
Hi there,

I am having some trouble with the 3d visualisation as attached when running the following command:
![tractometry_result_CC_1_3D](https://user-images.githubusercontent.com/78034006/136630468-19b0af12-1dd0-482a-b2d0-aa3611bb5420.png)

plot_tractometry_results -i /subjects.txt -o tractometry_result.png --mc --alpha 0.05 --plot3D pval --tracking_dir /TOM_trackings --tracking_format trk

Please could I get some guidance on how to address this?

**Comment by smeisler** [comment]
Were your input data rigidly aligned to MNI, and is the `tracking_format` you specified the same as when you ran `Tracking`?

**Comment by wasserth** [comment]
When you do the manual transformation to MNI space as you have described (using flirt) then you do not need to use the `--preprocess` option. `--preprocess` will simply do the same thing with flirt as you did manually.

Do you have the lastest docker container? In June I fixed a bug related to alignment of the streamlines. So make sure your docker container is from after this fix. Also you could try if it works with `--tracking_format tck`.

All the normal commands in the documentation can be used with docker. Therefore there is no separate documentation for docker.

**Comment by wasserth** [comment]
In version 2.4 I made another bug fix for alignment of the trackings. You could try again with this version.
