### ISSUE TITLE
Faulty tracts when when feeding already calculated peaks and TOMs

### ISSUE THREAD

**Issue by LucSam** [MIC-DKFZ/TractSeg#16]
Hi, we're encountering faulty tracks when we feed previously calculated peaks and segmentations, as seen in the attached image. We tested with both .trk and .tck formats.
If we enter the command to calculate all data from scratch it works fine, but it unfortunately has to create the peaks and toms again.
![tractseg_error](https://user-images.githubusercontent.com/30386169/47029107-3c13ea00-d15a-11e8-99e6-7008bf1b9bbe.png)

**Comment by wasserth** [comment]
That's quite strange. What happens if you run MRtrix manually on your previously calculated peaks? e.g. `tckgen -algorithm FACT tractseg_output/TOM/CST_right.nii.gz CST_right_tracking.tck -seed_image your_brain_mask.nii.gz -minlength 40 -select 2000`

**Comment by LucSam** [comment]
That works very fine.

**Comment by wasserth** [comment]
Could you share your previously calculated peaks and segmentations so I can try to reproduce it? Otherwise it is quite hard to say what went wrong. When I try it, it works fine.

**Comment by LucSam** [comment]
The  size here on github seems to be too big (peaks are compressed 40mb). Can I share it somewhere else? Can you provide an email address?

**Comment by wasserth** [comment]
Probably also too big for email. Best would be if you upload it to Dropbox for example and send me the link via email. My address: j.wasserthal at dkfz.de

**Comment by LucSam** [comment]
Thank you for the fixel plot hint. We just looked at the different volumes which seemed fine. It works now properly. Best, Lucius
