### ISSUE TITLE
Error in run TracSeg

### ISSUE THREAD

**Issue by EromFreitas** [MIC-DKFZ/TractSeg#161]
Hi,
When I run the following command:
` TractSeg -i Diffusion.nii.gz -o tractseg_output --raw_diffusion_input --csd_type csd_msmt --brain_mask nodif_brain_mask.nii.gz`

I get the following error message:
![Captura de tela de 2021-10-14 10-15-42](https://user-images.githubusercontent.com/12056275/137332021-3f8559b0-6a6e-4501-bea9-3c9cb9c28788.png)

Can someone help me

**Comment by EromFreitas** [comment]
Hi, follow the files in the directory:

![Captura de tela de 2021-10-15 07-25-31](https://user-images.githubusercontent.com/12056275/137479270-c1ca5848-0c97-4e4f-83a3-00138b76bdf5.png)

When I run `--csd_type csd` doesn't work

**Comment by wasserth** [comment]
If even `--csd_type csd` does not work I guess there might something be wrong with your mrtrix setup or your data. I would try to run mrtrix on my own to see in more detail where things fail.
