### ISSUE TITLE
Error run TractSeg in Docker GPU

### ISSUE THREAD

**Issue by EromFreitas** [MIC-DKFZ/TractSeg#164]
Hi,

When I run the TractSeg command in a container, it stops in the Processing address 3. Below is the log:

`sudo nvidia-docker run -v /clinic_toc/tract:/data -t wasserth/tractseg_container_gpu:1.7.1 TractSeg -i /data/peaks.nii.gz -o /data/tractseg_output --output_type endings_segmentation

INFO: font search path ['/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/ttf', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/afm', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/pdfcorefonts']

INFO: generated new fontManager

Loading weights from: /root/.tractseg/pretrained_weights_endings_segmentation_v3.npz

Processing direction (1 of 3)
100%|███████████████████████████████████████████████████████████████| 144/144 [00:06<00:00, 20.61it/s]

Processing direction (2 of 3)
100%|███████████████████████████████████████████████████████████████| 144/144 [00:17<00:00,  8.13it/s]

/neurodocker/startup.sh: line 4:    19 Killed                  "$@"
`

**Comment by wasserth** [comment]
The GPU docker file is not up to date anymore. Only the CPU dockerfile is maintained. Please try again with the cpu container.
