### ISSUE TITLE
A question about MitkFiberDirectionExtraction.sh 

### ISSUE THREAD

**Issue by zhaolei4383** [MIC-DKFZ/TractSeg#165]
Hello! I'm doing research about TOM, however when I use MitkFiberDirectionExtraction to generate traning labels, it requires a parameter --mask. I don't understand what I need to enter for this parameter. I tried using the bundle mask, but the output is an empty file. What needs to be input for this parameter?

**Comment by wasserth** [comment]
It should be the bundle mask. See this issue for more details: https://github.com/MIC-DKFZ/TractSeg/issues/92

**Comment by zhaolei4383** [comment]
I think it may be the version of trk file. When I use MITK open my trk file, it will flip the tract. For example, AF_ Lef was supposed to be on the right, but it appeared on the left, while the corresponding bundle mask is still on the right. Then I used some fibers that still intersect with the mask even after flipping like CC_7, the output can generate directions in the area where they intersect.

**Comment by wasserth** [comment]
Yes, probably you have to download the older trk files as outlined in issue 92 as those are compatible with MITK.
