### ISSUE TITLE
Questions about alignment to MNI image

### ISSUE THREAD

**Issue by melthy001** [MIC-DKFZ/TractSeg#167]
Hello, TractSeg team!
    I am using non-HCP diffusion data to do fiber tracking. The data has two shells (b=1000/2000), each with 64 directions and the resolution is 2*2*2 mm. I get a white matter FOD group template following  fixel-based analysis pipeline using mrtrix3. Then, I want to segment the group WM_FOD image to generate interested WM pathways so as to extract tract-based FDC/FC/FD. So, I created the peak.nii.gz using sh2peaks, and follow the TractSeg tutorial and the results look like reasonable. But I am still worried about whether it is correct without normalizing to MNI space (It seems there is no direct way to align wm_fod to MNI? so I run the fowllowing cml directly). For the alignment, I got two questions as follows:
     1) how to check the orientation of raw data is consistent to that of HCP data, given the right/left is quite symmetry and looks the same. 
     2) Can wm_fod file directly register into MNI space or should I register the raw DWI data into MNI and rerun the preprocessed step and get a group template in MNI space and run the TractSeg cml
 Could you help me check the result and give the advice whether the alignment is needed to conduct?
the command line I used is as follows:
sh2peaks wm_fod_template.mif  peaks.nii.gz
TractSeg -i peaks.nii.gz --output_type tract_segmentation
TractSeg -i peaks.nii.gz --output_type endings_segmentation
TractSeg -i peaks.nii.gz --output_type TOM 
Tracking -i peaks.nii.gz --tracking_format tck
This is several tracts I generated:
![2021-11-23 11-35-39屏幕截图](https://user-images.githubusercontent.com/38070009/143019178-f65423fb-af59-41d6-95f5-fab0058de253.png)

Many thanks!!
Kitty Zhu

**Comment by wasserth** [comment]
1) To check the orientation you can have a look at the affine matrix of the files and see if it has the same signs as the HCP data. If the signs of the diagonal elements are the same as of the HCP data and the off-diagonal elements are all 0 (except for the offset which can be any number), then the orientation is the same as HCP data.

2) Registering the wm_fod file to MNI space would be possible with the mrtrix fod registration commands and an HCP fod image as target (as HCP is in MNI space, this will be sufficient. If you need a HCP image you can check the Diffusion.nii.gz image here: https://github.com/MIC-DKFZ/TractSeg/tree/master/examples) . But you could also register the DWI images to MNI space first and then do all the processing.

Your tracts look very well and it seems that they are not displaced. So probably your wm_fod template already has the same orientation as MNI space and you are fine and do not have to do anything.

**Comment by melthy001** [comment]
> 

Thanks very much for your quick and detailed reply!  I will have a try!
Just to make sure I understand your first answer: I print the data information using mrinfo command. I got a 3x4 transformation matrix, so this is the affine matrix (the first three columns) you referred to? If it is, as you can see from the below picture, the signs of the diagonal elements are the same as the HCP data, but the off-diagonal elements are a little bit deviated from 0, will this affect the result?
![2021-11-24 03-09-23屏幕截图 (1)](https://user-images.githubusercontent.com/38070009/143171819-7f5bb04a-c689-4a50-9cf5-433d3ae1f7c8.png)

**Comment by wasserth** [comment]
The off-diagonal elements (of the first 3x3 values) cause a rotation (the last column does not matter because it is the offset). But they are very small and therefore the rotation is also only very small. This means it should be no problem and your image basically has the same orientation as HCP_MNI data.

**Comment by melthy001** [comment]
Thanks very much!! I think all my problems were solved!!
