### ISSUE TITLE
Issue with the precise brain location of end and start region

### ISSUE THREAD

**Issue by melthy001** [MIC-DKFZ/TractSeg#168]
Hello! TractSeg team!
    I would like to know where I can  find the precise description about the end and start  region from which the white matter pathway originate and terminate. Because the definition of pathways   have different standards  and I want to make sure whether what I get is what I wants. ( I can roughly see the start and end region from the TractSeg processing files, but I was still wondering  if I could find the official description of the whole pathway.)

Thanks in advance!!
Kitty

**Comment by wasserth** [comment]
These are the WMQL (https://tract-querier.readthedocs.io/en/latest/) Queries for the tracts:
https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/WMQL_Queries.qry
However, there was also a bit of manual tuning involved. So the final tracts are not 100% identical to these queries. 
The start and end regions where derived from the final tracts, not the other way around. So the start/end region has no specific definition.

**Comment by melthy001** [comment]
Thanks very much for your reply!!
