### ISSUE TITLE
How to use xtract for tracking

### ISSUE THREAD

**Issue by XYWCQM** [MIC-DKFZ/TractSeg#169]
Hello, when I am going to use the following command "TractSeg -i peaks.nii.gz --tract_definition xtract" to perform xtract tracking, I get an error in "Tracking -i peaks.nii.gz --tracking_format tck": "FileNotFoundError: [ Errno 2] No such file or directory:'/data/bundle_segmentations/AF_left.nii.gz'", how can I adjust the parameters to be able to track xtract, thank you.

**Comment by wasserth** [comment]
`--tract_definition xtract` only works for tract segmentation or density map regression (dm_regression). It does not support TOM or Tracking. The reason is that xtract itself does not output streamlines but only a segmentation/density map.
