### ISSUE TITLE
3D Plots orientations are inconsistent with 2D Plots (tractometry)

### ISSUE THREAD

**Issue by DanielaMariaPinzon** [MIC-DKFZ/TractSeg#170]
Hi, 

When I run plot_tractometry_results the statistical comparison between groups shows the following:
![tractometry_result_FA](https://user-images.githubusercontent.com/83370287/150962221-b7d80cbd-a0ed-4f9a-ae8f-c3ddb4d8e5c7.png)

first; I would like confirm if the centroids along the Corpus Callosum are located from Right to Left (x axis 0 to 100, in the plots)
If this is correct, when plotting the 3D tracts, the results should be CC 3: significant differences located on Right Hemisphere, CC 4 : on the Left Hemisphere, and CC 5 on the more less over the mid-line of the brain. However, setting the 3D paths to subject 22 shows the following: 
![tract_result_pval_FA_CC_3_3D](https://user-images.githubusercontent.com/83370287/150963498-4aa9c018-f5ca-45e5-87a0-006219cbcb9a.png)  ![tract_result_pval_FA_CC_4_3D](https://user-images.githubusercontent.com/83370287/150963499-bc8da903-2682-4584-a6d2-42345c9ce7a1.png) ![tract_result_pval_FA_CC_5_3D](https://user-images.githubusercontent.com/83370287/150963553-b091e868-245c-4ac0-abfb-d52e51377ed3.png)

Then I tried using a different subjects' path for the 3D plots (sub-15) and it seems that the significant regions are located onto a different centroid/segment. This has occurred for various of my subjects. I previously re-oriented all images in the preprocessing steps using fslreorient2std, and then I aligned all images to MNI space using non-linear registration (fnirt) and checked tracks (.tck), TOM and bundle segments; all seem to be in the same orientation and MNI space. I do not understand how the algorithm places the significant areas onto the 3D plot, and how it changes from subject to subject. 

![tract_result_pval_FA_CC_3_3D](https://user-images.githubusercontent.com/83370287/150964599-30dc0f97-fa25-45b8-942c-34539cd7b369.png)
![tract_result_pval_FA_CC_4_3D](https://user-images.githubusercontent.com/83370287/150964831-46a15ff4-8b27-4814-a5d4-9b1c3ddbe740.png)
![tract_result_pval_FA_CC_5_3D](https://user-images.githubusercontent.com/83370287/150964854-7a3d5f70-f13c-4837-9ad7-41b04d36ec30.png)

In addition to this, I was wondering if we can have access the number of the segments (out of the 100) that had significant differences after the t-test saved in a cvs or txt file. The image is very illustrative but I would like to localize those segments for further analysis. 

Any recommendations or clues of what is going on behind this?

Thanks a lot!

**Comment by wasserth** [comment]
I had a quick look on the code and there might be a bug. I will do some more investigation next week.

**Comment by wasserth** [comment]
I did some more investigation and there is no bug. The problem is the following: The start and end region of each tract are not always aligned to the same side. For example CC_4 and CC_5 start in the right hemisphere. But CC_3 starts in the left hemisphere. You can see this buy looking at the <tract_name>_b.nii.gz files ("b" for beginning) inside of tractseg_output/endings_segmentation. There is no specific logic if the beginning is on the left or right hemisphere. It can be different for each tract. But it is constant over subjects. So CC_3 will always start in the left hemisphere for all subjects.
Unfortunately this is a bit inconvenient. You will have to check all <tract_name>_b.nii.gz files.

**Comment by DanielaMariaPinzon** [comment]
Hi again, 
thank you for having a look to this and for your suggestion. Your clarification was very helpful. Indeed, results are consistent within same subject.

On the other hand, I  was wondering if we can have access the number of the segments (out of the 100) that had significant differences after the t-test, and save them in a cvs or txt file. I would like to localize those segments for further analysis. I have tried saving  the "position" from the plot_tractometry_results but I was not able to do so. Do you have any suggestions on this?.

**Comment by wasserth** [comment]
Unfortunately there is no easy way to get those segments. You would have to edit the code.
You can insert `print(pvalues)` in line 247 in the file `bin/plot_tractometry_results`. This would print you the pvalues for each segment of each bundle.
