### ISSUE TITLE
--plot3D tag causing issues in plot_tractometry_results

### ISSUE THREAD

**Issue by CarolynMcNabb** [MIC-DKFZ/TractSeg#172]
Hello,

Firstly - I'm loving tractseg so thank you so much for making this software publicly available.

I'm having some issues with `plot_tractometry_results`.  When I run it without the `--plot3D` tag (or using `--plot3D none`, it works fine and creates the `tractometry_results.png` file. However, when trying to include either `--plot3D metric` or `--plot3D pval`, I get the following error:
```
/home/sapcm15/.local/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
/home/sapcm15/gitlab/wand/2.2_plot_tractometry_results.sh: line 50: 25681 Segmentation fault      (core dumped) plot_tractometry_results -i ${group_output_dir}/subjects.txt -o ${group_output_dir}/tractometry_result.png --mc --tracking_format tck --plot3D metric
```
I'm guessing this is an incompatibility issue with numpy, which seems to have deprecated `_asarray.py`.

Can you please tell me if there is a way around this?

Many thanks,
Carolyn

**Comment by wasserth** [comment]
I am happy to hear that TractSeg is doing a good job for you.
I think the issue it not related to numpy. This is just a deprecation warning, which means it is not an error yet.
If --plot3D is not working it is typically connected to fury and vtk which are used for 3d plotting. Could you check which version of fury you have installed (`pip list | grep fury`).

**Comment by CarolynMcNabb** [comment]
Thanks so much for getting back to me.
I'm using fury 0.7.1 (I had a compatibility issue between dipy and fury earlier whereby vtk wouldn't work, so I changed the versions for both of these - I'm now using dipy version 1.4.1). 
Which versions would you recommend?

**Comment by CarolynMcNabb** [comment]
Update: I have managed to create the 3D files and group statistical plot by using two separate lines of code (a work around but probably not the way you initially intended).

```
echo "Plotting 3D tractometry results"
plot_tractometry_results -i ${group_output_dir}/subjects.txt -o ${group_output_dir}/tractometry_result.png --mc --tracking_format tck --plot3D metric

echo "Plotting group-level tractometry results"
plot_tractometry_results -i ${group_output_dir}/subjects.txt -o ${group_output_dir}/tractometry_result.png --mc --tracking_format tck
```

I also updated vtk to version==9.1.0, which I think might have done something in the way of helping.
