### ISSUE TITLE
Visualize peaks.nii.gz

### ISSUE THREAD

**Issue by jasonbian97** [MIC-DKFZ/TractSeg#173]
You mentioned in FQA "In those cases you should view the peaks in mrview and make sure they have the proper orientation." I can visualize peaks.nii.gz using MITK, but how do you visualize peaks using mrivew. I tried: `-odf.load_vector` and `-vector.load`, but none works. For `vector.load`, it simply says this option does not exist. (Btw, I am using MRtrix3.0.3.)

Thanks!

**Comment by wasserth** [comment]
I open them in the GUI of mrview in the "fixel plot" toolbox
<img width="416" alt="Bildschirmfoto 2022-03-05 um 13 15 39" src="https://user-images.githubusercontent.com/26226563/156882559-bca5d4d4-ba8c-4f8e-817d-a64a9738ad53.png">
.
