### ISSUE TITLE
Problems are encountered with TractSeg

### ISSUE THREAD

**Issue by Monitoryang** [MIC-DKFZ/TractSeg#176]
fuying@fuying-System-Product-Name:~$ TractSeg
Traceback (most recent call last):
  File "/home/fuying/miniconda3/bin/TractSeg", line 20, in <module>
    from tractseg.libs import plot_utils
  File "/home/fuying/miniconda3/lib/python3.7/site-packages/tractseg/libs/plot_utils.py", line 22, in <module>
    from tractseg.libs import fiber_utils
  File "/home/fuying/miniconda3/lib/python3.7/site-packages/tractseg/libs/fiber_utils.py", line 10, in <module>
    from dipy.tracking.streamline import compress_streamlines as compress_streamlines_dipy
ImportError: cannot import name 'compress_streamlines' from 'dipy.tracking.streamline' (/home/fuying/miniconda3/lib/python3.7/site-packages/dipy/tracking/streamline.py)

**Comment by Monitoryang** [comment]
I am trying to use TractSeg on Ubuntu18.04. And I Install python3.7 and MRtrix3 using miniconda3, but encounter the above problems. How can I solve this problem? Thank you  for receiving your reply.

**Comment by wasserth** [comment]
You can either manually install an older version of dipy or you install the latest master of TractSeg which solves this issue:
```
pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
```

**Comment by Monitoryang** [comment]
> You can either manually install an older version of dipy or you install the latest master of TractSeg which solves this issue:
> 
> ```
> pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
> ```

Thank you for your reply. I installed an older version of dipy which solved the problem.
