### ISSUE TITLE
"bundle ... contains less than 5 streamlines. Saving value 0 for this bundle.

### ISSUE THREAD

**Issue by RJMullins** [MIC-DKFZ/TractSeg#177]
I am using tractseg via docker 20.10.7 on Ubuntu 20.04.4.

I can run the sample data through the tractography steps cleanly as per your documentation. Unfortunately, it fails on my own data, which is preprocessed and MNI registered in a near-identical way. When I get to the last step (5. Run Tractometry) some of the tracts in the Tractometry_xxx.csv file are complete, but most are not. I have tried flipping peaks every which way to no avail.

The error message for the empty columns is "Bundle CST_right contains less than 5 streamlines. Saving value 0 for this bundle." and so on for many of the bundles. The input bundles look ok to me, but I might not know exactly what to look for.

I'm sure something is different about my input images but I am not sure what this error means and how to start addressing it. Does it have to do with input resolution? My input image resolution is lower - 1.8x1.8x2.0 before MNI transform into 1.25x isometric.

**Comment by wasserth** [comment]
The image resolution should not be a problem. Do the tract segmentations generated by TractSeg look good? What version of TractSeg are you using?

**Comment by RJMullins** [comment]
FYI, I just came back to this. It turns out tractseg didn't work well after I used 1dDW_gradomat++ to flip the y vectors in the bval/bvecs file. When I used a non flipped data set tractseg worked just fine.

**Comment by wasserth** [comment]
I am happy to hear to it worked finally.
