### ISSUE TITLE
TractSeg: command not found

### ISSUE THREAD

**Issue by yoyoxueli123** [MIC-DKFZ/TractSeg#179]
I am using TractSeg via macOS. 
**python version 3.8.9
pip3 version 22.0.4**
pytorch was also successfully installed, please see:
```
lixue@pc244-171 examples % pip3 show torch
Name: torch
Version: 1.11.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /Users/lixue/Library/Python/3.8/lib/python/site-packages
Requires: typing-extensions
Required-by: torchaudio, torchvision
lixue@pc244-171 examples % 
```
I installed the TractSeg via `pip3 install TractSeg`, and I can see the TractSeg exists in the folder `/Users/lixue/Library/Python/3.8/bin`, but when I try to type `TractSeg --help` , it showed: `command not found: TractSeg`

I guess there may be some problems (maybe path?) when installing TractSeg, but I cannot handle this, could you give me some guidance with this issue?
Thanks in advance.
Li

**Comment by wasserth** [comment]
Unfortunately it is more difficult to test TractSeg on MacOS. It is always tested on Ubuntu. You could try if you can directly install it from github: 
```
pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip
```
