### ISSUE TITLE
tutorial error

### ISSUE THREAD

**Issue by LucSam** [MIC-DKFZ/TractSeg#18]
Hi, after following the tutorial we now receive following error after completion of the 4th step of loading the weights. We tried it on our ubuntu 16.04 LTS system as well as on a macbook pro with Mojave 10.14. It occurs after the 3rd command in the tutorial `TractSeg -i tractseg_output/peaks.nii.gz -o . --output_type TOM --track --filter_tracking_by_endpoints`. We used HCP data.

```
Tracking...
Traceback (most recent call last):
  File "/home/bwgig/anaconda2/bin/TractSeg", line 202, in <module>
    output_format=args.tracking_format)
  File "/home/bwgig/anaconda2/lib/python2.7/site-packages/tractseg/libs/Mrtrix.py", line 172, in track
    " -include " + tmp_dir + "/" + bundle + "_e.nii.gz" +
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by wasserth** [comment]
It is missing a brain mask (per default it looks for a file `nodif_brain_mask.nii.gz` in the input directory). If the default file is not there you have to specify it using `--brain_mask`. I will update the tutorial and the code to make this explicit.

**Comment by LucSam** [comment]
Thank you very much, that solved the problem.

**Comment by wasserth** [comment]
I adapted the code, so now actually no brain mask is needed at all when doing tracking. The tutorial code should work now the way it is.
