### ISSUE TITLE
Low number of fibers within the CC_3 area.

### ISSUE THREAD

**Issue by tc19r** [MIC-DKFZ/TractSeg#180]
Dear experts:

I was trying to use TractSeg to study the fibers in the CC(Corpose Callosum) area, with data from the ADNI database.
While the overall results of the CC is good, the one small bundle: CC_3, usually generates a very low number of fibers, which can vary from 1 to ~100 across subjects.  Same thing happens with two other bundles outside of CC: FX_left, FX_right.

Some information about the dataset:
The DTI dataset come with two b-values: 0, 1000. 
The resolution is 2.7x2.7x2.7mm, but the images were reconstructed with 1.35x1.35x2.7mm voxels (i.e. they were zero padded in x and y).
I apologize that I am not sure if the image in is MNI space, except when I use the --preprocessing command, an error would occur in the tracking step: [IndexError: index 76 is out of bounds for axis 2 with size 59]

Do you know why this might have occurred?
Let me know if you need more information of the experiment.

Thanks,
Chen

**Comment by wasserth** [comment]
The first thing I would recommend is to check the tract segmentation mask for CC_3 and the start and end region segmentation masks (all of those are generated by TractSeg). Do these look good or not? If those are wrong then the tracking also can not work properly.
The FX bundle in general is more difficult as it is quite small. So i would expect it to work not so good especially with your low image resolution.
You should also check if your images are in MNI space. This can really help. You can follow these commands to do this: https://github.com/MIC-DKFZ/TractSeg#aligning-image-to-mni-space

**Comment by wasserth** [comment]
Happy to hear that it worked.
