### ISSUE TITLE
 ImportError: cannot import name 'compress_streamlines' from 'dipy.tracking.streamline'

### ISSUE THREAD

**Issue by TPS-LM** [MIC-DKFZ/TractSeg#181]
Dear Experts

I installed TracSeg and tried to run it. but could not import  'compress_streamlines' from 'dipy.tracking.streamline'.  Regarding the previous similar issue (https://github.com/MIC-DKFZ/TractSeg/issues/178), dipy version 1.5.0 may cause this problem, I installed the latest version of Tractseg from pip install https://github.com/MIC-DKFZ/TractSeg/archive/master.zip.  
However, I couldn't fix this problem and the following message was shown.

`
Traceback (most recent call last):
  File "/home/brain/.local/bin/TractSeg", line 20, in <module>
    from tractseg.libs import plot_utils
  File "/home/brain/.local/lib/python3.8/site-packages/tractseg/libs/plot_utils.py", line 22, in <module>
    from tractseg.libs import fiber_utils
  File "/home/brain/.local/lib/python3.8/site-packages/tractseg/libs/fiber_utils.py", line 10, in <module>
    from dipy.tracking.streamline import compress_streamlines as compress_streamlines_dipy
ImportError: cannot import name 'compress_streamlines' from 'dipy.tracking.streamline' (/home/brain/.local/lib/python3.8/site-packages/dipy/tracking/streamline.py)
` 

I am using TractSeg via Ubuntu with Windows Virtualbox.
python version   3.8.10
pip3 version pip 20.0.2
pytorch was successfully installed.

Is there something that I fix this?

Thanks.

**Comment by wasserth** [comment]
That is strange. Master should work. Does it work if you downgrade dipy, e.g. `pip install --upgrade dipy==1.4.0` ?
