### ISSUE TITLE
tractseg bundle segmentation crops image

### ISSUE THREAD

**Issue by pmn1113** [MIC-DKFZ/TractSeg#183]
Hi,

I am trying to process raw diffusion data to get approximate bundle segmentations with TractSeg. My data has dimensions of 80 x 128 x 128 x 148 and voxel size of 2x2x2. I run this command:

TractSeg -i dwis.nii -o tractseg_output --raw_diffusion_input --preprocess 

My output segmentation files get cropped to 80 x 128 x 127 for some subjects, but not others. Any reason why this might be happening?

**Comment by wasserth** [comment]
This is strange. Does it also happen if you do not use the option `--preprocess` ?
