### ISSUE TITLE
v2.6: Bundles do not align to reference image

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#192]
Hello,

I am using TractSeg 2.6 on my Linux HPC via Singularity. I have been running TractSeg on data that I have reoriented to MNI-orientation via `fslreorient2std`.

I noticed that in the master branch, compared to 2.3 that I used previously, tract files (I have tested on both `--tracking_format` tck and trk) are no longer in DWI space. When I load the tck/trk file in MRView/FSLeyes, the tract file is out of bounds of the DWI reference image (in this case, I used FA).

In version 2.3, as seen below with the left AF, trk and tck map onto the image (top is trk in FSLeyes, bottom is tck in MRView). However, it is worth noting that the left AF appears on the wrong hemisphere for the trk file, while the tck file is correct:
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/27028726/187112189-2df50415-1f39-4bad-a66a-eea71dd7ca88.png">
<img width="512" alt="image" src="https://user-images.githubusercontent.com/27028726/187112243-e30881e0-9f6d-4b80-b763-44e4c17a1b22.png">

Does this have to do with the bug-fix for tracking in non-MNI space introduced in v2.4?

Please let me know if there is any other info I could provide to help debug.

Best,
Steven

**Comment by wasserth** [comment]
Thank you for reporting this problem. Could you provide the image file (the DWI file) so I can try to reproduce the problem on my machine?

**Comment by smeisler** [comment]
Sure, the data may be found here:
https://drive.google.com/drive/folders/1MMy4PxqiN52zCpGyOsEHvmNRrcOwKYmE?usp=sharing

It includes both the original and reoriented data/gradients, as well as the wmfod and peaks of the reoriented image on which I ran TractSeg.

**Comment by smeisler** [comment]
I should also add that the bundle segmentations, beginning/endpoints, and TOMs were aligned to the image as expected in v2.6, it was only the tract files that were misaligned.

**Comment by wasserth** [comment]
I just pushed a fix to the master branch. It should work now.

**Comment by smeisler** [comment]
Works on my end, thanks! Closing the issue.
