### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mrribbits** [MIC-DKFZ/TractSeg#196]
Hi! Not an issue, just a general question/feature request. 

I'm wondering how to easily generate (1) a figure of a specific bundle just like you have in the Tractometry documentation showing the segments in different colors, and (2) a figure of a bundle with the statistically significant segments colored. 

Thx!

**Comment by wasserth** [comment]
Hi, 
figure (1) is not easily possible with TractSeg. I used some separate code for that.
figure (2) can be generated by using the argument `--plot3D pval`.

**Comment by mrribbits** [comment]
Thanks! I didn't realize what --plot3D pval did, that makes sense now.
