### ISSUE TITLE
Feature request: paired t-test?

### ISSUE THREAD

**Issue by mrribbits** [MIC-DKFZ/TractSeg#198]
Hi! It looks like plot_tractometry_results is running an unpaired t-test?  I'm comparing subjects longitudinally, pre and post-test. So is there a way to run a paired t-test instead?  (I can always use the data in csv files in a separate stats package of course, but curious if I can do the stats with plot_tractometry_results since it gives such nice graphic results and corrects for mc so easily).
Thanks!

**Comment by wasserth** [comment]
You would have to adapt the code to run a paired t-test. There is no option to easily change this. If you are not familiar with python I would recommend using the csv files and running the test yourself in any statistics software.

**Comment by mrribbits** [comment]
Ah okay, that is good to know.  Time to become familiar with python I suppose :)
