### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by MSIB76** [MIC-DKFZ/TractSeg#2]
Hi, I'm new to using TractSeg. I tried to do bundle segmentation of the example provided by TractSeg as follow:

Mudathirs-MacBook-Pro:~ mudathirsalman$ ls examples
Diffusion.bvals			Tests
Diffusion.bvecs			example_output.nii.gz
Diffusion.nii.gz		resources
Diffusion_mrtrix_peaks.nii.gz

But I got the following error:

Mudathirs-MacBook-Pro:/ mudathirsalman$ TractSeg -i /examples/Diffusion.nii.gz
Creating brain mask...

Error: input image /examples/Diffusion not valid

rm: /examples/tractseg_output/nodif_brain_mask.nii.gz: No such file or directory
mv: rename /examples/tractseg_output/nodif_brain_mask_mask.nii.gz to /examples/tractseg_output/nodif_brain_mask.nii.gz: No such file or directory
Creating peaks (1 of 3)...
Traceback (most recent call last):
  File "/Users/mudathirsalman/mrtrix3/bin/dwi2response", line 80, in <module>
    app.makeTempDir()
  File "/Users/mudathirsalman/mrtrix3/lib/mrtrix3/app.py", line 226, in makeTempDir
    dir_path = dict.get('ScriptTmpDir', workingDir)
TypeError: descriptor 'get' requires a 'dict' object but received a 'str'
Creating peaks (2 of 3)...
dwi2fod: [ERROR] input file "/examples/Diffusion.bvecs" for option "-fslgrad" not found
Creating peaks (3 of 3)...
sh2peaks: [ERROR] failed to open key/value file "/examples/tractseg_output/WM_FODs.mif": No such file or directory
sh2peaks: [ERROR] error opening image "/examples/tractseg_output/WM_FODs.mif"
Traceback (most recent call last):
  File "/Users/mudathirsalman/anaconda3/bin/TractSeg", line 109, in <module>
    data_img = nib.load(join(HP.PREDICT_IMG_OUTPUT, "peaks.nii.gz"))
  File "/Users/mudathirsalman/anaconda3/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
FileNotFoundError: No such file: '/examples/tractseg_output/peaks.nii.gz'

I checked FSL and MRtrix all are working fine. I wonder where was my mistake. Thanks

**Comment by wasserth** [comment]
It seems like you used an absolute path instead of a relative one. Instead of `TractSeg -i /examples/Diffusion.nii.gz` try using `TractSeg -i examples/Diffusion.nii.gz`  (remove the leading slash)

**Comment by MSIB76** [comment]
Thanks for your reply. I did with your advice. I still get the same error as you can see below:
Mudathirs-MacBook-Pro:~ mudathirsalman$ ls examples
Diffusion.bvals			Tests
Diffusion.bvecs			example_output.nii.gz
Diffusion.nii.gz		resources
Diffusion_mrtrix_peaks.nii.gz
Mudathirs-MacBook-Pro:~ mudathirsalman$ TractSeg -i examples/Diffusion.nii.gz
Creating brain mask...
Creating peaks (1 of 3)...
Traceback (most recent call last):
  File "/Users/mudathirsalman/mrtrix3/bin/dwi2response", line 80, in <module>
    app.makeTempDir()
  File "/Users/mudathirsalman/mrtrix3/lib/mrtrix3/app.py", line 226, in makeTempDir
    dir_path = dict.get('ScriptTmpDir', workingDir)
TypeError: descriptor 'get' requires a 'dict' object but received a 'str'
Creating peaks (2 of 3)...
dwi2fod: [ERROR] no data in matrix file "examples/tractseg_output/response.txt"
dwi2fod: [ERROR] CSD algorithm expects second argument to be the input response function file
Creating peaks (3 of 3)...
sh2peaks: [ERROR] failed to open key/value file "examples/tractseg_output/WM_FODs.mif": No such file or directory
sh2peaks: [ERROR] error opening image "examples/tractseg_output/WM_FODs.mif"
Traceback (most recent call last):
  File "/Users/mudathirsalman/anaconda3/bin/TractSeg", line 109, in <module>
    data_img = nib.load(join(HP.PREDICT_IMG_OUTPUT, "peaks.nii.gz"))
  File "/Users/mudathirsalman/anaconda3/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    raise FileNotFoundError("No such file: '%s'" % filename)
FileNotFoundError: No such file: 'examples/tractseg_output/peaks.nii.gz'

Hope you can find where is my mistake, thanks

**Comment by wasserth** [comment]
This is an error in MRtrix (mrtrix3/app.py). I use the following Mrtrix version: 3.0_RC3. Try using this version.
Otherwise you could also run TractSeg via Docker. This already contains all dependencies. You only have to install docker and then you can simply run TractSeg (see updated Documentation for how to run TractSeg via Docker).
