### ISSUE TITLE
ModuleNotFoundError: No module named 'tractseg.experiments.custom.My_custom_experiment'

### ISSUE THREAD

**Issue by YichengZou626** [MIC-DKFZ/TractSeg#201]
I am trying to use the model to train my own data, but I got this probem. I have used the same method done in #51  but still cannot resolve it.
<img width="852" alt="Screen Shot 2022-09-29 at 3 52 33 PM" src="https://user-images.githubusercontent.com/59714064/193129073-0d2ec1dc-677e-4013-8c37-0c55e65925d8.png">

**Comment by wasserth** [comment]
Does it work if you try writing it in lower cases: my_custom_experiment ?
