### ISSUE TITLE
A lzma warning in the docker

### ISSUE THREAD

**Issue by yanbin-niu** [MIC-DKFZ/TractSeg#203]
Hi!

Hope you are doing well! and Thank you for developing this tool!!

I run successfully with docker. But two quick double check questions:

1. I had this user warning. should this be a concern? 
> /usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.

2. the link in the imageing build file (https://github.com/MIC-DKFZ/TractSeg/archive/master.zip) is the most up-to-date version? I want to make sure I am using the the most up-to-date version.

Any feedback would be much appreciated! Thank you!!

Best,
Yanbin

**Comment by wasserth** [comment]
Hi, 
1: this warning is not familiar to me. I guess you can ignore it.
2: Yes, the master is the most up-to-date version.

**Comment by yanbin-niu** [comment]
Hi! Thank you for answering it! This is very helpful!
