### ISSUE TITLE
98 instead of 100 segments

### ISSUE THREAD

**Issue by mrribbits** [MIC-DKFZ/TractSeg#204]
Hi!  The tractometry documentation states that the bundles get divided into 100 segments, but the csv output only shows 98.

Any idea why that is?

Thanks!

Sample file here:
[Tractometry_TOM_Deterministic_FA.csv](https://github.com/MIC-DKFZ/TractSeg/files/9700666/Tractometry_TOM_Deterministic_FA.csv)

**Comment by wasserth** [comment]
The first and last segment are discarded since they are not as robust. So only 98 are used.
