### ISSUE TITLE
Out of application memory when training the model in terminal

### ISSUE THREAD

**Issue by YichengZou626** [MIC-DKFZ/TractSeg#205]
Hello, I was trying to train the model with my own data, but I got this error. How should I resolve this problem?
<img width="1225" alt="Screen Shot 2022-10-05 at 1 03 54 PM" src="https://user-images.githubusercontent.com/59714064/194119731-a9a76fe2-327f-4d63-929a-03ac2cd15110.png">

**Comment by YichengZou626** [comment]
I also try to use the school server to train the data but got this error message
<img width="1798" alt="Screen Shot 2022-10-08 at 12 08 44 PM" src="https://user-images.githubusercontent.com/59714064/194716900-15af1786-f049-428d-b2a4-6f3f33b12007.png">

**Comment by YichengZou626** [comment]
I set up running memory as 300GB. Is that still not enough for training?

**Comment by wasserth** [comment]
It definitely should not take 300 GB of memory. So something must be wrong. Maybe wrong pytorch installation. You should also try to make APEX work so it works with fp16. Maybe our input data is too big.

**Comment by YichengZou626** [comment]
Got it! The code has been run for 10 hours, but it is still training. I only use 6 HCP subjects for training. Does it take so long to work?
<img width="2240" alt="Screen Shot 2022-10-12 at 1 35 32 PM" src="https://user-images.githubusercontent.com/59714064/195410624-5ae03319-f4ea-4a9d-8b91-ca149e3d38ee.png">

**Comment by wasserth** [comment]
Yes thats normal. Training can take 2-3 days.

**Comment by YichengZou626** [comment]
Got it! Thanks
