### ISSUE TITLE
Docker image build issue

### ISSUE THREAD

**Issue by yanbin-niu** [MIC-DKFZ/TractSeg#207]
Hi experts,

I am having issues to get a native environment, mainly due to the version of dependencies. I met the same issues as https://github.com/MIC-DKFZ/TractSeg/issues/187. I followed their solutions, but the new issues came up:

> TractSeg -h
> OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

Finally, I decided to build a docker, but this `download_all_pretrained_weights` runs forever. I tried to download the link in the `download_all_pretrained_weights` manually -- all has no problem. So, I am a bit clueless now about what I can do to build the image.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/79607547/195371006-377f99eb-ea42-4a97-b5b5-cd743016e5d0.png">

Any advice would be appreciated!!
Thank you!

Yanbin

**Comment by yanbin-niu** [comment]
Sorry for not making things clear. 
More info about what I meant by "download the link in the download_all_pretrained_weights manually" -- I mean, if I just run `python3 download_all_pretrained_weights`, it can successfully download things.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/79607547/195449097-ce8573d1-e89b-4609-a900-ab13d556ff4f.png">

So, I am wondering if there exists a workaround? for example, I can first run `python3 download_all_pretrained_weights`, and comment off the `RUN download_all_pretrained_weights`  in the docker build file?

**Comment by yanbin-niu** [comment]
@wasserth thank you for insights here https://github.com/MIC-DKFZ/TractSeg/issues/194

I also tried downloading things in my computer first:
> COPY ./tractseg_pretrained/pretrained_weights_tract_segmentation_xtract_v1.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_tract_segmentation_v3.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_endings_segmentation_v4.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_dm_regression_xtract_v1.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_dm_regression_v2.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_peak_regression_part1_v2.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_peak_regression_part2_v2.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_peak_regression_part3_v2.npz ~/.tractseg
> COPY ./tractseg_pretrained/pretrained_weights_peak_regression_part4_v2.npz ~/.tractseg

It seems work, though add extra 9 layers.....

**Comment by wasserth** [comment]
I am happy to hear that it works now. Not sure why it does not look in the user home.
Just another tip: You can always download the already built docker image from docker hub. This way you do not have to bother with building it on your own.
