### ISSUE TITLE
Unable to save weights after training the model with my own data

### ISSUE THREAD

**Issue by YichengZou626** [MIC-DKFZ/TractSeg#208]
Hello, I am trying to train the tractseg model with my own data. After running the model, I got this data file for my experiment. But when I use "TractSeg -i 108323/mrtrix_peaks.nii.gz  -o dir --output_type tract_segmentation --exp_name my_custom_experiment" to predict with my own model, I got this error message. How to find the weight file?
<img width="776" alt="Screen Shot 2022-10-19 at 2 17 30 PM" src="https://user-images.githubusercontent.com/59714064/196772862-a01f4fc9-390a-4514-a629-c340564ee170.png">
<img width="565" alt="Screen Shot 2022-10-19 at 2 20 04 PM" src="https://user-images.githubusercontent.com/59714064/196772873-048f82e8-49a5-47c7-a399-2d004a2b6d01.png">
Thanks!

**Comment by wasserth** [comment]
This is strange. The weights should also be in the directory. Unfortunately I do not really have an idea why they are missing for you.

**Comment by YichengZou626** [comment]
I only set the number of epochs to 1. Does that matter? Also, I delete the best weight path for testing, because I try to use the weight after training. I think maybe it's why the weight file is not saved.

**Comment by wasserth** [comment]
Yes, that could be the problem. I think it only saves weights after 5 epochs. So I would set epochs to minimum of 10.
