### ISSUE TITLE
New questions about alignment to MNI image 

### ISSUE THREAD

**Issue by melthy002** [MIC-DKFZ/TractSeg#211]
Hello, TractSeg team!
The question is the following of  issue https://github.com/MIC-DKFZ/TractSeg/issues/167 (sorry for changing a username )
Recently I has reanlayzed my data and a new question about the aligment was arisen. 
I wondering the requirement to alignment to MNI space is specific to the original unproprocessed raw DWI data or 
any data (preprocessed or not) which was put as the input of TractSeg.  The orientation of my raw DWI datasets are silimar to the HCP images, but the preprocessing steps I done (topup & eddy in FSL--generate fod & group template in mrtrix3--change fod_template to peak.nii.gz as tractseg input using sh2peak ) maybe different from Tractseg's default steps, whether the preprocessing step influence the images orientations and how to check? This is the information of my TractSeg input peaks images:
<img width="830" alt="111" src="https://user-images.githubusercontent.com/117813676/200793656-98516051-4010-43b5-9db9-26112633ad18.PNG">

Many thanks!!
Kitty Zhu

**Comment by wasserth** [comment]
Hi, 
if your orientation is similar to HCP images I would just run TractSeg. If you get good segmentations of the different bundles, then you are fine. If not, then I would register the data to MNI space.

**Comment by melthy002** [comment]
Thanks for your response~
