### ISSUE TITLE
Calculate mean FA of a specific tract

### ISSUE THREAD

**Issue by melthy002** [MIC-DKFZ/TractSeg#212]
Hello ! TractSeg team!
   I read related issues #159 and #188 about the calculation of mean FA of one tract, but still cannot make sure whether I did it the right way. In order to make the FA maps in the same template space as track bundle segmentations which was generated by Tractseg based on group fod template, I applied  the subject fod-to-group fod template transformation to  the FA map  and then used the _mrstats_ comamnd to calculate the mean FA. I am wondering whether this is reasonable or there is other more proper ways to do this.
The cmls I used are as follows: 

<img width="732" alt="333" src="https://user-images.githubusercontent.com/117813676/200811488-04055a99-77d5-481c-9829-e5591b853284.PNG">

Thanks very much!
Kitty Zhu

**Comment by wasserth** [comment]
This seems reasonable, but just from looking at this code I can not tell if it is really correct.

I would open the bundle mask from TractSeg and your FA image (FA_inTempSpace.mif) in a medical image viewer. If both of them align properly, then it should be fine.

**Comment by melthy002** [comment]
<img width="844" alt="444" src="https://user-images.githubusercontent.com/117813676/200853581-2324bd7a-99f0-442c-aea1-759b165451f7.PNG">
 I displayed two bundle maks (AF_left&right) and FA image (FA_inTempSpce.nii.gz) simultaneously , it looks align well !
thanks for your advice~
