### ISSUE TITLE
Problems with training own models for start&end regions and TOMs

### ISSUE THREAD

**Issue by YichengZou626** [MIC-DKFZ/TractSeg#216]
Hi, I am trying to train my own models to get bundle-specific tractograms. However, the tutorial only tells me how to train the model for bundle segmentation. I am wondering what the folder structure of your training data should be like for start&end regions and TOMs models. Also, how should I change the parameters inside the code to train those models?

Thanks!

**Comment by wasserth** [comment]
The folder structure basically is the same and the experiment parameters can be seen here:

https://github.com/MIC-DKFZ/TractSeg/blob/master/tractseg/experiments/endings_seg.py
https://github.com/MIC-DKFZ/TractSeg/blob/master/tractseg/experiments/peak_reg.py

"FEATURES_FILENAME" is the filename of the label files in your folder structure.

**Comment by YichengZou626** [comment]
By using this code https://github.com/MIC-DKFZ/TractSeg/blob/master/tractseg/libs/create_endpoints_mask_with_clustering.py, I will get two binary mask files, one for starting and the other for ending. Which one should be used? Also, the input is still the Mrtrix CSD peak file, right?

**Comment by wasserth** [comment]
You have to use both files. One for the endings and one for the beginnings. The endpoint segmentation model thus has the double number of classes (72*2).
Right, the input is still the mrtrix csd peak file.

**Comment by YichengZou626** [comment]
Got it! Thanks so much
