### ISSUE TITLE
Bundle segmentation are not right for some participants while the same processing script is used

### ISSUE THREAD

**Issue by warddef** [MIC-DKFZ/TractSeg#217]
hello, 

I edited the preprocessing script to make it fit my own data, i am now running into a problem where for some participants the bundle segmentation is not done properly while for other it is done perfectly. All participants undergo the same processing script (see link) so i am wondering what the problem could be. All of the images are alligned to mni space and the peaks are supposed to be on the right side, i checked participant motion and this is not the problem. Any idea what might cause this? in the attached link you can find an example of the succesfull bundle segmentations and the botched ones. 

https://kuleuven-my.sharepoint.com/:f:/g/personal/ward_deferm_student_kuleuven_be/EriMHQ_Q389Hkvh35x_QLSUBD_AEx4nkfUwuxBD1et6cPw?e=LrP0KG

Kind regards, 

Ward

**Comment by wasserth** [comment]
Could you also upload the raw Diffusion data as well as the final preprocessed Diffusion data for both images? This is the relevant part.

**Comment by wasserth** [comment]
Thanks for sending these. The preprocessed image is top down (the brain is upside down). So the registration to MNI space did not work apparently. You will have to make your registration work, otherwise the following steps will also not work. Maybe try a different registration method. Or register to another subject in MNI space (instead of your atlas image). Those might also help.

**Comment by warddef** [comment]
Thank you for the fast response, 

My apologies for wasting your time with something so trivial, i should've checked my images in mrview. 
Thank you for the suggestions. 

Kind regards, 

Ward

**Comment by warddef** [comment]
Sorry to reopen this issue but the problem keeps persisting 

as you suggested I tried a variety of different transforms using flirt linear and affine, using a variety of different reference templates (MNI_FA template of tractseg, the MNI_fa of a participant, MNI templates of 1 and 2 mm, the FMRIB58_FA_1mm.nii of FSL and the FSL_HCP1065_FA_1mm.nii template in fsl). None of these resulted in the correct tractseg output. I did notice that there seemed to be something wrong with the calc fa output since all of the values for FA were really high ![screenshot0001](https://user-images.githubusercontent.com/116576571/207598392-d48236a7-13b3-44be-be62-55f0de421425.png), so i redid all of these steps with the FA calculated using fsl and dtifit but even this did not solve the issue. 

I have ran out of things to try, are there any other recommendations that you have or is there an inherent problem with the data for these participants maybe? 

Kind regards, 

Ward

**Comment by warddef** [comment]
To solve this issue, I now use the transformation matrix of a participant for which the transformation was successful and use this matrix as the "rule" for the transformation of the Diffusion data to MNI space. The same is done for the transformation of the FA values to FA_MNI space which I need for my statistics. so the code would look like this. This has solved my problem for participants with wrong output, and tractseg runs without error and is able to reconstruct all of the tracts. 

calc_FA -i Diffusion.nii.gz -o FA.nii.gz --bvals Diffusion.bvals --bvecs Diffusion.bvecs \
--brain_mask nodif_brain_mask.nii.gz

flirt -ref tractseg/tractseg/resources/MNI_FA_template.nii.gz -in FA.nii.gz \
-out FA_MNI.nii.gz  -dof 6 -cost mutualinfo -searchcost mutualinfo -init transformation matrix of subject 15 for which the original code was successful 


flirt -ref tractseg/tractseg/resources/MNI_FA_template.nii.gz -in Diffusion.nii.gz \
-out Diffusion_MNI.nii.gz -applyxfm -init transformation matrix of subject 15 for which the original code was succesfull trans -dof 6
cp Diffusion.bvals Diffusion_MNI.bvals
rotate_bvecs -i Diffusion.bvecs -t FA_2_MNI.mat -o Diffusion_MNI.bvec

I had a discussion about this with a colleague  but we weren't sure if this was proper procedure. We could explain it as using a subject specific template but the participant I chose for this was completely random. Are there any better ways to do this or does it even matter what exact MNI space the subject is in since the neural network of tractseg manages to recognize everything it needed?  Any directions or help you could give me would be greatly appreciated.

**Comment by wasserth** [comment]
I am happy to hear that it works. This should be fine. Using the transformation of a certain subject is ok.
