### ISSUE TITLE
--nr_cpus not used to run dwi2response

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#22]
@wasserth Thank you for adding the --nr_cpus option (https://github.com/MIC-DKFZ/TractSeg/issues/13#issuecomment-432641394) 

However, it looks like this option is not propagated to various commands that TractSeg runs internally. One such command that I noticed was the dwi2response.

dwi2response has the following option

```
  -nthreads number
     Use this number of threads in MRtrix multi-threaded applications (0
     disables multi-threading)
```

I believe nr_cpus option should be used to set this parameter?

**Comment by wasserth** [comment]
So far --nr_cpus is only used for setting the nr of CPUs when doing fiber compression. For all the mrtrix commands and pytorch commands this has no effect. But it certainly makes sense to add this.

**Comment by wasserth** [comment]
--nr_cpus now also affects the mrtrix und pytorch commands

**Comment by soichih** [comment]
@wasserth We just noticed that on the latest version of TractSeg (2.2), mrtrix is still getting executed with more than specified number of CPU cores.

```
 TractSeg -i tractseg_output/peaks.nii.gz --output_type TOM --nr_cpus 8 -o tractseg_output
```

![tractseg-cpu](https://user-images.githubusercontent.com/923896/103921391-7756b680-50e0-11eb-874e-914d49f7d0cb.png)

As you can see graph is exceeding 800% that we are trying to shoot for.

Do you know if --nr_cpus is propagated to mrtrix?
