### ISSUE TITLE
Definition of AF and SLF-III

### ISSUE THREAD

**Issue by melthy001** [MIC-DKFZ/TractSeg#229]
hello, TractSeg team!
 I try to use Tractseg to get AF and SLF-III, but the definition makes me a little bit confused. here are my quesions:
    1)	It appears that there may be a discrepancy between the definition of the tracts used in WMQL and the tracts described in the paper (details see below). I have generated a group template using Tractseg, and the resulting tracts seem larger than expected. Would you kindly provide feedback on whether the tracts appear to be correct?
![AF](https://user-images.githubusercontent.com/38070009/224048264-74c91713-4a63-45c6-b5f6-42749e4dea55.png)

The definition of AF in paper (Wassermann et al., 2016) is as follows: 
Superior longitudinal fascicle III (SLF III) SLF III courses within the frontal and parietal operculum connecting the supramarginal gyrus with the third frontal convolution (Makris et al. 2005).
Arcuate fascicle (AF) The AF is located ventral to the SLF II and dorsal to the extreme capsule and the superior circular sulcus of the insula. It connects the inferior frontal gyrus with the middle temporal gyrus, the posterior part of the superior temporal gyrus and cortices of the lateral temporo-occipital transition region (Catani et al. 2005; Makris et al. 2005).

And  WMQL (https://tract-querier.readthedocs.io/en/latest/) Queries for the tracts writes：
<img width="360" alt="SLF_III_AF_py" src="https://user-images.githubusercontent.com/38070009/224048695-b5b25dd1-4a10-47ce-b58c-4735470596a8.PNG">

 
2)The SLF has been subdivided into four components. Based on my understanding, the AF is not entirely independent of the SLF I/II/III components, would it be accurate to state that the SLF III is a part of the AF, specifically the anterior section of the AF? (Refer to Catani 2004)

Thanks in advance for your help!

Kitty

**Comment by wasserth** [comment]
The SLF and AF are not completely independent. There is a bit over overlapping. But SLF III is also not completely part of AF.  The definitions of those different tracts are often a bit fuzzy and there is no universally accepted precise definition. Therefore, I can not give you a very clear answer unfortunately.

**Comment by melthy001** [comment]
Thanks for your reply.
