### ISSUE TITLE
About trk_2_binary.py

### ISSUE THREAD

**Issue by xiaotaoxinge** [MIC-DKFZ/TractSeg#232]
Dear author, I am sorry to bother you. When I run the file "trk_2_binary.py", the following error occurs：
`Traceback (most recent call last):
  File "trk_2_binary.py", line 87, in <module>
    dm = utils_trk.density_map(streamlines, ref_shape, affine=ref_affine)
TypeError: density_map() got multiple values for argument 'affine'`. How should I solve this problem？

**Comment by wasserth** [comment]
What is the complete command you are calling?

**Comment by wasserth** [comment]
Maybe the nodif_brain_mask.nii.gz image is not a proper nifti image. Can you load it with a normal image viewer and check that it is displayed normally.

**Comment by xiaotaoxinge** [comment]
Thank you for your reply. I have changed line 87 of the code to the following to run.
`dm = utils_trk.density_map(streamlines, ref_affine, ref_shape)`
Thank you again for your reply!
