### ISSUE TITLE
About bundle_masks.nii.gz

### ISSUE THREAD

**Issue by xiaotaoxinge** [MIC-DKFZ/TractSeg#235]
Hello, I'm sorry to bother you. When I trained my own model，I used trk_2_binary.py  to generate 72 bundles for each subject. How do I get the `bundle_masks.nii.gz` mentioned in step 5?

**Comment by czq0827** [comment]
Hi，
I met the same problem as you. Could you please tell me how you solved it? Thank you very much.

**Comment by czq0827** [comment]
> Hello, I'm sorry to bother you. When I trained my own model，I used trk_2_binary.py to generate 72 bundles for each subject. How do I get the `bundle_masks.nii.gz` mentioned in step 5?

**Comment by czq0827** [comment]
> Hello, I'm sorry to bother you. When I trained my own model，I used trk_2_binary.py to generate 72 bundles for each subject. How do I get the `bundle_masks.nii.gz` mentioned in step 5?

Hi，
I met the same problem as you. Could you please tell me how you solved it? Thank you very much.
