### ISSUE TITLE
Training Process Question

### ISSUE THREAD

**Issue by mrrestre** [MIC-DKFZ/TractSeg#244]
Hello and thanks for sharing and answering always the questions! I have another question to the training process. When training with new data as explained in the Readme one is only performing the training on the first FCNN letting the second one really only as an additional option or is the training of the merging directly implemented?

**Comment by wasserth** [comment]
You are correct: This is only training the first FCNN. Also the TractSeg version you can download via pip is also only using the first FCNN. The second one gives only very minor improvements but increases runtime a lot. Therefore, I actually never use it.

**Comment by mrrestre** [comment]
Thanks for the answer! :)
