### ISSUE TITLE
New pypi package

### ISSUE THREAD

**Issue by peterneher** [MIC-DKFZ/TractSeg#252]
Hi Jakob, could you create a new pypi package? The version currently on pypi still wants to install sklearn instead of scikit-learn.

Cheers

**Comment by wasserth** [comment]
Thanks for pointing this out. I will have a look at it.

**Comment by wasserth** [comment]
I just published a new version (v2.9) on pypi.

**Comment by peterneher** [comment]
Nice, thx!
