### ISSUE TITLE
How can I get "bundle_masks.nii.gz"?

### ISSUE THREAD

**Issue by czq0827** [MIC-DKFZ/TractSeg#253]
Hi,
I want to train model, I got data from Zenodo. However, the data only have tracking (.trk) files.
As the tutorial mentioned, the folder structure of training data should include "mrtrix_peaks.nii.gz" and "bundle_masks.nii.gz".
How can I get "bundle_masks.nii.gz"?

**Comment by wasserth** [comment]
Check step 2 in "Train your own model". It links to a script which can help you with that.

**Comment by czq0827** [comment]
> Check step 2 in "Train your own model". It links to a script which can help you with that.

Hello, I have used the script trk_2_binary.py to convert 72 files (.trk) from each subject in the download dataset to their corresponding binary. However, only one bundle_mask_72.nii.gz file is required during training. Could you please tell me how to obtain the bundle_mask_72.nii.gz file in each subject? Thank you very much for your answer.
