### ISSUE TITLE
Deleted wm_fods

### ISSUE THREAD

**Issue by LucSam** [MIC-DKFZ/TractSeg#26]
If we use `--output_type tract_segmentation` TractSeg seems to delete previously written wm_fods. Is there another possibility to keep those without moving them to a different location before using `--output_type tract_segmentation` a second time? This would be helpful, since with our clinical data we sometimes need first to find the proper axis to flip which.

**Comment by wasserth** [comment]
If you use the option `--keep_intermediate_files` you should be able to avoid the deletion.
