### ISSUE TITLE
plot_tractometry_results --plot3D metric gives ValueError 

### ISSUE THREAD

**Issue by Raktonic** [MIC-DKFZ/TractSeg#267]
Hi Community,

Thanks for your hard working on this whole project.

I am currently using TractSeg 2.9 to do Tractometry analysis. I had done all the preprocessing steps for my DWI data. When it comes to plotting results using plot_tractometry_results, I add the option --plot3D metric and edit the subject.txt file correctly.  The mask is generated by myself based on the command from Freesurfer. After I add --plot3D, it gives me the error like this: 
Correcting for comparison of multiple tracts: True
Doing group analysis.
Number of subjects:
  group 0: 32
  group 1: 30
  0%|                                                                                                                                                     | 0/50 [00:03&lt;?, ?it/s]
Traceback (most recent call last):
  File "/home/wei/data/bin/anaconda3/envs/py3.10/bin/plot_tractometry_results", line 384, in &lt;module&gt;
    main()
  File "/home/wei/data/bin/anaconda3/envs/py3.10/bin/plot_tractometry_results", line 375, in main
    plot_tractometry_with_pvalue(values, meta_data, all_bundles, selected_bundles, args.output_path,
  File "/home/wei/data/bin/anaconda3/envs/py3.10/bin/plot_tractometry_results", line 277, in plot_tractometry_with_pvalue
    plot_utils.plot_bundles_with_metric(tracking_path, ending_path, mask_path, bundle, metric,
  File "/home/wei/data/bin/anaconda3/envs/py3.10/lib/python3.10/site-packages/tractseg/libs/plot_utils.py", line 463, in plot_bundles_with_metric
    sl_actor = actor.streamtube(streamlines, colors=colors_all, linewidth=0.2, opacity=1)
  File "/home/wei/data/bin/anaconda3/envs/py3.10/lib/python3.10/site-packages/fury/actor.py", line 683, in streamtube
    poly_data, color_is_scalar = lines_to_vtk_polydata(lines, colors)
  File "/home/wei/data/bin/anaconda3/envs/py3.10/lib/python3.10/site-packages/fury/utils.py", line 317, in lines_to_vtk_polydata
    cols_arr = np.asarray(colors)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2500,) + inhomogeneous part.

This is the command I used: plot_tractometry_results -i /home/wei/data/wei/SZ/tractSeg/subjects.txt -o tractometry_result_MD.png --mc --plot3D metric

But if I don't add --plot3D option, there is no error appearing.
I have no idea about how to fix this. Do you have any ideas with this problem?
Looking forward to your reply. Thanks.

**Comment by EromFreitas** [comment]
Hello,
When you run without _--plot3D_ does the command generate results properly?

Another thing, regarding the command:
`Tractometry -i TOM_trackings/ -o Tractometry_subject.csv -e endings_segmentations/ -s ../MD.nii.gz`

The MD.nii.gz file was extracted from the DWI of the subject registered in MNI space, right?

**Comment by Raktonic** [comment]
Yes, I did tried to run without --plot3D and the command generated results properly like Tractometry_documentation.md written. 

The MD.nii.gz file was extracted from DWI of the subject in native space and then registered MNI space based on the transform matrix from FA.nii.gz to MNI_FA_template.nii.gz.

**Comment by EromFreitas** [comment]
Specific the format of the trackings with the command: ` --tracking_format tck`

**Comment by wasserth** [comment]
The plot3D command is a bit unstable unfortunately and does not work properly in all environments. I would recommend to use it without plot3D.

**Comment by Raktonic** [comment]
I tried to specific the format of the trackings with --tracking_format tck. But it didn't work and has same error I met before. And thanks for your suggestions. I probably would not use --plot3D anymore due to its instability. Thank you so much!
