### ISSUE TITLE
No such file or no access: 'tractseg_output/peaks.nii.gz'

### ISSUE THREAD

**Issue by roeysc** [MIC-DKFZ/TractSeg#29]
EDIT
=
Problem solved. It turns out that the bvals file I used wasn't called "data.bvals", and so mrconvert failed. Using the "--verbose" option let me to the correct error file, which made it all clear.
=

Dear Jakob (and other developers),

First of all, thanks for making this wonderful tool available for the community!

I'm using the latest version of TractSeg (1.9) in an anaconda3 environment on Ubuntu 18.04 (64bit). Usually I can run it with no problems on HCP data (7T diffusion), however now I use the following command:

TractSeg -i /path/to/dwi.nii.gz -o /path/to/outdir --raw_diffusion_input

and  get the following FileNotFoundError:

No such file or no access: 'outdir/peaks.nii.gz'

And indeed, the peaks file is not being created.
Such an error was raised by another user in a closed issue, however I wasn't able to resolve it.

Do you have an idea what might cause this?
Many thanks,
Best,
Roey

**Comment by wasserth** [comment]
Happy to hear that you found the problem.
If your bvals/bvecs do not have the same name as your diffusion data file you have to tell TractSeg by passing their path via `--bvals` and `--bvecs`.
So in your case it should have working if the files were named `dwi.nii.gz`, `dwi.bvals` and `dwi.bvecs`.
