### ISSUE TITLE
loss become minus when train my own model

### ISSUE THREAD

**Issue by gangli95** [MIC-DKFZ/TractSeg#32]
Thanks for your work, and it works pretty well by using pretrained model. However,  the loss become minus when I train my own model.

First, I generated the peak.nii.gz by using the  command you provided, and converted the tract to volume, which is provided on Zenodo. Then I mated all bundles(72) into one 4D img. 

After that, I adapted  _my_custom_experiment.py_  AND  _~/.tractseg/config.txt_ .
Due to the HCP data, the following functions are not changed
_tractseg.libs.DatasetUtils.scale_input_to_unet_shape()
tractseg.libs.exp_utils.get_bundle_names()
tractseg.libs.exp_utils.get_labels_filename()
tractseg.libs.Subjects_

Here is my hyperparameters
> {'BATCH_NORM': False,
>  'BATCH_SIZE': 47,
>  'BEST_EPOCH': 0,
>  'CALC_F1': True,
>  'CLASSES': 'All',
>  'CSD_RESOLUTION': 'LOW',
>  'CV_FOLD': 0,
>  'DATASET': 'HCP',
>  'DATASET_FOLDER': 'HCP',
>  'DATA_AUGMENTATION': False,
>  'DAUG_ELASTIC_DEFORM': True,
>  'DAUG_FLIP_PEAKS': False,
>  'DAUG_INFO': 'Elastic(90,120)(9,11) - Scale(0.9, 1.5) - CenterDist60 - '
>               'DownsampScipy(0.5,1) - Gaussian(0,0.05) - Rotate(-0.8,0.8)',
>  'DAUG_MIRROR': False,
>  'DAUG_NOISE': True,
>  'DAUG_RESAMPLE': True,
>  'DAUG_ROTATE': False,
>  'DAUG_SCALE': True,
>  'DIM': '2D',
>  'DROPOUT_SAMPLING': False,
>  'EPOCH_MULTIPLIER': 1,
>  'EXPERIMENT_TYPE': 'tract_segmentation',
>  'EXP_MULTI_NAME': '',
>  'EXP_NAME': 'my_custom_experiment',
>  'EXP_PATH': 'XXX/hcp_exp/my_custom_experiment_x2',
>  'FEATURES_FILENAME': 'peaks',
>  'FLIP_OUTPUT_PEAKS': True,
>  'GET_PROBS': False,
>  'INFO': '-',
>  'INPUT_DIM': (144, 144),
>  'KEEP_INTERMEDIATE_FILES': False,
>  'LABELS_FILENAME': 'bundle_masks',
>  'LABELS_FOLDER': 'bundle_masks',
>  'LEARNING_RATE': 0.001,
>  'LOAD_WEIGHTS': False,
>  'LOSS_FUNCTION': 'default',
>  'LOSS_WEIGHT': 1,
>  'LOSS_WEIGHT_LEN': -1,
>  'LR_SCHEDULE': False,
>  'MODEL': 'UNet_Pytorch',
>  'MULTI_PARENT_PATH': 'XXX/hcp_exp/',
>  'NORMALIZE_DATA': True,
>  'NORMALIZE_PER_CHANNEL': False,
>  'NR_CPUS': -1,
>  'NR_OF_CLASSES': 72,
>  'NR_OF_GRADIENTS': 9,
>  'NR_SLICES': 1,
>  'NUM_EPOCHS': 250,
>  'OPTIMIZER': 'Adamax',
>  'OUTPUT_MULTIPLE_FILES': False,
>  'PEAK_DICE_LEN_THR': 0.05,
>  'PEAK_DICE_THR': [0.95],
>  'PREDICT_IMG': False,
>  'PREDICT_IMG_OUTPUT': None,
>  'PRINT_FREQ': 20,
>  'RESET_LAST_LAYER': False,
>  'RESOLUTION': '1.25mm',
>  'SAVE_WEIGHTS': True,
>  'SEGMENT': False,
>  'SEG_INPUT': 'Peaks',
>  'SLICE_DIRECTION': 'y',
>  'TEST': False,
>  'TEST_TIME_DAUG': False,
>  'THRESHOLD': 0.5,
>  'TRACTSEG_DIR': 'tractseg_output',
>  'TRAIN': True,
>  'TRAINING_SLICE_DIRECTION': 'xyz',
>  'TYPE': 'single_direction',
>  'UNET_NR_FILT': 64,
>  'UPSAMPLE_TYPE': 'bilinear',
>  'USE_DROPOUT': False,
>  'USE_VISLOGGER': False,
>  'VERBOSE': True,
>  'WEIGHTS_PATH': '',
>  'WEIGHT_DECAY': 0}

To solve the bugs, I changed 2 lines

FIRST:
trainer.py  164
from
```
metrics = metric_utils.calculate_metrics(metrics, None, None, loss, f1=np.mean(f1), type=type,
                                                                 threshold=Config.THRESHOLD)
```
to
```
peak_f1_mean = np.array([s.item() for s in f1]).mean()
metrics = metric_utils.calculate_metrics(metrics, None, None, loss, f1=peak_f1_mean, type=type,
                                                                 threshold=Config.THRESHOLD)
```
for the error
`'torch.dtype' object has no attribute 'type'`

SECOND:
from
```
self.net = NetworkClass(n_input_channels=NR_OF_GRADIENTS, n_classes=self.Config.NR_OF_CLASSES,
                                n_filt=self.Config.UNET_NR_FILT, batchnorm=self.Config.BATCH_NORM,
                                dropout=self.Config.USE_DROPOUT, upsample=self.Config.UPSAMPLE_TYPE)
```
to
```
self.net = NetworkClass(n_input_channels=NR_OF_GRADIENTS, n_classes=self.Config.NR_OF_CLASSES,
                                n_filt=self.Config.UNET_NR_FILT, batchnorm=self.Config.BATCH_NORM,
                                dropout=self.Config.USE_DROPOUT)
```
for the error
`TypeError: __init__() got an unexpected keyword argument 'upsample'`

After these changes above, I can run, but the loss is minus

```
train Ep 0, Sp 940, loss -12.775692, t print 182.392s, t batch 9.12s
train Ep 0, Sp 1880, loss -444671.51571, t print 86.198s, t batch 4.31s
train Ep 0, Sp 2820, loss -2378428503.875, t print 87.207s, t batch 4.36s
train Ep 0, Sp 3760, loss -512482880699494.4, t print 86.612s, t batch 4.331s
train Ep 0, Sp 4700, loss -6.402550831420487e+18, t print 85.732s, t batch 4.287s
```

Is there anything that I missed or wrong?

**Comment by wasserth** [comment]
Hi,
unfortunately it is a bit hard to say what is happening without being able to debug into the code.
First thing I would do is to have a look at x and y in trainer.py line 110 to see if they contain sensible values. Then I would have a look at at base_model.py line 108 to see if the output of the network is sensible. This might help you to understand why the loss is getting negative. 
The two code changes you did should not be related to the negative loss.

**Comment by gangli95** [comment]
Thanks for your reply!
I checked the x in trainer.py, and many elements are minus. Is my peak file wrong?

**Comment by wasserth** [comment]
The peaks file contains negative values. That is correct.

**Comment by gangli95** [comment]
Sorry for my late reply.  As you said, the x should be correct. I also found that all elements in y  are a same positive number, like 1064. However, I didn't solve this error after several hours' trying. Do you know  what the problem is?

**Comment by wasserth** [comment]
y should be a binary array (if you train a tract_segmentation model). All values should be either 0 or 1 (False or True). Are the tract masks you are using binary masks?

**Comment by gangli95** [comment]
Oh, after using binary masks, this problem was solved. Thanks very much. Now, the loss is quite small, begin at 0.55, and 0.024 after 2 epoch. By the way,  how did you convert tract into volume?  I used function _dipy.tracking.utils.density_map_

**Comment by wasserth** [comment]
Happy to hear that it works now. I also use dipy.tracking.utils.density_map. If you feel fancy you can also remove small blobs in the binary mask that are not connected to the rest. Might clean the results a bit.

**Comment by ilyanelken** [comment]
Hey Guys,

I have an additional question regarding the training.
Which TractSeg and batchgenerators versions should I use?

Since I see the developement of both of them is currently in progress.

Thanks in advance,
Ilya

**Comment by gangli95** [comment]
Hi,sorry for my late reply.I just used the commad in readme, and tractseg should be 1.9. By the way, you can convert the bin file, like TractSeg, ExpRunner into .py, then it would completely be a python project. Gang Li Insititute of Automation, CAS ligangdemail@gmail.com Signature is customized by Netease Mail Master On 04/26/2019 02:06, Ilya Nelkenbaum wrote: Hey Guys, I have an additional question regarding the training. Which TractSeg and batchgenerators versions should I use? Since I see the developement of both of them is currently in progress. Thanks in advance, Ilya — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ilyanelken** [comment]
@gangli95 I understand, Thanks! Ilya
