### ISSUE TITLE
Tractometry results

### ISSUE THREAD

**Issue by JoaoPaulo100** [MIC-DKFZ/TractSeg#33]
Dear Jakob,

First of all, thanks for this great tool! 
Using the documentation, I was able to create bundles and extract FA values for most of my sample. 
However, sometimes a subject does not have 1 bundle (for example, the ICP_right - "tract endings mask of ICP_right empty" ) and it does not seem like Tractometry can give me the .csv output with the 71 available. I'm not particularly interested in this bundle now, so I would rather use all the rest at this point. 
Is there a way to do that? 

Thanks!!
João Paulo

**Comment by wasserth** [comment]
Hi Paulo,
sorry for the late reply. I was on vacation...  
At the moment there is no way to run Tractometry for a subset of the bundles (if one bundle is missing). For the bundles that are missing you could create an empty file (containing 0 streamlines). Tractometry should be able to work with that.

**Comment by JoaoPaulo100** [comment]
Thanks for your reply! I'll try that.
Regards,
João Paulo

**Comment by caffeNewbie** [comment]
> Hi Paulo,
> sorry for the late reply. I was on vacation...
> At the moment there is no way to run Tractometry for a subset of the bundles (if one bundle is missing). For the bundles that are missing you could create an empty file (containing 0 streamlines). Tractometry should be able to work with that.


Hello, just wondering if by editing line 121 of bin/Tractometry to read bundles = [".."], it might be possible to run Tractometry for a subset of the bundles. Something similar to the solution mentioned [here](https://github.com/MIC-DKFZ/TractSeg/issues/38#issuecomment-490110351).

**Comment by wasserth** [comment]
That should work. In my previous response I meant that it does not work for a subset of bundles without touching the code. But touching the code it should be quite easy.
