### ISSUE TITLE
Tracking on Peaks or on FOD?

### ISSUE THREAD

**Issue by AntoineBouyeure** [MIC-DKFZ/TractSeg#34]
Dear TractSeg community,

I am using diffusion data with a b=1000 shell and 30 directions. On the tutorial, it is written (if I understood clearly) that for data with poor resolution, the `Tracking` command should be executed with its default behavior, i.e. tracking is performed on peaks, which i did. But I also tried `Tracking` with the `--track_FODs iFOD2` option, i.e. tracking is performed on FOD.

On the image below, you can see the corticospinal tract with tracking performed on peaks on the left, and corticospinal tract with tracking performed on FOD on the right.

![alt text][logo]

[logo]: https://i20.servimg.com/u/f20/19/06/89/72/captur13.png "Logo Title Text 2"

The FOD-tracking looks more... noisy? while it manages to capture fibers that look like they _should_  belong to the CST (the lateral branch and the dorsal fibers of the tract are more complete), comparatively to the peaks-Tracking. For the latter method, it looks like the CST is incomplete.

Below is an image of the CST + AF with peaks-tracking on the left and FOD-tracking on the right.

![alt text][logo2]

[logo2]: https://i20.servimg.com/u/f20/19/06/89/72/captur14.png "Logo Title Text 2"

As you can see, for peaks-tracking, these two tracts have little overlap (white voxels) comparatively to the FOD-tracking method.

Do you have any insights of what could I do to obtain what would appear as an ideal middle ground, i.e. a complete CST (i.e., FOD-tracking), but not too noisy (i.e., peaks-Tracking)?

I also have another dataset with high-resolution multishell data. In this case, which Tracking method should be preferred?

Thanks a lot for your help.

**Comment by wasserth** [comment]
Unfortunately there is no easy answer to this. 
Peaks-tracking is doing tracking on the predicted peaks (Tract Orientation Maps). Moreover it is using a custom tracking implementation which is similar to a deterministic tracking but at each step adds a small random jitter to make it more sensitive. In the end the streamlines are smoothed a little bit to make the streamlines less scrawly.  
FOD-tracking is doing tracking on the FODs. It is using the mrtrix iFOD2 tracking.

So you have 2 different tracking algorithms and 2 different orientation sources (predicted peaks and original FODs). Now you have to decide which one is better for your needs.

There is no straight forward way to get the best out of both.
