### ISSUE TITLE
No more --tracking_format ?

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#36]
I used to be able to output tracking output in .tck format by seeging "--tracking_format tck" command line parameter, but this option doesn't seem to exist anymore. 

```
TractSeg: error: unrecognized arguments: --output_format tck
```

Do I need to manually convert .trk output to .tck now? I am using version 1.9

**Comment by wasserth** [comment]
Tracking is done now using the `Tracking` binary instead of `TractSeg` (see [Changelog](https://github.com/MIC-DKFZ/TractSeg/blob/master/CHANGELOG.md) `Tracking` still accepts the argument `--tracking_format tck`.

**Comment by soichih** [comment]
Thanks for the pointer to the ChangeLog. I was looking under github releases and not much information was there.. so I couldn't figure out what was changed.

I've updated our script to use the Tracking binary and now everything seems to be working. Thanks!

**Comment by wasserth** [comment]
Great to hear that it works now.
