### ISSUE TITLE
How to further segment one of the 72 tracts using end region masks?

### ISSUE THREAD

**Issue by aver123** [MIC-DKFZ/TractSeg#40]
Thanks Jakob once again for this great tool!!
I would like to further segment one of the 72 tracts based on cortical masks. Is there a way to do it with TractSeg? 
Thanks a lot!! Amelia

**Comment by wasserth** [comment]
Hi Amelia,
it is not possible to refine or edit the segmentations with TracSeg. You would have to use a different tool for that, e.g. [MITK Diffusion](http://mitk.org/wiki/MitkDiffusion).

**Comment by aver123** [comment]
Thanks for the prompt response!
Amelia
________________________________
