### ISSUE TITLE
Tractometry sampling

### ISSUE THREAD

**Issue by caffeNewbie** [MIC-DKFZ/TractSeg#41]
Hello,

Just wondering when tractometry code samples FA values along the tract, is this done is a pre-determined way? As in, is the sampling always done in anterior to posterior direction/ or superior-inferior? 

The x-axis of the plot produced is 'position' - I was not quite clear how this maps to anatomical positions.

Thanks,

Surya

**Comment by wasserth** [comment]
It is always starting the sampling from the "beginnings" region that was generated when running `TractSeg ... --output_type endings_segmentation` (e.g. `CST_right_b.nii.gz`). This does not always correspond to anterior/posterior, but is consistent across all subjects.

This is how the evaluation is done then:
It will make sure each streamline starts in the "beginnings" region. Then it will resample each streamline into 20 equally distant segments. Then it will get the FA at each segment for each streamline. Then it will average the FA across all streamlines for each segment.

**Comment by caffeNewbie** [comment]
Is there a way to find out what the 'beginnings' region is for a particular tract? Specifically, I am interested in the corpus callosum.

**Comment by wasserth** [comment]
You can just open the file and look at it, e.g. `endings_segmentations/CST_right_b.nii.gz`.

**Comment by caffeNewbie** [comment]
Sorry if I'm missing something obvious here! I opened the endings segmentations file for CC_b.nii.gz. It is a binary 3D image and I can clearly see that it is the corpus callosum, because of the shape. But how do I figure out which is the 'beginning'? I have uploaded the image as openend in FSLeyes.

![image](https://user-images.githubusercontent.com/13829518/60082736-41372900-972c-11e9-89d1-e063d82761dd.png)

**Comment by wasserth** [comment]
There are two files `CC_b.nii.gz` and `CC_e.nii.gz`.  `_b` is the beginning region and `_e` is the endings region. Does that make it clear?

**Comment by caffeNewbie** [comment]
Ah! That clears things up, thank you.

**Comment by caffeNewbie** [comment]
Hi,

I had another question: perhaps this should be another topic as well.

I ran tractseg for corpus callosum, plotted tractometry between patients and controls; and the FA values are in the range 0.3-05 approximately, in the plot. However, if I open the actual FA image (FA.nii.gz) in ImageJ and check the values in corpus callosum and they seem to be in 0.7-0.9 range. I was wondering why this difference is. If I open the files in a viewer (e.g. MITK), the fibres do seem to be overlaid over the corpus callosum perfectly.

Thanks,

Surya

**Comment by wasserth** [comment]
The reported values are the mean over all streamlines for each segment. For some streamlines the segment will be right in the middle of the CC for others the same segment might be slightly next to it. Therefore the mean can be lower than the maximum value in the CC. But I will do some more investigation into this issue in the next days. Maybe this can be optimized.

**Comment by caffeNewbie** [comment]
I'm not quite sure that averaging across streamlines alone is the issue. I edited the Tractometry code to output maximum/median values instead of the mean and it is still in the lower ranges (~ 0.5 being the peak of the plot). 

I'm also seeing in my dataset, that FA(group A) > FA(group B) in the tractometry plot - whereas in simpler tests such as regression or t tests, I found FA(group A) < FA(group B). 

Hope this helps to debug the issue.

**Comment by wasserth** [comment]
Thank you for these infos. I will do some more investigation.

**Comment by wasserth** [comment]
I did some test myself: When running on a HCP subject and looking at CC_4 I get high values (>0.9) in the middle for the corpus callosum. If I run it on a downsampled HCP subject (2.5mm resolution) I get values around 0.6 because of greatly increased partial voluming. When I use the max instead of the mean to aggregate all streamlines for each segment I also get values >0.9 for the downsampled HCP subject. (I replaced mean by max in line 71 of `bin/Tractometry`). This seems to work as expected.

Regarding your results: What bundle did you look at? What is the resolution of your dataset? When looking at the streamlines do they look good and complete? Did you also try it on HCP data?

**Comment by caffeNewbie** [comment]
I looked at the corpus callosum bundle, on the dataset from ADNI3 - resolution being 2 mm isotropic. I followed the 'best use practice' tips that you recommend for low resolution data. I also set number of fibres to be 10000.

When opening the bundle in MITK diffusion, it seems to be tracked reasonably well considering the resolution.

![image](https://user-images.githubusercontent.com/13829518/60811658-ac9ae500-a187-11e9-92c0-ab48d9fd80aa.png)

A closeup in the axial plane:

![image](https://user-images.githubusercontent.com/13829518/60811756-d8b66600-a187-11e9-99b0-f74709fb8300.png)

Could it be then that the issue is due to the low resolution/partial volume effects?

**Comment by wasserth** [comment]
When I do max for the CC bundle on the downsampled HCP data I also get very high values. It seems quite strange that you do not get high values when using max. If you send me the DWI of the subject I could have a more detailed look at it (j.wasserthal@dkfz.de).

**Comment by caffeNewbie** [comment]
Apologies! There was a mistake in my code. After correcting it, taking the maximum does bring the values to 0.8-0.9 range. Really sorry about the confusion!

So the original issue must relate to averaging across the streamlines. Hopefully this can be optimised.
