### ISSUE TITLE
How to move fibers to subject space?

### ISSUE THREAD

**Issue by zhuozihan** [MIC-DKFZ/TractSeg#44]
Hi all:
I move image to MNI space using --preprocess and generate TOM_trackings (trk format).
How can I move fibers to subject space?

**Comment by wasserth** [comment]
TractSeg generates a file `FA_2_MNI.mat`. This contains the transformation used for moving the input to MNI space. You can invert this ransformation  and use it together with FSL `flirt` and `vecreg` to move the TractSeg output back to subject space. In subject space you can run `Tracking` then.
In the near future I am trying to add this to TractSeg so it is done automatically.

**Comment by wasserth** [comment]
I forgot one thing: You have to add the option `--keep_intermediate_files` otherwise the file `FA_2_MNI.mat` will automatically be removed.

**Comment by zhuozihan** [comment]
Thanks, big help!

**Comment by zhuozihan** [comment]
Well done! Thanks a lot!

**Comment by wangyibin0011** [comment]
> vecreg



> TractSeg生成一个文件`FA_2_MNI.mat`。这包含用于将输入移动到MNI空间的转换。您可以反转此变形，并将其与FSL一起使用`flirt`，`vecreg`并将TractSeg输出移回主题空间。`Tracking`然后，您可以在主题空间中运行。
> 在不久的将来，我尝试将其添加到TractSeg，以便自动完成。



> TractSeg生成一个文件`FA_2_MNI.mat`。这包含用于将输入移动到MNI空间的转换。您可以反转此变形，并将其与FSL一起使用`flirt`，`vecreg`并将TractSeg输出移回主题空间。`Tracking`然后，您可以在主题空间中运行。
> 在不久的将来，我尝试将其添加到TractSeg，以便自动完成。



> TractSeg生成一个文件`FA_2_MNI.mat`。这包含用于将输入移动到MNI空间的转换。您可以反转此变形，并将其与FSL一起使用`flirt`，`vecreg`并将TractSeg输出移回主题空间。`Tracking`然后，您可以在主题空间中运行。
> 在不久的将来，我尝试将其添加到TractSeg，以便自动完成。

What is the concrete implementation here？I can see what you mean, but I don't know exactly how to do it

**Comment by zhuozihan** [comment]
> What is the concrete implementation here？I can see what you mean, but I don't know exactly how to do it

Use "vecreg" to move the fibers output back to subject space.
