### ISSUE TITLE
'move_streamlines' not found in dipy.tracking.utils

### ISSUE THREAD

**Issue by caffeNewbie** [MIC-DKFZ/TractSeg#45]
Hi,

After having to reset my PC, I installed TractSeg again (installation was successful). However, on trying to run some Tractometry codes, the following error comes up:

```
Traceback (most recent call last):
  File "/usr/bin/Tractometry", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/fsluser/Documents/TractSeg-1.9/bin/Tractometry", line 28, in <module>
    from dipy.tracking.utils import move_streamlines
ImportError: cannot import name 'move_streamlines'
```

I checked the file `utils.py` in `python/site-packages/dipy/tracking/` and the function `move_streamlines()` is no longer in there. I was wondering what is happening here.

**Comment by wasserth** [comment]
dipy 1.0 changed its API. I updated TractSeg accordingly in the latest commit. So if you pull the newest master of TractSeg it should work.
