### ISSUE TITLE
cannot access file "/HCP105/599469/T1w/Diffusion/T1w_acpc_dc_restore_brain.nii.gz": No such file or directory

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#46]
Hi.
When I run `TractSeg -i Diffusion.nii.gz -o tractseg_output --raw_diffusion_input --csd_type csd_msmt_5tt --brain_mask nodif_brain_mask.nii.gz` , the following error occurs.

(pytorch) qilu@user-SYS-7048GR-TR:/data1/qilu/HCP105/599469/T1w/Diffusion$ TractSeg -i Diffusion.nii.gz -o tractseg_output --raw_diffusion_input --csd_type csd_msmt_5tt --brain_mask nodif_brain_mask.nii.gz
Creating peaks (1 of 4)...
5ttgen: 
5ttgen: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
5ttgen: 
5ttgen: Generated temporary directory: /data1/qilu/HCP105/599469/T1w/Diffusion/5ttgen-tmp-O35FDC/
mrinfo: [ERROR] cannot access file "/data1/qilu/HCP105/599469/T1w/Diffusion/T1w_acpc_dc_restore_brain.nii.gz": No such file or directory
mrinfo: [ERROR] error opening image "/data1/qilu/HCP105/599469/T1w/Diffusion/T1w_acpc_dc_restore_brain.nii.gz"
5ttgen: [ERROR] Could not access header information for image '/data1/qilu/HCP105/599469/T1w/Diffusion/T1w_acpc_dc_restore_brain.nii.gz'
5ttgen: Contents of temporary directory kept, location: /data1/qilu/HCP105/599469/T1w/Diffusion/5ttgen-tmp-O35FDC/
Creating peaks (2 of 4)...
dwi2response: 
dwi2response: Note that this script makes use of commands / algorithms that have relevant articles for citation. Please consult the help page (-help option) for more information.
dwi2response: 
dwi2response: Generated temporary directory: /data1/qilu/HCP105/599469/T1w/Diffusion/dwi2response-tmp-X8FTEU/
Command:  mrconvert /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.nii.gz /data1/qilu/HCP105/599469/T1w/Diffusion/dwi2response-tmp-X8FTEU/dwi.mif -strides 0,0,0,1 -fslgrad /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvecs /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvals
dwi2response: 
dwi2response: [ERROR] Command failed: mrconvert /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.nii.gz /data1/qilu/HCP105/599469/T1w/Diffusion/dwi2response-tmp-X8FTEU/dwi.mif -strides 0,0,0,1 -fslgrad /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvecs /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvals (dwi2response:86)
dwi2response: Output of failed command:
              mrconvert: [ERROR] input file "/data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvecs" for option "-fslgrad" not found
dwi2response: 
dwi2response: Script failed while executing the command: mrconvert /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.nii.gz /data1/qilu/HCP105/599469/T1w/Diffusion/dwi2response-tmp-X8FTEU/dwi.mif -strides 0,0,0,1 -fslgrad /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvecs /data1/qilu/HCP105/599469/T1w/Diffusion/Diffusion.bvals
dwi2response: For debugging, inspect contents of temporary directory: /data1/qilu/HCP105/599469/T1w/Diffusion/dwi2response-tmp-X8FTEU/
Creating peaks (3 of 4)...
dwi2fod: [ERROR] input file "Diffusion.bvecs" for option "-fslgrad" not found
Creating peaks (4 of 4)...
sh2peaks: [ERROR] cannot access file "tractseg_output/WM_FODs.nii.gz": No such file or directory
sh2peaks: [ERROR] error opening image "tractseg_output/WM_FODs.nii.gz"
Traceback (most recent call last):
  File "/home/qilu/anaconda2/envs/pytorch/bin/TractSeg", line 382, in <module>
    main()
  File "/home/qilu/anaconda2/envs/pytorch/bin/TractSeg", line 253, in main
    data_img = nib.load(peak_path)
  File "/home/qilu/anaconda2/envs/pytorch/lib/python2.7/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: 'tractseg_output/peaks.nii.gz'

Do I need to change the file name to the following form?  
![image](https://user-images.githubusercontent.com/43931240/63239245-ec6fe480-c27c-11e9-9d16-b707079436a6.png)

Or is something wrong? 
![image](https://user-images.githubusercontent.com/43931240/63239272-0ad5e000-c27d-11e9-8fb4-52109c6d347d.png)

**Comment by wasserth** [comment]
Yes, you need to have the files in the form described in the Readme/Tutorial. The T1 file needs to be named `T1w_acpc_dc_restore_brain.nii.gz`and be in the same folder as your `Diffusion.nii.gz` file. (note: the `Diffusion.nii.gz` file can be named differently as you specify this as input parameter)

**Comment by luqily** [comment]
> Yes, you need to have the files in the form described in the Readme/Tutorial. The T1 file needs to be named `T1w_acpc_dc_restore_brain.nii.gz`and be in the same folder as your `Diffusion.nii.gz` file. (note: the `Diffusion.nii.gz` file can be named differently as you specify this as input parameter)

I have renamed files, 
![image](https://user-images.githubusercontent.com/43931240/63269314-85781d00-c2c8-11e9-9f7b-953c9e951732.png)

but the error still exists. 
![image](https://user-images.githubusercontent.com/43931240/63269380-ad678080-c2c8-11e9-8f45-b0615bd72745.png)
![image](https://user-images.githubusercontent.com/43931240/63269416-c07a5080-c2c8-11e9-8d2c-f3665060c3d5.png)

**Comment by wasserth** [comment]
Your Diffusion files are not on the same folder level as your T1 file, but in a subfolder. You have to move `T1w_acpc_dc_restore_brain.nii.gz` into the folder `Diffusion`.

**Comment by luqily** [comment]
> Your Diffusion files are not on the same folder level as your T1 file, but in a subfolder. You have to move `T1w_acpc_dc_restore_brain.nii.gz` into the folder `Diffusion`.

Thanks for your reply! I have moved the file.
But there seems to be a new mistake.
![image](https://user-images.githubusercontent.com/43931240/63271109-fcfb7b80-c2cb-11e9-890e-7b9a18cf779b.png)
![image](https://user-images.githubusercontent.com/43931240/63271121-04bb2000-c2cc-11e9-9372-debe89e67270.png)
![image](https://user-images.githubusercontent.com/43931240/63271130-08e73d80-c2cc-11e9-8d12-66120ced2d1c.png)

**Comment by wasserth** [comment]
Apparently FSL FIRST failed. This is a FSL tool, so I do  not know about the details. Maybe your T1 image has heavy artefacts? Then FSL FIRST might fail? Otherwise you can try with `--csd_type csd_msmt`. This will work without FSL FIRST.

**Comment by luqily** [comment]
> Apparently FSL FIRST failed. This is a FSL tool, so I do not know about the details. Maybe your T1 image has heavy artefacts? Then FSL FIRST might fail? Otherwise you can try with `--csd_type csd_msmt`. This will work without FSL FIRST.

It solved my problem! Thanks very much!
