### ISSUE TITLE
How can I get the bundle_masks.nii.gz?

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#48]
If I want to train my own model, I need files named `bundle_masks.nii.gz (Reference bundle masks; shape: [x,y,z,nr_bundles])`. But I have only 144 independent bundle masks after running TractSeg. Should I put these 144 bundle masks together to get the shape: [x,y,z,nr_bundles]?

**Comment by wasserth** [comment]
I do not quite understand your question, yet. When you run TractSeg you should have 72 bundle masks. 144 probably is the width/height of the images when feeding them to the model.

If you want to train your own model you have to download the training data (https://zenodo.org/record/1477956) and convert the trackings to binary masks (this script can help you with that: https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/utility_scripts/trk_2_binary.py). This will give you the `bundle_masks.nii.gz` files.

**Comment by luqily** [comment]
> I do not quite understand your question, yet. When you run TractSeg you should have 72 bundle masks. 144 probably is the width/height of the images when feeding them to the model.
> 
> If you want to train your own model you have to download the training data (https://zenodo.org/record/1477956) and convert the trackings to binary masks (this script can help you with that: https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/utility_scripts/trk_2_binary.py). This will give you the `bundle_masks.nii.gz` files.

Thanks for your reply!
I have 72 bundle masks, not 144.
