### ISSUE TITLE
Question about the data for training my own model.

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#49]
Hi, I have downloaded the HCP_105 data for training my own model. 
For the second step, should I put these 144 bundle masks together to get the files named `bundle_masks.nii.gz (Reference bundle masks; shape: [x,y,z,nr_bundles])`?
What's more, for the third step, I don't know if the data has been preprocessed. Is whether I'm going to `preprocess the data using tractseg/data/preprocessing.py to remove all non-brain area (crop to brain bounding box). Adapt the data pathes in tractseg/data/preprocessing.py to fit your data (look for #todo: adapt inside of the file.)`

**Comment by wasserth** [comment]
There are 72 bundles, not 144. 144 probably is the spatial dimension (x,y,z).

This data is not yet preprocessed. You have to create the binary masks and then you have to use `tractseg/data/preprocessing.py` to remove the non-brain area.

**Comment by luqily** [comment]
> There are 72 bundles, not 144. 144 probably is the spatial dimension (x,y,z).
> 
> This data is not yet preprocessed. You have to create the binary masks and then you have to use `tractseg/data/preprocessing.py` to remove the non-brain area.

Thanks very much!
