### ISSUE TITLE
Hosting TractSeg on brainlife.io

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#5]
@wasserth Jakob,

(I couldn't find your email address so I appologize in advance for posting it here!) As you might have noticed, I've been playing with TractSeg for the last few weeks and I am super impressed by what it can do! I've tested with a few of HCP dataset as well as some NKI data - both worked nicely!

I am actually a software engineer at Indiana University working for a NSF funded project called [BrainLife](https://brainlife.io) and our platform allows researchers to publish algorithms as Apps and allows users to execute them on our compute resources. Apps can interface with other Apps developed by other researches through the use of registered *datatypes* to easily construct a workflow and explore new ways to use the algorithms.

I've registered an App on BrainLife here.
> https://brainlife.io/app/5b82d7f4e2f4f800275e020f

If you would signup on BrainLife, you will be able to run your App by visiting "Execute" tab via above URL. 

I'd like to know if you have any concerns or questions about our platform and if you could let us publish your App through it. By having your App published on BrainLife, other users can discover and try your App with their own datasets, and take the output from your App and feed it to other registered Apps such as ..

* 3D Tract Surfaces (https://brainlife.io/app/593049d7ff090a00210eff05#) 

This App can take tract masks and generate 3D volumes of the tracts and visualize them online (without having to download any software)

![screenshot from 2018-08-30 12-04-28](https://user-images.githubusercontent.com/923896/44864124-e12b3f80-ac4c-11e8-96e8-5a7f006e8663.png)

The output from 3D tract surfaces can then used by other Apps such as

* Steklov Operator Spectrum (https://brainlife.io/app/59e9f8fc816545002d0910cb#)
* Laplace Beltrami Spectrum (https://brainlife.io/app/5a53b2be56e507002d1a9628)
* Plot Eigenfunctions (https://brainlife.io/app/5a54f0b84f89380027a9a48d#)

etc..

As you can see, users can quickly explore / compare different Apps on our platform and promote code reuse and sharing across different fields of science.

I hope you will be interested in Brainlife, and please feel free to contact me directly at soichih@gmail.com, or on our [slack channel](https://brainlife-inviter.herokuapp.com/) I am looking forward to hearing from you!

Thank you,
Soichi

**Comment by wasserth** [comment]
Looks great! I sent you a message via email.
