### ISSUE TITLE
dwi2fod and sh2peaks are using all cpus.

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#53]
Hi.
When I train my own model, I use this command `TractSeg -i data.nii.gz -o tractseg_output --raw_diffusion_input --csd_type csd_msmt --brain_mask nodif_brain_mask.nii.gz --bvals bvals --bvecs bvecs` to get peaks.
When it meets `dwi2fod` and `sh2peaks` command, I always use all cpus. Is this reasonable?
Is this the right way of training model to get the `mrtrix_peaks.nii.gz (mrtrix CSD peaks;  shape: [x,y,z,9])`?

**Comment by thijsdhollander** [comment]
> When it meets dwi2fod and sh2peaks command, I always use all cpus. Is this reasonable?

If you mean "Is this normal?", then yes: `dwi2fod` and `sh2peaks` by default perform multi-threading with a number of threads equal to the number of CPUs you have; i.e. making optimal (well, "full") use of your resources.

You can create an mrtrix configuration file, and add a `NumberOfThreads` entry: https://mrtrix.readthedocs.io/en/latest/reference/config_file_options.html#cmdoption-arg-numberofthreads , if you need the number of threads to be lower for some reason (e.g. on a shared system, or if you use the machine interactively while processing and you don't want to be slowed down too much).  More info on where to store this kind of configuration file: https://mrtrix.readthedocs.io/en/latest/getting_started/config.html

**Comment by luqily** [comment]
> if you need the number of threads to be lower for some reason (e.g. on a shared system, or if you use the machine interactively while processing and you don't want to be slowed down too much

YES!
Thanks a lot! It's very helpful for me!

**Comment by thijsdhollander** [comment]
No worries. ^_^

**Comment by wasserth** [comment]
In TractSeg you can set the option `--nr_cpus`. This will be passed on to the Mrtrix commands that are called internally by TractSeg. Per default all cpus are used. This also makes sense.  
Your command `TractSeg -i data.nii.gz -o tractseg_output --raw_diffusion_input --csd_type csd_msmt --brain_mask nodif_brain_mask.nii.gz --bvals bvals --bvecs bvecs` is also correct for generating peak images.

**Comment by luqily** [comment]
> In TractSeg you can set the option `--nr_cpus`. This will be passed on to the Mrtrix commands that are called internally by TractSeg. Per default all cpus are used. This also makes sense.
> Your command `TractSeg -i data.nii.gz -o tractseg_output --raw_diffusion_input --csd_type csd_msmt --brain_mask nodif_brain_mask.nii.gz --bvals bvals --bvecs bvecs` is also correct for generating peak images.

Thanks for your reply~ That helps me a lot!
