### ISSUE TITLE
How can I predict the bundles after training the model?

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#54]
Hi.
After training the model, I run this command. `ExpRunner --train=False --test=True --lw --config=My_custom_experiment`
But I can only get bundle metrics. How can I predict the 72 bundles for each test subject?

**Comment by wasserth** [comment]
You can try `--train=False --test=False --seg=True`.

**Comment by luqily** [comment]
`--train=False --test=False --seg` is okay.
What I get is a bundle_masks matrix with dimension (146,174,146,72). I think the order of the 72 bundles in this matrix is the order in the bundles of the training data have been synthesized. Is that  right?

**Comment by wasserth** [comment]
That is correct.
