### ISSUE TITLE
"Tracking" script not available on GPU container

### ISSUE THREAD

**Issue by mattlyon93** [MIC-DKFZ/TractSeg#55]
Tried to run `Tracking` within the GPU docker container, but failed with an error:

> /bin/bash: Tracking: command not found

The command i used was:
`sudo nvidia-docker run -v $in_dir:/data
    -t wasserth/tractseg_container_gpu:1.7.1
    /bin/bash -c "Tracking -i $peaks --tracking_dir $tracking_dir --tracking_format tck --nr_fibers 10000"`

Previous commands such as the one below did work.
`sudo nvidia-docker run -v $in_dir:/data \
    -t wasserth/tractseg_container_gpu:1.7.1 \
    /bin/bash -c "TractSeg -i $peaks --bundle_specific_thr"`

Suggests the `Tracking` script isn't on the `$PATH` within the GPU Docker image?

**Comment by wasserth** [comment]
The gpu container is not up to date anymore, but uses a old version (1.7.1). This version does not have the `Tracking` command yet. Unfortunately it is not so easy for me to update the GPU container. My recommendation would be to use the CPU container or use TractSeg without any container (then it will also use a GPU if available).
