### ISSUE TITLE
The dimension of the predicted data does not match the dimension of the training data.

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#56]
Hi. I have used HCP105 data to train my own model. The shape of `bundle_masks.nii.gz` is (145,174,145,72) and the shape of `mrtrix_peaks.nii.gz` is (145,174,145,9).

But the shape of predicted data is  (146,174,146,72). How can I get the same dimensions as the training data`(145,174,145,72)`?

**Comment by wasserth** [comment]
Internally the U-Net is using a shape of 144. To get back to the original resolution of 145 it will pad with 1 on both sides which leads to 146. It does not automatically support to pad with different numbers on both sides. Therefore you have to manually cut away one voxel:
```
new_data = data[:-1, :, :-1, :]
```

**Comment by wasserth** [comment]
I will try to automate this in the next release.

**Comment by luqily** [comment]
> Internally the U-Net is using a shape of 144. To get back to the original resolution of 145 it will pad with 1 on both sides which leads to 146. It does not automatically support to pad with different numbers on both sides. Therefore you have to manually cut away one voxel:
> 
> ```
> new_data = data[:-1, :, :-1, :]
> ```

Thanks so much!
