### ISSUE TITLE
3D visualization of FA differences

### ISSUE THREAD

**Issue by JoaoPaulo100** [MIC-DKFZ/TractSeg#57]
Dear Jakob, 

Thanks for this great tool. Using the latest version of TractSeg, I got some very interesting results. After correction for multiple comparisons, I have significant findings in specific points (let's say in 4 points of the 20) of one white matter tract and I'm looking for a way to represent these differences on top of the white matter tract picture. Something like this:

![image](https://user-images.githubusercontent.com/47246052/67234427-22fbe400-f413-11e9-86f3-3603d370b1a9.png)

Is there a way to do something similar using TractSeg? 

Thanks,
João Paulo

**Comment by wasserth** [comment]
Hi,
TractSeg can not generate such a visualization automatically. But using for example dipy it should not be too difficult to create such a visualization yourself. Just plot the tracts and color them according to the FA or p-value.

**Comment by JoaoPaulo100** [comment]
Thanks! I'll try that.
