### ISSUE TITLE
Excuse me, what was the reason for reporting the following error when I was working on the cloning project?

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/TractSeg#60]
Cloning into 'TractSeg'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (121/121), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by wasserth** [comment]
This is a `git` problem and nothing specific to TractSeg. Try to google for this problem. You will find a lot on stackoverflow.

**Comment by zlf123-marker** [comment]
Ok, thank you very much
