### ISSUE TITLE
May I ask which part I should change if I align the image with MNI space according to the following warning?

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/TractSeg#63]
flirt -ref /home/zlf/TractSeg/resources/MNI_FA_template.nii.gz -in Diffusion.nii.gz -out Diffusion_MNI.nii.gz -applyisoxfm FA_2_MNI.mat -dof 6
WARNING: sampling 0 less than 0.00001 mm
         Setting to 1.0 sampling instead

**Comment by wasserth** [comment]
This seems like an FSL warning. You have to consult the FSL documentation / mailing list for more details regarding the FSL warnings.

**Comment by zlf123-marker** [comment]
Thank you very much
