### ISSUE TITLE
Unusual issue with registration of tractography

### ISSUE THREAD

**Issue by JustinGarber** [MIC-DKFZ/TractSeg#65]
Hi
Thanks for your great program. I am having an unusual issue with generating bundle tractograms. I am able to create bundle segmentations, ending segmentations and TOM maps well with the basic commands as per Git instructions, but when I do:
Tracking -i peaks.nii.gz;
the resultant streamlines are not aligned to the dwi image or the bundle, ending or TOM segmentations. Please see the image below of the CST, but this applies to every bundle. Do you know why this may occur?
I have tried the deterministic tractography, and FODs tracking, and they all seem to be aligned normally. Only the probabilistic tractography is misaligned.
![Screen Shot 2019-10-29 at 9 55 48 am](https://user-images.githubusercontent.com/57091738/67724668-de380480-fa33-11e9-90e3-e88f2320da82.png)
![Screen Shot 2019-10-29 at 9 57 41 am](https://user-images.githubusercontent.com/57091738/67724678-e55f1280-fa33-11e9-8ef6-55127a34d0a0.png)

Also I wanted to know if there was an option to just create streamlines (or segmentations for that matter) for the CST without the other 70 white matter bundles.

Regards
Justin

**Comment by wasserth** [comment]
Hi,
which version of TractSeg are you using?
Per default it is not possible to create streamlines only for a subset of the bundles. But you could easily change the classes in the source code:
You would have to adapt line 140 in `tractseg/bin/Tracking`. For example you could replace it with the following line:
```
bundles = ["CST_right", "CST_left"]
```
Then it will only track those two bundles.

**Comment by JustinGarber** [comment]
Thanks for that tip about the bundles.

I am using the latest TractSeg version, 2.1. Only installed a few days ago.

**Comment by wasserth** [comment]
Is your input image properly aligned with MNI space? Could you share the affine matrix of it?

**Comment by JustinGarber** [comment]
Maybe not.

Is this the affine matrix? From mrinfo readout:

  Transform:      0.9997     0.02348     0.00989      -134.6
                         -0.02387      0.9988     0.04161      -101.1
                        -0.008902    -0.04184      0.9991      -41.76

**Comment by wasserth** [comment]
The easiest way to make it work would be to rigidly align it with MNI space (see [here](https://github.com/MIC-DKFZ/TractSeg#aligning-image-to-mni-space) for details).

If you could share the peaks file with me I could have a more detailed look if it could also work without MNI space.

**Comment by JustinGarber** [comment]
Thanks, Ill have a look at how it goes with aligning to MNI.

Happy to send you the peaks file. It's too big to send here (49MB). Can I send it to your email?

**Comment by wasserth** [comment]
You can send it by email: j.wasserthal@dkfz.de

**Comment by wasserth** [comment]
It is a little bit more complicated unfortunately. I pushed an update but it only solves part of the problem. It works now, but only if the affine does not contain any rotation (all off-diagonal elements have to be 0). In your case it contains rotation.

So you can either remove the rotation or make the orientation the same as MNI space (then the rotation does not matter).

In you case the easiest would be to invert the y-axis 
```
image = image[:, ::-1, :, :]
affine[1,1] *= -1
```
Then your image has the same orientation as MNI space and everything should work fine.

**Comment by JustinGarber** [comment]
Thanks for looking into that.
I'm sorry I don't know how to implement the inversion of the y-axis as you wrote it there.
Is that a code I should put into tractseg/bin/TractSeg?

**Comment by wasserth** [comment]
You have to write an extra script for that which you call on the data before you run TractSeg.

You could put the following python code into a new file:

```
import sys
import nibabel as nib

args = sys.argv[1:]
file_in = args[0]    # file_in
file_out = args[1]   # file_out
axis = args[2]       # x / y / z

img = nib.load(file_in)
data = img.get_data()

newAffine = img.affine.copy()

if axis == "x":
    data = data[::-1, :, :]  # flip x Axis
    newAffine[0, 0] = newAffine[0, 0] * -1
    newAffine[0, 3] = newAffine[0, 3] * -1  
elif axis == "y":
    data = data[:, ::-1, :]  # flip x Axis
    newAffine[1, 1] = newAffine[1, 1] * -1
    newAffine[1, 3] = newAffine[1, 3] * -1  
elif axis == "z":
    data = data[ :, :, ::-1]  # flip x Axis
    newAffine[2, 2] = newAffine[2, 2] * -1
    newAffine[2, 3] = newAffine[2, 3] * -1  

new_image = nib.Nifti1Image(data, newAffine)
nib.save(new_image, file_out)
```

Then call it the following way:
`python my_script.py data.nii.gz data_flipped.nii.gz y`

**Comment by JustinGarber** [comment]
Thanks. That has it working well.

Justin
