### ISSUE TITLE
Excuse me, I would like to ask where the weight file pretrained_weights_tract_segmentation_v3.npz has been downloaded

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/TractSeg#72]

**Comment by wasserth** [comment]
I gets downloaded to `~/.tractseg`.

**Comment by zlf123-marker** [comment]
Is it a hidden file?I can't find it. How can I drag it to the local area?

**Comment by wasserth** [comment]
It is a hidden directory. In the terminal you can just navigate there by typing in the path.

**Comment by zlf123-marker** [comment]
Thank you very much
