### ISSUE TITLE
Finding the coordinates of the points along white matter tract

### ISSUE THREAD

**Issue by skebaas** [MIC-DKFZ/TractSeg#77]
Hello Jakob,

We would like to obtain the (x,y,z) coordinates of the points along the white matter tracts and use them to plot a model in another program.  Is there a file containing these files that is outputted by the program and/or an additional function to obtain these coordinates?

Thank you,
Alex

**Comment by wasserth** [comment]
Hi Alex,
not sure if I understand your question correctly. Each streamline is made up of points with (x,y,z) coordinates. You can easily get those from the *.trk files. But I guess you mean something else.

**Comment by skebaas** [comment]
Thank you Jakob,

Would you mind specifying how to obtain those values from the .trk files?

**Comment by wasserth** [comment]
Have a look at this code in `bin/Tractometry`:

```
            if args.tracking_format == "trk_legacy":
                streams, hdr = trackvis.read(trk_path)
                streamlines = [s[0] for s in streams]
            else:
                sl_file = nib.streamlines.load(trk_path)
                streamlines = sl_file.streamlines
```
`streamlines` is a list of all streamlines. Each streamline is a list of points (x,y,z).

**Comment by skebaas** [comment]
We printed the streamlines and noticed that it gives us each point along the tract for _all_ fibers.  Is there are variable that outputs the average position of the points along each fiber for all bundles (i.e. AF_left.trk), or is that something that we will have to do ourselves?

**Comment by wasserth** [comment]
Getting the average position is not so easy. First: There are different ways of what you might define as the "average". Do you mean a centroid line? Do you mean resampling all streamlines to the same number of points then take the average for all points with the same index?
