### ISSUE TITLE
Tractometry

### ISSUE THREAD

**Issue by JoaoPaulo100** [MIC-DKFZ/TractSeg#78]
Hello Jakob,

Thanks again for this great tool! Using tckedit, I was able to further segment ATR_left.tck. 
I'm particularly interested in the part of the tract that goes into VLPFC. Now, I need to extract values (FA) for my analysis and I would like to use tractometry. My question: using this selection as my new ATR_left.tck, would tractometry work correctly and give me values only for this specific selection? Maybe there is a problem I still don't realize. 

Thanks!
João

**Comment by wasserth** [comment]
Hi João,
in general this is possible. There is only one thing which might become a problem: Tractometry is using the endings_segmentation mask to align all streamlines of one bundle to start in the same region. So you have to make sure your new ATR_left has its streamlines end in the endings_segmentation masks. Then it should work. You can just replace the old ATR_left.tck by our new ATR_left.tck and run Tractometry.

**Comment by JoaoPaulo100** [comment]
Hi Jakob,
Thank you so much!
João
