### ISSUE TITLE
Question about Tracking

### ISSUE THREAD

**Issue by schoffelen** [MIC-DKFZ/TractSeg#79]
Dear Jakob,

Thanks very much for this awesome piece of work! I am a very naive to Diffusion-Weighted Imaging, and only recently started to look into this, on a ~200 subject dataset (thus ideally requiring more or less automated pipelines).
My own field of expertise is electrophysiology (EEG/MEG), and as a side note, I am one of the core developers of the fieldtrip-toolbox for electrophysiological data analysis https://github.com/fieldtrip/fieldtrip. This is just to give some background info, not to do self advertisement.
Anyway, long story short, I came across your pipeline after playing around with tracula and autoPtx (and not being too happy with either approach to be honest). Overall, my initial experience with TractSeg, followed by Tracking (both following your documentation, i.e. applying it more or less in default mode) is very good, but I noticed that in some cases the tract trk-files are very sparse, i.e. they contain very few streamlines. My question now is whether there are any options that I can tweak in order to get 'better' results (where better is then defined as getting 'thicker' bundles)? And related to this, is there any possibility to run the Tracking on a subset of tracks? 
Let me know if this is not the appropriate platform to discuss this, and thanks again for your work and for sharing it.

**Comment by wasserth** [comment]
Hi,
I am happy to hear that you like TractSeg. 
So far there is no option to track only a subset of the bundles. But it is very easy to adjust the code accordingly. 
First clone the repository. Then add `bundles = ["CST_right", "CA", ....]` (replace by your bundles) into line 141 of `tractseg/bin/Tracking`. Then install your local copy of tractseg by going into the tractseg directory and doing `pip install .`  
If the tract trk files are very sparse you can check the following things:
- look at the bundle segmentation masks generated with TractSeg and check if they look good or are missing parts (if they are missing parts this will of course affect the tracking). Something else might be wrong leading to bad results.
- look at the TOM peaks (using e.g. MRtrix `mrview` and in mrview load them via Tool->Fixel plot). Do they look reasonable?
- If both the segmentation and the TOMs look good, you can increase the sensitivity of the probabilistic tracking, by increasing the "randomness". However, this will make the result more noisy and less dependent on the signal. Therefore this has to be done carefully. To do this increase the parameter `next_step_displacement_std` in line 101 in `tractseg/bin/Tracking`. Default is `0.15`. Increasing to `0.2` should be fine. Everything above `0.3` is nonsense. I would not go higher than `0.25`, better `0.2`.

**Comment by wasserth** [comment]
I added an option `--bundles` to `Tracking` to manually specify a subset of bundles. So you do not have to change it in the code anymore.

**Comment by schoffelen** [comment]
Thanks for the suggestions and the update to the code, Jakob!
