### ISSUE TITLE
.tck instead of .trk

### ISSUE THREAD

**Issue by LucSam** [MIC-DKFZ/TractSeg#8]
Thank you very much for providing TractSeg.
Where exactly can I change the output format of the tractography files from .trk to .tck or add an additional .tck output to the existing .trk?

Since csd etc. is performed within mrtrix and all my other pipelines and workflows are using mrtrix, I would like to be able to stay within and use mrview for visualisation instead of trackvis.

The python script trk2tck.py outputs erroneous files, furthermore, I'd rather like to output a .tck file directly.
Thank you very much in advance, Lucius

**Comment by wasserth** [comment]
So far there is not option for selecting the output format. I will add that.
You can also run mrtrix tracking on your own. Just use `tckgen -algorithm FACT` on the TOM output. That's what TractSeg is also doing internally.

**Comment by LucSam** [comment]
ok thank you very much for your answer, looking forward for the option, best

**Comment by wasserth** [comment]
If you use the most recent master branch there is an option `--tracking_format trk|tck` now. Now TOM and tracking also supports 72 bundles instead of only 20.

**Comment by LucSam** [comment]
Thank you, that's very great. What's your motive behind the FACT algorithm? I used a TOM output with subsequent `tckgen -alg ifod2` and was quite happy with the result - I tested with the standard `-cutoff 0.05` and as well `-cutoff 0.1` and -`cutoff 0.2`.

**Comment by soichih** [comment]
@LucSam @wasserth A stupid question.. I thought TractSeg was to segment the volume - not the fibers. Where does the .tck output come from? Does TractSeg segment volume as well as generate/segment tracts?

@LucSam 
> The python script trk2tck.py outputs erroneous files,
I am using nibabel.streamline.load() / save(). Could you elaborate on how you are converting trk2tck?

```
#!/usr/bin/env python
import json
import nibabel

with open('config.json') as config_json:
    config = json.load(config_json)

print("loading trk")
trk = nibabel.streamlines.load(config["trk"])
print(trk)

print("saving track.tck")
nibabel.streamlines.save(trk.tractogram, "track.tck")
print("done")
```

**Comment by wasserth** [comment]
@LucSam The branch `TOM_72bundles` is now merged into `master`. So you can also use `master`.
@LucSam The reason why I am using FACT (= deterministic tracking) is that the TOM output is just giving you one peak. So in difference to the output of Constrained Spherical Deconvolution it does not contain a measure of variance that would be used to do probabilistic tracking (iFOD2). I am not so familiar with the details of iFOD2 so I am not sure what they are doing if you only input a peak and not a FOD. That's the reason I only used FACT so far. I was quite happy with the results so I did not try any other algorithm so far. I also think FACT is faster than iFOD2, but have not tested it yet.
@soichih TractSeg can also generate so called Tract Orientation Maps which can then be used for bundle specific tracking (https://arxiv.org/abs/1806.05580). Moreover TractSeg can segment the start and end region of bundles. Often also helpful for filtering all fibers ending somewhere in between.

**Comment by LucSam** [comment]
@wasserth thanks for your answer, I see. If your interested: I use a different mrtrix3 pipeline for csd generation, so for msmt_csd I include and output all response functions and fod's (wm.txt wm.mif gm.txt gm.mif csf.txt csf.mif) since it will affect the fod generation, which I noticed by looking at TractSeg's generated WM_FODs. Including and generating all responses and fod's will then result in not having fod's in the csf.
For subsequent tractography I use the wm.mif instead of TractSeg's WM_FODs and use the TOM output just as a seeding image. This combination provided nice tractography results.

**Comment by wasserth** [comment]
Ok I see. So you use the TOM output only as a binary seeding mask? In that case I would recommend not using `--output_type TOM` but `--output_type tract_segmentation`(default). This is a bit more accurate than TOM if you only need binary tract segmentations.
