### ISSUE TITLE
IndexError: index -2 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by soichih** [MIC-DKFZ/TractSeg#80]
The TractSeg is failing with this error message (TractSeg 1.9 on PSC Bridges via singularity)

```
$ TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd_msmt_5tt --output_type tract_segmentation --keep_intermediate_files --postprocess --nr_cpus 8 -o .
...
Traceback (most recent call last):
  File "/usr/local/bin/TractSeg", line 303, in <module>
    main()
  File "/usr/local/bin/TractSeg", line 252, in main
    inference_batch_size=inference_batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/python_api.py", line 225, in run_tractseg
    seg = img_utils.postprocess_segmentations(seg, blob_thr=blob_size_thr, hole_closing=2)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/img_utils.py", line 187, in postprocess_segmentations
    data_single = remove_small_blobs(data_single, threshold=blob_thr, debug=False)
  File "/usr/local/lib/python2.7/dist-packages/tractseg/libs/img_utils.py", line 145, in remove_small_blobs
    second_largest_blob_value = np.sort(counts)[-2]
IndexError: index -2 is out of bounds for axis 0 with size 1
```

Prior to this error message, it was displaying the following warning from 5ttcheck..

```
hayashis@xps13:~/Downloads 2 5ttcheck 5TT.mif 
5ttcheck: [WARNING] Image "5TT.mif" contains 24 brain voxels with non-unity sum of partial volume fractions
5ttcheck: [WARNING] Input image does not perfectly conform to 5TT format, but may still be applicable (suggest re-running using the -masks option to see voxels where tissue fractions do not sum to 1.0)
```

I am not sure how to check the 5TT.mif, but I do see some artifacts(?) on the 5TT.mif Is this why TractSeg is failing?

![Screenshot from 2019-11-22 09-19-59](https://user-images.githubusercontent.com/923896/69433326-6941ad00-0d09-11ea-9e80-4a59d71d635c.png)

-so

**Comment by wasserth** [comment]
First I would check the peaks that were generated by TractSeg. If those look fine, then the warning from 5TT should be ok. You can plot the peaks for example with MRtrix `mrview` and then load them via Tools->fixel plot.
The problem might be that the segmentation masks are actually empty and therefore the postprocessing fails. This should be fixed in newer TractSeg versions. Then it will return the empty masks. Would be also interesting to see if the masks are indeed empty.

**Comment by soichih** [comment]
peaks.nii.gz looks fine?

![Screenshot from 2019-11-22 10-25-01](https://user-images.githubusercontent.com/923896/69438034-66978580-0d12-11ea-8461-ad013fa6f784.png)

And when you say mask, do you mean "nodif_brain_mask.nii.gz" right? It looks fine also?

![Screenshot from 2019-11-22 10-31-43](https://user-images.githubusercontent.com/923896/69438588-4d430900-0d13-11ea-9280-9b605eefd118.png)

Should I try the new version (2.1.1?) of TractSeg? Also I can send you the t1 and dwi data I am using if you are interested..

**Comment by soichih** [comment]
I found an issue with the way we were preprocessing dwi (flipped bvec-x). I've updated it and now TractSeg is finishing successfully. Would it explain the error message I was seeing?

**Comment by wasserth** [comment]
Incorrectly flipped bvecs can lead to this issue. So I guess this was the reason. For some datasets it can be a bit tricky to get the bvecs correctly flipped.

**Comment by soichih** [comment]
Thanks for the confirmation. I am going to close this issue for now.
