### ISSUE TITLE
How can I get the orginal dataset in the paper Tract Orientation Mapping for Bundle-Specific Tractography

### ISSUE THREAD

**Issue by liu0haha123** [MIC-DKFZ/TractSeg#82]
Hello Jakob,

I have a research about the Tract Orientation Mapping. I downloaded the dataset the provided in that paper.But that dataset is used for the paper Tractseg. How could I get the dataset that used to train the model in《Tract Orientation Mapping for Bundle-Specific Tractography》

**Comment by wasserth** [comment]
Hi,
I used the command `MitkFiberDirectionExtraction.sh` from MITK Diffusion to generate peak images from tractograms. It is part of the MITK Diffusion miniapps. Getting MITK Diffusion to run can be a bit difficult unfortunately.
