### ISSUE TITLE
Plotting FA values or p-values on segments for tracts

### ISSUE THREAD

**Issue by malwina-molendowska** [MIC-DKFZ/TractSeg#85]
I did the Tractometry for my group analysis. For now, I plot statistical results only as a tract profiles (script: plot_tractometry_results). I would like to ask is there a possibility to visualize the results i.e. "projected" FA values / p-values on tracts segments as in Tractometry_documentation.md

I will be grateful for any help on this topic!

**Comment by wasserth** [comment]
Hi,
so far there is no code available for this. You would have to code this yourself. I recommend using e.g. Dipy for this.

**Comment by malwina-molendowska** [comment]
Thanks for the information!
