### ISSUE TITLE
Statistical testing for repeated measurements design

### ISSUE THREAD

**Issue by malwina-molendowska** [MIC-DKFZ/TractSeg#86]
My TractSeg analysis is a single group analysis that was scanned multiple times i.e. I have a repeated measurements (RM) design e.g. 30 subjects scanned 4 times during training.

Do you have any recommendations for statistical testing? Should it be just simple RM-anova implemented in this permutation based approach?

**Comment by wasserth** [comment]
Unfortunately I am not an expert on statistics. I implemented the TractSeg statistical analysis based on [AFQ from Yeatman et al.](https://github.com/yeatmanlab/AFQ/blob/master/functions/AFQ_MultiCompCorrection.m). Everything which goes beyond this I can not give reliable recommendations.
