### ISSUE TITLE
T1 volume registration

### ISSUE THREAD

**Issue by zhuozihan** [MIC-DKFZ/TractSeg#87]
Hi, I have got fibers by using TractSeg and Tracking. 

```
TractSeg -i Diffusion.nii.gz --raw_diffusion_input
TractSeg -i peaks.nii.gz --output_type endings_segmentation
TractSeg -i peaks.nii.gz --output_type TOM
Tracking -i peaks.nii.gz --tracking_dilation 1 --nr_fibers 4000
```

But the Diffusion.nii.gz and T1.nii.gz are not in the same position and resolution. How can I register the fibers to T1 volumes? Would you give some suggestions?

**Comment by wasserth** [comment]
You can use FSL flirt to rigidly register the the T1 image to the b0 image. Then your T1 image will be in the same space as the fibers.
The code should be similar to the following code: https://github.com/MIC-DKFZ/TractSeg#aligning-image-to-mni-space

**Comment by zhuozihan** [comment]
How can I get the b0 image?

**Comment by zhuozihan** [comment]
Thanks! But how can I get the b0 image?

**Comment by wasserth** [comment]
It's normally the first volume/channel of your DWI image. There are for example some FSL commands for splitting a DWI image / 4D image into its channel. I think it was `fslsplit`.

**Comment by zhuozihan** [comment]
Now I got the b0 image with voxel size [2, 2, 2]. I used the following command to register t1 image with voxel size [1, 1, 1], but the registration result looks not well (downsampling the t1 image):

```
flirt -ref b0.nii.gz -in t1.nii.gz -out t1reg.nii.gz -dof 6
```

Emm.....What's wrong?

[b0.nii.gz](https://github.com/MIC-DKFZ/TractSeg/files/3916057/b0.nii.gz)
[t1.nii.gz](https://github.com/MIC-DKFZ/TractSeg/files/3916059/t1.nii.gz)

**Comment by zhuozihan** [comment]
I got the resolution from https://github.com/MRtrix3/mrtrix3/blob/52a2540d7d3158ec74d762ad5dd387777569f325/docs/troubleshooting/FAQ.rst

Thank you!

**Comment by wangyibin0011** [comment]
> 现在，我得到了体素大小为[2，2，2]的b0图像。我使用以下命令以体素大小[1，1，1]注册t1图像，但是注册结果看起来不太好（对t1图像进行下采样）：
> 
> ```
> flirt -ref b0.nii.gz -in t1.nii.gz -out t1reg.nii.gz -dof 6
> ```
> 
> 恩.....怎么了？
> 
> [b0.nii.gz ](https://github.com/MIC-DKFZ/TractSeg/files/3916057/b0.nii.gz)
> [t1.nii.gz](https://github.com/MIC-DKFZ/TractSeg/files/3916059/t1.nii.gz)

Hello，How to create b0.nii file?

**Comment by wasserth** [comment]
You could use mrtrix for example: https://mrtrix.readthedocs.io/en/latest/reference/commands/dwiextract.html

**Comment by wangyibin0011** [comment]
Hello, it seems that T1 and b0 cannot generate normal pose transformation matrix,This is my order：
dwiextract Diffusion_MNI.nii.gz -fslgrad Diffusion_MNI.bvecs Diffusion_MNI.bvals -bzero b0.nii.gz
flirt -ref b0.nii.gz -in t1.nii.gz -out t1_MNI.nii.gz -omat t1_MNI.mat -dof 6 -cost mutualinfo -searchcost mutualinfo
flirt -ref t1.nii.gz -in t1.nii.gz -out t1_MNI.nii.gz -applyxfm -init t1_MNI.mat -dof 6
@wasserth 
[t1.nii.gz](https://github.com/MIC-DKFZ/TractSeg/files/4357905/t1.nii.gz)
[b0.nii.gz](https://github.com/MIC-DKFZ/TractSeg/files/4357906/b0.nii.gz)

**Comment by wangyibin0011** [comment]
@zhuozihan May I ask what is your specific implementation method? Can you share it? Thank you very much
