### ISSUE TITLE
Train model: can not download the data from Zenodo

### ISSUE THREAD

**Issue by zhuozihan** [MIC-DKFZ/TractSeg#88]
Hi,
I want to train my own model, but the Zenodo data doesn't seem to exist.
How can I get them?
Thank you!

**Comment by wasserth** [comment]
The link in the Readme was somehow broken. I fixed it. This link should work:
https://doi.org/10.5281/zenodo.1088277

**Comment by zhuozihan** [comment]
> The link in the Readme was somehow broken. I fixed it. This link should work:
> https://doi.org/10.5281/zenodo.1088277

I got it! However, the data only have tracking (.trk) files.
As the tutorial mentioned, the folder structure of training data should include "mrtrix_peaks.nii.gz" and "bundle_masks.nii.gz":
```
custom_path/HCP/subject_01/
      '-> mrtrix_peaks.nii.gz       (mrtrix CSD peaks;  shape: [x,y,z,9])
      '-> bundle_masks.nii.gz       (Reference bundle masks; shape: [x,y,z,nr_bundles])
```
How can I get them?

**Comment by liu0haha123** [comment]
Sorry to bother you. I have same problem with you. And wasserth  told me to use the command MitkFiberDirectionExtraction.sh from MITK Diffusion to generate peak images from tractograms.
But I fail to use it correctly .

**Comment by zhuozihan** [comment]
> Sorry to bother you. I have same problem with you. And wasserth told me to use the command MitkFiberDirectionExtraction.sh from MITK Diffusion to generate peak images from tractograms.
> But I fail to use it correctly ，if you solve it,could you share the way with me.Thank you

Hi, liu0haha123. I want to train my own model using clinical DWI images, but the tutorial is a bit simple to guide to do it. Do you have some suggestions?

**Comment by liu0haha123** [comment]
> > Sorry to bother you. I have same problem with you. And wasserth told me to use the command MitkFiberDirectionExtraction.sh from MITK Diffusion to generate peak images from tractograms.
> > But I fail to use it correctly ，if you solve it,could you share the way with me.Thank you
> 
> Hi, liu0haha123. I want to train my own model using clinical DWI images, but the tutorial is a bit simple to guide to do it. Do you have some suggestions?

I tried to use the dataset that wasserth provides,but i have the same porblem with you. i don't konw how to generate peaks from the dataset,too. And I tried to simulate fibers ,but without masks,the fiber is out of the range of brain. I am not fimliar with the clinical data. You can see the issue that I commit,maybe it will help you.
https://github.com/MIC-DKFZ/TractSeg/issues/82#issue-527848642

**Comment by zhuozihan** [comment]
> > > Sorry to bother you. I have same problem with you. And wasserth told me to use the command MitkFiberDirectionExtraction.sh from MITK Diffusion to generate peak images from tractograms.
> > > But I fail to use it correctly ，if you solve it,could you share the way with me.Thank you
> > 
> > 
> > Hi, liu0haha123. I want to train my own model using clinical DWI images, but the tutorial is a bit simple to guide to do it. Do you have some suggestions?
> 
> I tried to use the dataset that wasserth provides,but i have the same porblem with you. i don't konw how to generate peaks from the dataset,too. And I tried to simulate fibers ,but without masks,the fiber is out of the range of brain. I am not fimliar with the clinical data. You can see the issue that I commit,maybe it will help you.
> [#82 (comment)](https://github.com/MIC-DKFZ/TractSeg/issues/82#issue-527848642)

Thank you! We have a common goal, maybe we can communicate by email.
Mine is: zihan_zhuo@hotmail.com
