### ISSUE TITLE
How to train my own model?

### ISSUE THREAD

**Issue by zhuozihan** [MIC-DKFZ/TractSeg#89]
Hi, all! I want to train my own model. 
I have download the zenodo data but it only have tracking (.trk) files. As the tutorial mentioned, the folder structure of training data should include "mrtrix_peaks.nii.gz" and "bundle_masks.nii.gz":

custom_path/HCP/subject_01/
      '-> mrtrix_peaks.nii.gz       (mrtrix CSD peaks;  shape: [x,y,z,9])
      '-> bundle_masks.nii.gz       (Reference bundle masks; shape: [x,y,z,nr_bundles])
How can I get them?

Another question: if I want to train my own model using clinical DWI images, how should I do?

Thank you!

**Comment by wasserth** [comment]
Download the HCP data and run MRtrix CSD for the HCP data to get the mrtrix_peaks.nii.gz files.

Convert the bundles to binary masks (bundle_masks.nii.gz) by using this script: https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/utility_scripts/trk_2_binary.py

With the binary masks you can create a segmentation model. If you want to train a TOM model it becomes more difficult as you have to convert the streamlines to peak maps. This can be done with MitkFiberDirectionExtraction.sh with MITK Diffusion. But this is difficult.

**Comment by liu0haha123** [comment]
> Download the HCP data and run MRtrix CSD for the HCP data to get the mrtrix_peaks.nii.gz files.
> 
> Convert the bundles to binary masks (bundle_masks.nii.gz) by using this script: https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/utility_scripts/trk_2_binary.py
> 
> With the binary masks you can create a segmentation model. If you want to train a TOM model it becomes more difficult as you have to convert the streamlines to peak maps. This can be done with MitkFiberDirectionExtraction.sh with MITK Diffusion. But this is difficult.

Sorry to bother you again. I have the same problem with zhuozihan . How could Iget the reference_file that used in trk_2_binary.py

**Comment by wasserth** [comment]
You can just use any brain mask from the HCP data as reference file.

**Comment by liu0haha123** [comment]
> You can just use any brain mask from the HCP data as reference file.

Sorry，I use this file to gernate brain_mask but  mask I get is like this  
![image](https://user-images.githubusercontent.com/35953547/71163766-b7a28700-2288-11ea-96ae-8657ef6ce47b.png)
And the reference I use is this [https://github.com/liu0haha123/utils/blob/master/nodif_brain_mask.nii.gz](url)
So i get nothing When I generate peaks. What necessary I miss? Or the reference file is wrong,Thank you.
