### ISSUE TITLE
Specifying additional tckgen options

### ISSUE THREAD

**Issue by meconomou** [MIC-DKFZ/TractSeg#90]
Thanks for this nice collection of tools and all the work that has gone into it!

I was wondering if it's possible to include additional desirable options for tracking with tckgen e.g. specifying minlength, maxlength, etc... Would simply changing the code to add the extra options be sufficient? Or is that something you would advise against?

Many thanks!

**Comment by wasserth** [comment]
You can just change the part in the code where `tckgen` is called and add the parameters you want (the `tckgen` calls are in `tractseg/tractseg/libs/tracking.py`). In this case you have to clone the TractSeg source code and install it locally.
This should be fine.

**Comment by meconomou** [comment]
Thank you!
