### ISSUE TITLE
Use T1 with existing peaks

### ISSUE THREAD

**Issue by jguerrerogon** [MIC-DKFZ/TractSeg#91]
Thank you for this great tool. If I understand correctly, the structural T1W image is used in the tracking part of the process and not in the spherical deconvolution part. Would it be possible to provide the T1W image along with previously computed peaks in order to take advantage of the anatomical information during tracking? Or is this limited to use with raw diffusion data as input?

Thanks, 

-- Jose

**Comment by wasserth** [comment]
Hi,
the T1w image is not needed at any point (also not for tracking).
You might only need it, if you use multi-shell multi-tissue CSD.
During tracking the T1 image can not be incorporated.

**Comment by jguerrerogon** [comment]
Got it, thanks!
