### ISSUE TITLE
move_to_subject_space

### ISSUE THREAD

**Issue by trichtu** [MIC-DKFZ/TractSeg#93]
when I use --preprocess,, there is raising an error in  in my /DATA/envs/anaconda3/bin/TractSeg at line 388:
"""
if args.preprocess and not Config.EXPERIMENT_TYPE == "peak_regression":
            if Config.SINGLE_OUTPUT_FILE:
                preprocessing.move_to_subject_space(Config.PREDICT_IMG_OUTPUT, Config.EXPERIMENT_TYPE, output_subdir=output_subdir,
                                                    output_float=output_float)
    """
I think """move_to_subject_space""" should change to """move_to_subject_space_single_file""" for solving this problem.

**Comment by wasserth** [comment]
Thanks for pointing out this error. I fixed it.
