### ISSUE TITLE
Coordinate mismatch between original DTI data and subject_space_bundles

### ISSUE THREAD

**Issue by trichtu** [MIC-DKFZ/TractSeg#94]
when I use --preprocess, the bundles segmentations in subejct space is not match the original DTI data, for the resolution in two are not the same. How could make it the same in corrdinate without registration.
DTI_data
 """
data_type	FLOAT32
dim1		128
dim2		128
dim3		84
dim4		33
datatype	16
pixdim1		2.000000
pixdim2		2.000000
pixdim3		2.000001
pixdim4		10.000001
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+"""

Bundles Segmentation
"""
data_type	FLOAT32
dim1		132
dim2		132
dim3		87
dim4		72
datatype	16
pixdim1		1.930000
pixdim2		1.930000
pixdim3		1.930000
pixdim4		1.000000
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+
"""

**Comment by wasserth** [comment]
This seems strange. Would it be possible to share your DTI data so I can try to reproduce the problem?
