### ISSUE TITLE
timestamp field in .tck header

### ISSUE THREAD

**Issue by jguerrerogon** [MIC-DKFZ/TractSeg#96]
Dear Jakob, 

I am trying to map voxel values (e.g. from an FA map) onto their corresponding streamline points. I am using mrtrix's 'tcksample' to achieve this, but get a complaint about the 'timestamp' field missing from the header of the .tck file. Upon running mrtrix's 'tckinfo' on the .tck file, indeed there is no field named 'timestamp'. Would you have any suggestions for either:

1. incorporating this information into the header. 
or 
2. an alternative approach for mapping voxel values to streamline vertices. 

Best, 

--Jose

**Comment by wasserth** [comment]
I am using dipy to plot the FA values onto the streamlines. You can adapt the following code from the diyp tutorial:
https://dipy.org/documentation/1.1.1./examples_built/viz_bundles/

I the coming weeks I will try to add code for this into TractSeg.

**Comment by jguerrerogon** [comment]
This is great, thanks! 

On a related note, what tools did you use for visualizing tract segments like you do for the cortico-spinal tract in the tractometry tutorial?

**Comment by wasserth** [comment]
I used dipy for the visualization in the tractometry tutorial.
